// SPDX-License-Identifier: AGPL-3.0-only
//! Package files: `pyproject.toml`, `README.md`, `py.typed`, the shared
//! helpers module `_internal.py` and the hand-editable
//! `<module>/custom/__init__.py`.

use std::collections::BTreeSet;

use tungsten_ir::{AuthScheme, CompositePart, IdempotencyKind, Safety};

use crate::ops::{OpShape, has_preview, safety_str};
use crate::options::{HTTPX_RANGE, Models, Options, PYDANTIC_RANGE, RuntimeDep};
use crate::plan::{MemberKind, Plan};
use crate::py::{LINE_LENGTH, string_lit};

/// A TOML basic string (JSON string escapes are valid TOML escapes).
fn toml_str(s: &str) -> String {
    string_lit(s)
}

pub(crate) fn pyproject(plan: &Plan<'_>, opts: &Options, header: &str) -> String {
    let runtime = match &opts.runtime {
        RuntimeDep::Spec(spec) => format!("tungsten-runtime{spec}"),
        RuntimeDep::Path(_) => "tungsten-runtime".to_string(),
    };
    let mut out = String::new();
    out.push_str(header);
    out.push_str("\n\n[build-system]\nrequires = [\"hatchling>=1.25\"]\nbuild-backend = \"hatchling.build\"\n\n");
    out.push_str("[project]\n");
    out.push_str(&format!("name = {}\n", toml_str(&opts.package)));
    out.push_str(&format!("version = {}\n", toml_str(&opts.version)));
    out.push_str(&format!(
        "description = {}\n",
        toml_str(&format!(
            "Python SDK for the {} API, generated by tungsten.",
            tungsten_ir::title_stem(&plan.ir.api.title)
        ))
    ));
    out.push_str("readme = \"README.md\"\nrequires-python = \">=3.12\"\ndependencies = [\n");
    let mut deps = vec![runtime];
    if opts.models == Models::Pydantic {
        deps.push(format!("pydantic{PYDANTIC_RANGE}"));
    }
    deps.push(format!("httpx{HTTPX_RANGE}"));
    for dep in deps {
        out.push_str(&format!("  {},\n", toml_str(&dep)));
    }
    out.push_str("]\nclassifiers = [\n  \"Programming Language :: Python :: 3\",\n  \"Typing :: Typed\",\n]\n\n");
    out.push_str(&format!(
        "[tool.hatch.build.targets.wheel]\npackages = [{}]\n",
        toml_str(&opts.module)
    ));
    if let RuntimeDep::Path(path) = &opts.runtime {
        out.push_str(&format!(
            "\n# The runtime from a local checkout (uv; pip installs the published package).\n[tool.uv.sources]\ntungsten-runtime = {{ path = {} }}\n",
            toml_str(path)
        ));
    }
    out.push_str(&format!(
        "\n[tool.ruff]\nline-length = {LINE_LENGTH}\ntarget-version = \"py312\"\n\n[tool.ruff.lint]\nselect = [\"E\", \"F\", \"I\", \"B\", \"UP\", \"SIM\", \"RUF\"]\n# Descriptor data and docstrings are not wrapped; docstrings and literals\n# quote the API description's text, typographic characters included.\nignore = [\"E501\", \"RUF001\", \"RUF002\", \"RUF003\"]\n\n[tool.pyright]\ntypeCheckingMode = \"strict\"\npythonVersion = \"3.12\"\n"
    ));
    out
}

/// The hand-editable template. Never overwritten once it exists.
pub(crate) fn custom_template() -> String {
    "\"\"\"Hand-written extensions of this SDK.\n\n\
     tungsten creates this module once and never overwrites or deletes it (every\n\
     path under a `custom/` directory is yours). It is imported by the package\n\
     as `custom`.\n\
     \"\"\"\n"
        .to_string()
}

/// `<module>/_internal.py`: helpers the generated modules share.
pub(crate) fn internal_file(header: &str, models: Models) -> String {
    match models {
        Models::Pydantic => format!("{header}\n{INTERNAL}"),
        Models::Dataclasses => format!("{header}\n{INTERNAL_DATACLASSES}"),
    }
}

/// `_internal.py` of a package with dataclass models: the validation
/// machinery is the runtime's (`tungsten_runtime.schema`), so this module
/// only names it for the generated code, plus the client helpers.
const INTERNAL_DATACLASSES: &str = r#""""Helpers shared by the generated modules; not part of the package's API."""

from __future__ import annotations

import dataclasses
from collections.abc import Mapping, Sequence
from typing import Literal

from tungsten_runtime import (
    UNSET,
    AuthConfig,
    ClientOptions,
    MacroDescriptor,
    OperationDescriptor,
)
from tungsten_runtime.schema import (
    Arg,
    Binary,
    Bytes,
    Float,
    Int,
    Int32,
    Limits,
    Model,
    Never,
    Request,
    Response,
    Tag,
    all_of,
    exact,
    field,
    model,
    one_of,
    pattern,
    string_format,
    tag,
    union,
)

__all__ = [
    "Arg",
    "Binary",
    "Bytes",
    "Float",
    "Int",
    "Int32",
    "Limits",
    "Model",
    "Never",
    "Request",
    "Response",
    "Tag",
    "all_of",
    "args",
    "client_options",
    "exact",
    "field",
    "model",
    "one_of",
    "pattern",
    "string_format",
    "tag",
    "union",
]


def args(values: Mapping[str, object]) -> dict[str, object]:
    """The arguments of a call without the ones left ``UNSET``."""
    return {k: v for k, v in values.items() if v is not UNSET}


def client_options(
    options: ClientOptions | None,
    operations: Sequence[OperationDescriptor],
    macros: Sequence[MacroDescriptor],
    *,
    base_url: str | None,
    auth: AuthConfig | None,
    timeout_ms: int | None,
    validate_responses: Literal["off", "warn", "strict"] | None,
    headers: Mapping[str, str] | None,
) -> ClientOptions:
    """``options`` with the keyword arguments of a client constructor applied
    and the API's operations and macros registered first."""
    base = options if options is not None else ClientOptions()
    changes: dict[str, object] = {
        "operations": [*operations, *base.operations],
        "macros": [*macros, *base.macros],
    }
    shortcuts: dict[str, object] = {
        "base_url": base_url,
        "auth": auth,
        "timeout_ms": timeout_ms,
        "validate_responses": validate_responses,
        "headers": headers,
    }
    changes.update({k: v for k, v in shortcuts.items() if v is not None})
    return dataclasses.replace(base, **changes)
"#;

const INTERNAL: &str = r#""""Helpers shared by the generated modules; not part of the package's API."""

from __future__ import annotations

import base64
import binascii
import dataclasses
import re
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from types import ModuleType
from typing import Annotated, Any, Literal, cast

from pydantic import (
    AfterValidator,
    BaseModel,
    BeforeValidator,
    ConfigDict,
    Discriminator,
    Field,
    PlainSerializer,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    TypeAdapter,
    ValidationError,
    ValidationInfo,
    ValidatorFunctionWrapHandler,
    WrapValidator,
    model_serializer,
)
from pydantic_core import PydanticCustomError, PydanticSerializationError
from tungsten_runtime import (
    UNSET,
    AuthConfig,
    ClientOptions,
    Invalid,
    Issue,
    MacroDescriptor,
    OperationDescriptor,
    Valid,
)


class Model(BaseModel):
    """Base of the generated models.

    Validation is strict (no coercion between JSON types: ``"1"`` is not an
    integer; an integral number such as ``1.0`` is, as in JSON Schema and
    the TypeScript SDK: see ``Int``), fields accept their Python name or their
    wire name (no field's Python name is another field's wire name), and fields
    left ``UNSET`` are omitted when the model is dumped, so
    ``model_dump(by_alias=True)`` and ``model_dump(mode="json", by_alias=True)``
    give the wire form.
    """

    model_config = ConfigDict(populate_by_name=True, protected_namespaces=(), strict=True)

    @model_serializer(mode="wrap")
    def _omit_unset(self, handler: SerializerFunctionWrapHandler, info: SerializationInfo) -> Any:
        data = handler(self)
        if not isinstance(data, dict):
            return data
        out = cast("dict[str, Any]", data)
        for name, field in type(self).model_fields.items():
            if getattr(self, name, None) is UNSET:
                wire = field.serialization_alias if field.serialization_alias is not None else name
                out.pop(wire if info.by_alias else name, None)
        return out


def _decode_base64(value: str) -> bytes:
    try:
        return base64.b64decode(value, validate=True)
    except (binascii.Error, ValueError) as error:
        raise ValueError("expected a base64 string") from error


def _is_file(value: object) -> bool:
    """A binary value the runtime reads itself (``tungsten_runtime``
    ``Validator``): a bytearray or memoryview, a binary file object, or a
    ``(filename, content[, content_type])`` tuple."""
    if isinstance(value, bytearray | memoryview):
        return True
    if isinstance(value, tuple):
        parts = cast("tuple[object, ...]", value)
        return len(parts) in (2, 3) and (parts[0] is None or isinstance(parts[0], str))
    return callable(getattr(value, "read", None))


#: Validation context of a request argument sent as JSON: a bytes field is
#: base64 in the body, so it takes ``bytes`` (a bytearray or memoryview is
#: copied), never text or a file.
JSON_ARGUMENT = {"argument": "json"}
#: Validation context of a multipart, form or binary body argument: a bytes
#: field takes ``bytes`` or a file the runtime reads, never text.
FILE_ARGUMENT = {"argument": "file"}


def _bytes(value: object, handler: ValidatorFunctionWrapHandler, info: ValidationInfo) -> Any:
    """A bytes field. As a request argument (``JSON_ARGUMENT``,
    ``FILE_ARGUMENT``) it takes bytes, as the TypeScript SDK takes a
    ``Uint8Array``, plus files in a multipart body; elsewhere (a response, a
    model built by hand) a string is base64 as in JSON, and a file is kept
    for a multipart body."""
    context: object = info.context
    argument = cast("Mapping[str, object]", context).get("argument") if isinstance(context, Mapping) else None
    if isinstance(value, str):
        if argument is not None:
            raise PydanticCustomError("bytes_type", "Input should be bytes, not text")
        return handler(_decode_base64(value))
    if argument == "json":
        if isinstance(value, bytearray | memoryview):
            return handler(bytes(cast("bytes", value)))
        if _is_file(value):
            raise PydanticCustomError("bytes_type", "Input should be bytes: a file is sent only in a multipart body")
        return handler(value)
    return value if _is_file(value) else handler(value)


def _bytes_or_file(value: Any, handler: ValidatorFunctionWrapHandler) -> Any:
    return value if _is_file(value) else handler(value)


def _serialize_bytes(value: Any) -> Any:
    if isinstance(value, bytes | bytearray | memoryview):
        return base64.b64encode(cast("bytes", value)).decode("ascii")
    raise ValueError("a file or text cannot be sent as base64 bytes in JSON; pass bytes")


def _plain(value: Any) -> Any:
    """A non-JSON body's value for the runtime to encode: models as mappings
    by wire name without ``UNSET`` fields (extras kept), lists as lists, and
    everything else (bytes, files, file tuples, dates) as it is."""
    if isinstance(value, BaseModel):
        out: dict[str, Any] = {}
        for name, field in type(value).model_fields.items():
            item = getattr(value, name)
            if item is not UNSET:
                out[field.serialization_alias if field.serialization_alias is not None else name] = _plain(item)
        for key, item in (value.model_extra or {}).items():
            out[key] = _plain(item)
        return out
    if isinstance(value, Mapping):
        return {k: _plain(v) for k, v in cast("Mapping[object, object]", value).items()}
    if isinstance(value, list):
        return [_plain(v) for v in cast("list[object]", value)]
    return value


type Bytes = Annotated[
    bytes,
    WrapValidator(_bytes),
    PlainSerializer(_serialize_bytes, when_used="json"),
]
"""Bytes; a base64 string in JSON. As a request argument it takes bytes; a
file object or a ``(filename, content[, content_type])`` tuple only in a
multipart body, where the runtime reads it."""

type Binary = Annotated[bytes, WrapValidator(_bytes_or_file)]
"""A whole binary request body: bytes, or a file object or ``(filename,
content[, content_type])`` tuple the runtime reads."""

def _integral(value: object) -> object:
    if isinstance(value, float) and value.is_integer():
        return int(value)
    return value


type Float = Annotated[float, Field(allow_inf_nan=False)]
"""A number: finite, as in JSON (``nan`` and infinities are not numbers
there, and the TypeScript SDK rejects them)."""

type Int = Annotated[int, BeforeValidator(_integral)]
"""An integer. JSON Schema's ``integer`` is any number without a fractional
part, so ``1.0`` (what a JSON parser may give for ``1.0`` on the wire) is the
integer ``1``; ``1.5``, ``"1"`` and ``True`` are not integers."""

type Int32 = Annotated[int, BeforeValidator(_integral), Field(ge=-(2**31), le=2**31 - 1)]
"""A 32-bit integer (see ``Int``)."""


def _reject(value: Any) -> Any:
    raise ValueError("no value is valid here")


type Never = Annotated[Any, AfterValidator(_reject)]
"""A schema no value satisfies."""


def _keep(value: Any) -> Any:
    return value


def pattern(source: str) -> AfterValidator:
    """A JSON Schema ``pattern`` (searched, not anchored). A pattern Python's
    ``re`` cannot compile is not enforced, so importing the SDK never fails;
    the server still validates it."""
    try:
        compiled = re.compile(source)
    except (re.error, OverflowError, RecursionError):
        return AfterValidator(_keep)

    def check(value: str) -> str:
        if compiled.search(value) is None:
            # The pattern between slashes, as the TypeScript SDK quotes it.
            raise PydanticCustomError(
                "string_pattern_mismatch", "String should match pattern /{pattern}/", {"pattern": source}
            )
        return value

    return AfterValidator(check)


_DATE = (
    r"(?:(?:[0-9][0-9][2468][048]|[0-9][0-9][13579][26]|[0-9][0-9]0[48]|[02468][048]00|[13579][26]00)-02-29"
    r"|[0-9]{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12][0-9]|3[01])|(?:0[469]|11)-(?:0[1-9]|[12][0-9]|30)"
    r"|(?:02)-(?:0[1-9]|1[0-9]|2[0-8])))"
)
_IPV4_PART = r"(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])"
_H16 = r"[0-9a-fA-F]{1,4}"
_FORMATS: dict[str, re.Pattern[str]] = {
    "uuid": re.compile(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"),
    "email": re.compile(r"[^\s@\"]{1,64}@[^\s@]{1,255}"),
    "date-time": re.compile(
        _DATE + r"T(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:\.[0-9]+)?(?:Z|[+-](?:[01][0-9]|2[0-3]):[0-5][0-9])"
    ),
    "date": re.compile(_DATE),
    "ipv4": re.compile(rf"(?:{_IPV4_PART}\.){{3}}{_IPV4_PART}"),
    "ipv6": re.compile(
        rf"(?:(?:{_H16}:){{7}}{_H16}|(?:{_H16}:){{1,7}}:|(?:{_H16}:){{1,6}}:{_H16}|(?:{_H16}:){{1,5}}(?::{_H16}){{1,2}}"
        rf"|(?:{_H16}:){{1,4}}(?::{_H16}){{1,3}}|(?:{_H16}:){{1,3}}(?::{_H16}){{1,4}}|(?:{_H16}:){{1,2}}(?::{_H16}){{1,5}}"
        rf"|{_H16}:(?:(?::{_H16}){{1,6}})|:(?:(?::{_H16}){{1,7}}|:))"
    ),
}


def string_format(name: str) -> AfterValidator:
    """A JSON Schema string ``format`` the SDK checks (``uuid`` as any
    8-4-4-4-12 hex form, ``email``, ``date-time`` with a ``Z`` or numeric
    offset, ``date``, ``ipv4``, ``ipv6``), with the same rules as the
    TypeScript SDK, so both accept the same values."""
    compiled = _FORMATS[name]

    def check(value: str) -> str:
        if compiled.fullmatch(value) is None:
            raise PydanticCustomError("string_format", "String should be a valid {format}", {"format": name})
        return value

    return AfterValidator(check)


def _same(a: object, b: object) -> bool:
    """JSON equality: ``True`` is not ``1``, ``1`` is ``1.0``."""
    same_type = type(a) is type(b)
    if isinstance(a, bool) or isinstance(b, bool):
        return isinstance(a, bool) and isinstance(b, bool) and a == b
    if isinstance(a, int | float) and isinstance(b, int | float):
        return a == b
    if isinstance(a, Mapping) and isinstance(b, Mapping):
        ma = cast("Mapping[object, object]", a)
        mb = cast("Mapping[object, object]", b)
        return ma.keys() == mb.keys() and all(_same(ma[k], mb[k]) for k in ma)
    if isinstance(a, list | tuple) and isinstance(b, list | tuple):
        sa = cast("Sequence[object]", a)
        sb = cast("Sequence[object]", b)
        return len(sa) == len(sb) and all(_same(x, y) for x, y in zip(sa, sb, strict=True))
    return same_type and a == b


def one_of(values: Sequence[object]) -> AfterValidator:
    """Admits exactly the JSON values ``values`` (an ``enum`` or ``const``
    with members a ``Literal`` cannot express)."""

    def check(value: Any) -> Any:
        if not any(_same(value, v) for v in values):
            raise ValueError(f"expected one of {list(values)!r}")
        return value

    return AfterValidator(check)


def exact(values: Sequence[object]) -> BeforeValidator:
    """Checks a ``Literal`` of booleans or integers without Python's
    equality, before the ``Literal`` does: ``True`` is not ``1`` and ``1`` is
    not ``True`` (JSON types), ``1.0`` is ``1``."""

    def check(value: Any) -> Any:
        if isinstance(value, bool | int | float) and not any(_same(value, v) for v in values):
            raise PydanticCustomError(
                "literal_error", "Input should be {expected}", {"expected": " or ".join(map(repr, values))}
            )
        return value

    return BeforeValidator(check)


def all_of(members: Callable[[], Sequence[Any]]) -> AfterValidator:
    """Admits a value every member type admits (an ``allOf`` that could not
    be merged into one model); the value is kept as given."""
    adapters: list[TypeAdapter[Any]] = []

    def check(value: Any) -> Any:
        if not adapters:
            adapters.extend(TypeAdapter[Any](m) for m in members())
        for adapter in adapters:
            adapter.validate_python(value, strict=True)
        return value

    return AfterValidator(check)


def tag(wire: str, aliases: Mapping[str, str] | None = None) -> Discriminator:
    """The discriminator of a tagged union whose variants do not all fix the
    tag as a literal field: the value of the ``wire`` property of a mapping,
    or of the field with that wire name of a model. ``aliases`` maps the
    other tag values of the discriminator mapping to their variant's tag
    (``{"puppy": "dog"}`` when both select ``Dog``)."""
    others = dict(aliases or {})

    def read(value: Any) -> Any:
        found: object = None
        if isinstance(value, Mapping):
            found = cast("Mapping[str, object]", value).get(wire)
        elif isinstance(value, BaseModel):
            for name, field in type(value).model_fields.items():
                if field.serialization_alias == wire or (field.serialization_alias is None and name == wire):
                    found = getattr(value, name)
                    break
            else:
                found = (value.model_extra or {}).get(wire)
        return others.get(found, found) if isinstance(found, str) else found

    return Discriminator(read)


def rebuild(*modules: ModuleType) -> None:
    """Resolve the forward references of every model of ``modules`` once all
    of them are loaded (models refer to each other across modules)."""
    for module in modules:
        for value in list(vars(module).values()):
            if isinstance(value, type) and issubclass(value, Model) and value.__module__ == module.__name__:
                value.model_rebuild()


def union(*members: Any) -> Any:
    """The union of ``members`` as a runtime value (a validator's type):
    type checkers reject ``|`` between ``Annotated[...]`` forms outside
    annotations."""
    result: Any = members[0]
    for member in members[1:]:
        result = result | member
    return result


def args(values: Mapping[str, object]) -> dict[str, object]:
    """The arguments of a call without the ones left ``UNSET``."""
    return {k: v for k, v in values.items() if v is not UNSET}


def _path(loc: Sequence[str | int], value: object, missing: bool = False) -> list[str | int]:
    """The path of an error location in the validated value: the segments
    that step into it (keys and list indexes), without the union member and
    validator labels pydantic adds. For a missing field (``missing``), the
    last segment is the absent key, so the path names the field as the
    TypeScript SDK does (``response.deliveries``)."""
    out: list[str | int] = []
    current = value
    for i, segment in enumerate(loc):
        if isinstance(current, BaseModel):
            current = current.model_dump(by_alias=True)
        if isinstance(current, Mapping):
            mapping = cast("Mapping[object, object]", current)
            if segment in mapping:
                out.append(segment)
                current = mapping[segment]
            elif missing and i == len(loc) - 1:
                out.append(segment)
            continue
        if isinstance(current, list | tuple) and isinstance(segment, int):
            items = cast("Sequence[object]", current)
            if 0 <= segment < len(items):
                out.append(segment)
                current = items[segment]
    return out


def _issues(error: ValidationError, prefix: list[str | int], value: object) -> list[Issue]:
    """The issues of a validation error. A value that is not ``UNSET`` always
    fails the ``Unset`` member of an optional field's union as well; that
    second error is left out."""
    errors = error.errors(include_url=False)
    kept = [e for e in errors if "literal[UNSET]" not in e["loc"]] or errors
    return [
        {"path": prefix + _path(e["loc"], value, e["type"] == "missing"), "message": e["msg"], "code": e["type"]}
        for e in kept
    ]


@dataclass(frozen=True, slots=True)
class Arg:
    """One argument of an operation: its type, whether it is required, and
    whether its value is dumped JSON-ready (``False`` for bytes, text, form
    and multipart bodies, which the runtime encodes itself)."""

    type: Any
    required: bool
    json: bool = True


class Request:
    """Validates the arguments of an operation (a mapping by argument name)
    in strict mode (no coercion between JSON types, as the TypeScript SDK's
    schemas) and normalizes them: models dumped by wire name, ``UNSET``
    removed."""

    def __init__(self, args: Callable[[], Mapping[str, Arg]]) -> None:
        self._args = args
        self._adapters: dict[str, tuple[Arg, TypeAdapter[Any]]] | None = None

    def _ready(self) -> dict[str, tuple[Arg, TypeAdapter[Any]]]:
        if self._adapters is None:
            self._adapters = {k: (a, TypeAdapter[Any](a.type)) for k, a in self._args().items()}
        return self._adapters

    def validate(self, value: object) -> Valid[dict[str, Any]] | Invalid:
        if not isinstance(value, Mapping):
            return Invalid([{"path": [], "message": "expected a mapping of arguments by name"}])
        given = cast("Mapping[object, object]", value)
        adapters = self._ready()
        issues: list[Issue] = []
        data: dict[str, Any] = {}
        for name, (arg, adapter) in adapters.items():
            raw = given.get(name, UNSET)
            if raw is UNSET:
                if arg.required:
                    issues.append({"path": [name], "message": "Field required", "code": "missing"})
                continue
            try:
                parsed = adapter.validate_python(
                    raw, strict=True, context=JSON_ARGUMENT if arg.json else FILE_ARGUMENT
                )
                data[name] = adapter.dump_python(parsed, mode="json", by_alias=True) if arg.json else _plain(parsed)
            except ValidationError as error:
                issues.extend(_issues(error, [name], raw))
            except PydanticSerializationError as error:
                issues.append({"path": [name], "message": str(error), "code": "serialization"})
        for key, raw in given.items():
            if key not in adapters and raw is not UNSET:
                expected = ", ".join(adapters) or "no arguments"
                issues.append(
                    {
                        "path": [str(key)],
                        "message": f"Unexpected argument; expected one of: {expected}",
                        "code": "extra_forbidden",
                    }
                )
        return Invalid(issues) if issues else Valid(data)


class Response:
    """Validates a decoded success body into its typed value (models)."""

    def __init__(self, type_: Callable[[], Any]) -> None:
        self._type = type_
        self._adapter: TypeAdapter[Any] | None = None

    def _ready(self) -> TypeAdapter[Any]:
        if self._adapter is None:
            self._adapter = TypeAdapter[Any](self._type())
        return self._adapter

    def validate(self, value: object) -> Valid[Any] | Invalid:
        try:
            return Valid(self._ready().validate_python(value, strict=True))
        except ValidationError as error:
            return Invalid(_issues(error, [], value))


def client_options(
    options: ClientOptions | None,
    operations: Sequence[OperationDescriptor],
    macros: Sequence[MacroDescriptor],
    *,
    base_url: str | None,
    auth: AuthConfig | None,
    timeout_ms: int | None,
    validate_responses: Literal["off", "warn", "strict"] | None,
    headers: Mapping[str, str] | None,
) -> ClientOptions:
    """``options`` with the keyword arguments of a client constructor applied
    and the API's operations and macros registered first."""
    base = options if options is not None else ClientOptions()
    changes: dict[str, Any] = {
        "operations": [*operations, *base.operations],
        "macros": [*macros, *base.macros],
    }
    shortcuts: dict[str, object] = {
        "base_url": base_url,
        "auth": auth,
        "timeout_ms": timeout_ms,
        "validate_responses": validate_responses,
        "headers": headers,
    }
    changes.update({k: v for k, v in shortcuts.items() if v is not None})
    return dataclasses.replace(base, **changes)
"#;

/// Where an operation lives on the client (`client.public.webhooks.list`).
fn client_paths(plan: &Plan<'_>) -> Vec<(usize, String)> {
    fn walk(plan: &Plan<'_>, idx: usize, prefix: &str, out: &mut Vec<(usize, String)>) {
        for m in &plan.resources[idx].members {
            match m.kind {
                MemberKind::Op(o) => out.push((o, format!("{prefix}.{}", m.name))),
                MemberKind::Child(c) => walk(plan, c, &format!("{prefix}.{}", m.name), out),
                MemberKind::Preview(_) | MemberKind::Pages(_) => {}
            }
        }
    }
    let mut out = vec![];
    if plan.multi() {
        for n in &plan.client_namespaces {
            for (name, i) in &n.members {
                walk(plan, *i, &format!("client.{}.{name}", n.member), &mut out);
            }
        }
    } else {
        for (name, i) in &plan.client_resources {
            walk(plan, *i, &format!("client.{name}"), &mut out);
        }
    }
    out
}

/// The method name of `kind` for operation `o` (its preview or pages).
fn derived(plan: &Plan<'_>, o: usize, path: &str, preview: bool) -> String {
    let (prefix, _) = path.rsplit_once('.').unwrap_or(("client", path));
    for r in &plan.resources {
        for m in &r.members {
            match m.kind {
                MemberKind::Preview(i) if preview && i == o => {
                    return format!("{prefix}.{}", m.name);
                }
                MemberKind::Pages(i) if !preview && i == o => {
                    return format!("{prefix}.{}", m.name);
                }
                _ => {}
            }
        }
    }
    path.to_string()
}

/// The `auth` entries of the README's client example: one per scheme a
/// caller configures. A composite profile replaces the schemes it
/// satisfies and takes a mapping of its cookies and configuration keys.
fn auth_example(ir: &tungsten_ir::Ir) -> Vec<String> {
    let mut covered: BTreeSet<&str> = BTreeSet::new();
    let mut composites: Vec<(&str, Vec<&str>)> = vec![];
    for s in &ir.auth {
        if let AuthScheme::Composite {
            name,
            satisfies,
            parts,
        } = s
        {
            covered.extend(satisfies.iter().map(String::as_str));
            let keys = parts
                .iter()
                .filter_map(|p| match p {
                    CompositePart::Cookie { name } => Some(name.as_str()),
                    CompositePart::Header { from_config, .. } => from_config.as_deref(),
                    CompositePart::Bearer { .. } => None,
                })
                .collect();
            composites.push((name, keys));
        }
    }
    let mut entries: BTreeSet<String> = BTreeSet::new();
    for (name, keys) in &composites {
        let fields: Vec<String> = keys
            .iter()
            .map(|k| format!("{}: \"<{k}>\"", string_lit(k)))
            .collect();
        entries.insert(format!("{}: {{{}}}", string_lit(name), fields.join(", ")));
    }
    for s in &ir.auth {
        let name = s.name();
        if !covered.contains(name) && !composites.iter().any(|(c, _)| *c == name) {
            entries.insert(format!("{}: \"<credential>\"", string_lit(name)));
        }
    }
    entries.into_iter().collect()
}

/// Example keyword arguments for a call: required ones with placeholders.
fn example_args(shape: &OpShape<'_>) -> String {
    shape
        .fields
        .iter()
        .filter(|f| !f.optional)
        .map(|f| {
            let value = match f.hint.as_str() {
                "int" => "1".to_string(),
                "float" => "1.0".to_string(),
                "bool" => "True".to_string(),
                "bytes" | "BinaryInput" => "b\"\"".to_string(),
                "str" => string_lit(&format!("<{}>", f.key)),
                t if t.starts_with("Literal[") => t
                    .trim_start_matches("Literal[")
                    .split([',', ']'])
                    .next()
                    .unwrap_or("...")
                    .to_string(),
                _ => "...".to_string(),
            };
            format!("{}={value}", f.key)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn call(path: &str, args: &str, extra: &str) -> String {
    let parts: Vec<&str> = [args, extra]
        .into_iter()
        .filter(|s| !s.is_empty())
        .collect();
    format!("{path}({})", parts.join(", "))
}

/// The package README: install, auth, sync and async calls, idempotency,
/// preview then confirm, pagination, macros and the error envelope.
pub(crate) fn readme(
    plan: &Plan<'_>,
    shapes: &[OpShape<'_>],
    opts: &Options,
    header: &str,
    has_macros: bool,
) -> String {
    let ir = plan.ir;
    let client = &plan.client_class;
    let async_client = &plan.async_client_class;
    let module = &opts.module;
    let paths = client_paths(plan);
    let mut out = String::new();
    out.push_str("<!--\n");
    for l in header.lines() {
        out.push_str(l.trim_start_matches('#').trim_start());
        out.push('\n');
    }
    out.push_str("-->\n\n");
    out.push_str(&format!("# {}\n\n", opts.package));
    out.push_str(&format!(
        "Python SDK for the {} API ({}), generated by tungsten.\n\n",
        tungsten_ir::title_stem(&ir.api.title),
        ir.api.version
    ));
    let models_note = match opts.models {
        Models::Pydantic => "models are Pydantic v2",
        Models::Dataclasses => {
            "models are standard-library dataclasses (no dependency besides `tungsten-runtime` and `httpx`)"
        }
    };
    out.push_str(&format!(
        "Every call returns a `Result` and never raises for API or transport errors. \
         Arguments are validated before any request is sent. Python 3.12 or newer; \
         {models_note}.\n\n"
    ));
    out.push_str("## Install\n\n```sh\n");
    out.push_str(&format!("pip install {}\n```\n\n", opts.package));
    out.push_str("## Create a client\n\n```python\n");
    out.push_str(&format!("from {module} import {client}\n\n"));
    let auth = auth_example(ir);
    let server = ir
        .api
        .servers
        .first()
        .map_or("https://api.example.test", |s| s.url.as_str());
    out.push_str(&format!(
        "client = {client}(\n    base_url={},\n",
        string_lit(server)
    ));
    if !auth.is_empty() {
        out.push_str(&format!("    auth={{{}}},\n", auth.join(", ")));
    }
    out.push_str(")\n```\n\n");
    if !ir.auth.is_empty() {
        out.push_str(
            "`auth` takes one entry per scheme name. A composite profile takes a mapping \
             keyed by cookie name or configuration key. The constructor also takes a \
             `ClientOptions` (exported by this package); its keyword arguments override the \
             fields of the same name.\n\n",
        );
    }

    let find = |pred: &dyn Fn(usize) -> bool| paths.iter().find(|(o, _)| pred(*o));
    if let Some((o, path)) = find(&|o| plan.ops[o].op.agent.safety == Safety::ReadOnly) {
        let args = example_args(&shapes[*o]);
        out.push_str("## Read\n\n```python\n");
        out.push_str(&format!("from {module} import Ok\n\n"));
        out.push_str(&format!("res = {}\n", call(path, &args, "")));
        out.push_str("if isinstance(res, Ok):\n    print(res.value)\nelse:\n    print(res.error[\"category\"], res.error[\"remediation\"])\n```\n\n");
        out.push_str(&format!(
            "The async client has the same methods, awaited:\n\n```python\nimport asyncio\n\nfrom {module} import {async_client}\n\n\nasync def main() -> None:\n    async with {async_client}(base_url={}) as client:\n        res = await {}\n        print(res.ok)\n\n\nasyncio.run(main())\n```\n\n",
            string_lit(server),
            call(path, &args, "")
        ));
        out.push_str(&format!("`unwrap(res)` (`from {module} import unwrap`) returns the value or raises `TungstenError` with the envelope, for code that prefers exceptions.\n\n"));
    }
    let mutating =
        find(&|o| plan.ops[o].op.agent.idempotency.policy == IdempotencyKind::CallerOwned)
            .or_else(|| find(&|o| plan.ops[o].op.agent.safety == Safety::Mutating));
    if let Some((o, path)) = mutating {
        out.push_str("## Change something, safely\n\n");
        out.push_str(
            "Mutations are never retried blindly. When the operation takes an idempotency key, \
             generate it once, persist it with your intent, and reuse it on every retry.\n\n```python\n",
        );
        out.push_str("import uuid\n\nkey = str(uuid.uuid4())\n");
        out.push_str(&format!(
            "res = {}\n```\n\n",
            call(
                path,
                &example_args(&shapes[*o]),
                "opts={\"idempotency_key\": key}"
            )
        ));
    }
    if let Some((o, path)) = find(&|o| {
        let op = plan.ops[o].op;
        has_preview(op) && matches!(op.agent.safety, Safety::Destructive | Safety::Irreversible)
    }) {
        let op = plan.ops[*o].op;
        let preview = derived(plan, *o, path, true);
        let args = example_args(&shapes[*o]);
        out.push_str("## Preview, then confirm\n\n");
        out.push_str(&format!(
            "`{}` is `{}`: it needs a confirmation. Preview it (no request is sent), show the effects, then pass the token.\n\n```python\n",
            op.id.0,
            safety_str(op.agent.safety)
        ));
        out.push_str(&format!("from {module} import Ok\n\n"));
        out.push_str(&format!("preview = {}\n", call(&preview, &args, "")));
        out.push_str("if isinstance(preview, Ok) and preview.value[\"confirmation_token\"]:\n");
        out.push_str("    print(preview.value[\"effects\"])\n");
        out.push_str(&format!(
            "    {}\n```\n\n",
            call(
                path,
                &args,
                "opts={\"confirm\": preview.value[\"confirmation_token\"]}"
            )
        ));
    }
    if let Some((o, path)) = find(&|o| shapes[o].page_item.is_some()) {
        let pages = derived(plan, *o, path, false);
        out.push_str(&format!(
            "## Pagination\n\n```python\nfrom {module} import Ok\n\n"
        ));
        out.push_str(&format!(
            "for page in {}:\n",
            call(&pages, &example_args(&shapes[*o]), "")
        ));
        out.push_str("    if not isinstance(page, Ok):\n        break\n    for item in page.value.items:\n        print(item)\n```\n\n");
    }
    if has_macros {
        out.push_str(
            "## Macros\n\nMulti-step workflows from the agent manifest are methods of `client.macros`, \
             run by the runtime from the descriptors in `macros.py`. A macro that is `destructive` or \
             `irreversible`, or has such a step, is confirmed once for the whole run: call its \
             `preview_<macro>(...)` (nothing is sent) and pass the `confirmation_token` as \
             `opts={\"confirm\": token}`. The first failing step's envelope is returned and names the \
             steps already completed.\n\n",
        );
    }
    let models_text = match opts.models {
        Models::Pydantic => {
            "## Models and optional fields\n\nRequest and response bodies are Pydantic models \
         (`from {module}.models import ...`). A field that may be left out defaults to `UNSET` \
         (exported by this package), which is not sent; `None` sends JSON `null`. \
         `model_dump(mode=\"json\", by_alias=True)` gives the wire form. Fields whose wire name is \
         not a Python name are renamed: a keyword or a name the model needs gets `_` appended \
         (`type_`, `json_`) and a leading digit gets `field_` in front (`field_2fa`); the wire \
         name is used on the wire.\n\n"
        }
        Models::Dataclasses => {
            "## Models and optional fields\n\nResponse bodies are dataclasses \
         (`from {module}.models import ...`) and a request argument that is a record takes either \
         the dataclass or a plain mapping typed by its nested `TypedDict`, `Model.Input` (keys are \
         the attribute names; the wire names work at run time too). Building a dataclass does not \
         validate it; every call does, before anything is sent, and `Model.model_validate(data)` \
         does for data you hold (it raises `tungsten_runtime.schema.ValidationError`). A field that \
         may be left out defaults to `UNSET` (exported by this package), which is not sent; `None` \
         sends JSON `null`. `model.model_dump(mode=\"json\", by_alias=True)` gives the wire form. \
         Fields whose wire name is not a Python name are renamed: a keyword or a name the model \
         needs gets `_` appended (`type_`, `json_`) and a leading digit gets `field_` in front \
         (`field_2fa`); the wire name is used on the wire. A record that admits additional \
         properties keeps them in `model_extra`.\n\n"
        }
    };
    out.push_str(&models_text.replace("{module}", module));
    out.push_str("## Errors\n\nA failed call returns `Err(error)`, where `error` is the diagnostic envelope:\n\n```json\n");
    out.push_str(
        "{\n  \"status\": \"error\",\n  \"category\": \"VALIDATION_FAILED\",\n  \"operation\": \"<operation id>\",\n  \"http_status\": null,\n  \"code\": null,\n  \"failed_parameter\": \"<args path>\",\n  \"received_value\": null,\n  \"expected\": \"<what was expected>\",\n  \"remediation\": \"<what to do next>\",\n  \"retryable\": \"never\",\n  \"retry_after_ms\": null,\n  \"next_action\": null,\n  \"request_id\": null,\n  \"trace\": { \"attempts\": 0 }\n}\n```\n\n",
    );
    out.push_str(
        "Branch on `category` and `retryable`: `same_key_only` means retry only with the same \
         idempotency key, `after_remediation` means act first (fix the input, or check \
         whether an unknown outcome took effect: without a key a repeat can apply it \
         twice), and `OUTCOME_UNKNOWN` means the request may have been applied. A success \
         response without a body has `value=None`.\n\n",
    );
    out.push_str(&format!(
        "## Extending\n\n`{module}/custom/__init__.py` is yours: it is created once, never overwritten, and imported as `{module}.custom`.\n"
    ));
    out
}
