// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path"
	"sort"
	"strings"
)

// emittedFile is one file of the response.
type emittedFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// nsPlan is a namespace accessor of a multi-namespace client.
type nsPlan struct {
	ns       *Namespace
	goName   string
	accessor string
	roots    []*resPlan
}

func newGen(ir *IR, opts options) *gen {
	g := &gen{
		ir: ir, opts: opts, multi: len(ir.Namespaces) > 1,
		names:  newScope(packageReserved...),
		byID:   map[string]*goType{},
		inline: map[*Shape]*goType{},
		byOp:   map[string]*opPlan{},
		consts: map[*goType][]string{},
	}
	return g
}

// clientMembers are the methods every Client has.
var clientMembers = append([]string{"Core", "OAuth"}, dispatchMethods...)

func (g *gen) header() string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tungsten-emit-go %s (tungsten %s). DO NOT EDIT.\n", emitterVersion, g.ir.Generator.TungstenVersion)
	keys := make([]string, 0, len(g.ir.Generator.Inputs))
	for k := range g.ir.Generator.Inputs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var inputs []string
	for _, k := range keys {
		digest := g.ir.Generator.Inputs[k]
		if _, hex, ok := strings.Cut(digest, ":"); ok {
			digest = hex
		}
		if len(digest) > 12 {
			digest = digest[:12]
		}
		inputs = append(inputs, k+" "+digest)
	}
	if len(inputs) > 0 {
		fmt.Fprintf(&b, "// Inputs: %s\n", strings.Join(inputs, ", "))
	}
	b.WriteString("\n")
	return b.String()
}

func (g *gen) file(w *writer, imports ...string) *writer {
	imports = usedImports(w.b.String(), imports)
	out := &writer{}
	out.raw(g.header())
	out.line("package %s", g.opts.pkg)
	out.line("")
	if len(imports) > 0 {
		out.line("import (")
		for _, imp := range imports {
			if imp == runtimeImport {
				out.line("tungsten %s", goString(imp))
			} else {
				out.line("%s", goString(imp))
			}
		}
		out.line(")")
		out.line("")
	}
	out.raw(w.b.String())
	return out
}

const runtimeImport = "github.com/pboachie/tungsten/runtimes/go"

// importName is the name an import is referred to by in generated code.
func importName(imp string) string {
	if imp == runtimeImport {
		return "tungsten"
	}
	return path.Base(imp)
}

// usedImports keeps the imports the body refers to (a file whose types
// need no runtime schema, or no JSON method, must not import them). A body
// that does not parse keeps every import; formatting reports it.
func usedImports(body string, imports []string) []string {
	parsed, err := parser.ParseFile(token.NewFileSet(), "", "package p\n"+body, parser.SkipObjectResolution)
	if err != nil {
		return imports
	}
	used := map[string]bool{}
	ast.Inspect(parsed, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				used[id.Name] = true
			}
		}
		return true
	})
	var out []string
	for _, imp := range imports {
		if used[importName(imp)] {
			out = append(out, imp)
		}
	}
	return out
}

// run plans and writes the whole package.
func (g *gen) run() ([]emittedFile, error) {
	g.planTypes()
	g.planResources()
	g.planOps()
	var namespaces []*nsPlan
	var clientAccessors []string
	if g.multi {
		words := make([][]string, len(g.ir.Namespaces))
		for i := range g.ir.Namespaces {
			words[i] = g.ir.Namespaces[i].Name.Words
		}
		accessors := goNames(words, clientMembers...)
		for i := range g.ir.Namespaces {
			ns := &g.ir.Namespaces[i]
			p := &nsPlan{ns: ns, accessor: accessors[i], goName: g.names.alloc(goName(append(append([]string(nil), ns.Name.Words...), "namespace")))}
			for _, r := range g.roots {
				if r.ns == ns {
					p.roots = append(p.roots, r)
				}
			}
			namespaces = append(namespaces, p)
		}
		clientAccessors = accessors
	} else {
		for _, r := range g.roots {
			clientAccessors = append(clientAccessors, r.accessor)
		}
	}
	g.planMacros(clientAccessors)
	// Discover every inline type before anything is written, so names are
	// final.
	for i := 0; i < len(g.types); i++ {
		t := g.types[i]
		g.typeDiscovery(t)
	}
	descriptors := g.descriptorsFile()
	schemas := g.schemasFile()
	models := g.modelsFile()

	var files []emittedFile
	add := func(path string, w *writer) error {
		text, err := w.source(path)
		if err != nil {
			return err
		}
		files = append(files, emittedFile{Path: path, Content: text})
		return nil
	}
	if err := add("descriptors.go", descriptors); err != nil {
		return nil, err
	}
	if err := add("schemas.go", schemas); err != nil {
		return nil, err
	}
	if err := add("models.go", models); err != nil {
		return nil, err
	}
	if err := add("resources.go", g.resourcesFile(namespaces)); err != nil {
		return nil, err
	}
	if err := add("client.go", g.clientFile(namespaces)); err != nil {
		return nil, err
	}
	if err := add("dispatch.go", g.dispatchFile(namespaces)); err != nil {
		return nil, err
	}
	if len(g.macros) > 0 {
		if err := add("macros.go", g.macrosFile()); err != nil {
			return nil, err
		}
	}
	if err := add("doc.go", g.docFile()); err != nil {
		return nil, err
	}
	files = append(files, emittedFile{Path: "go.mod", Content: g.goMod()})
	files = append(files, emittedFile{Path: "README.md", Content: g.readme(namespaces)})
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

// typeDiscovery renders a type's Go declaration and schema once, which
// names the inline types inside it.
func (g *gen) typeDiscovery(t *goType) {
	g.writeType(&writer{}, t)
	g.shapeSchema(t.shape, splitWords(t.name))
}

func (g *gen) descriptorsFile() *writer {
	w := &writer{}
	w.comment(fmt.Sprintf("API describes the %s API to the runtime.", orDefault(g.ir.API.Title, g.ir.API.Name.Wire)))
	w.line("var API = %s", g.apiLit())
	w.line("")
	for _, p := range g.ops {
		w.comment(fmt.Sprintf("%s describes %s (%s %s).", p.descVar, p.op.ID, p.op.Method, p.op.Path.Raw))
		w.line("var %s = %s", p.descVar, g.descriptorLit(p))
		w.line("")
		if p.streamVar != "" {
			parts := []string{}
			if p.eventSchema != "" {
				parts = append(parts, "Event: "+p.eventSchema)
			}
			if d := p.op.Stream.Done; d != nil {
				parts = append(parts, "Done: tungsten.Ptr("+goString(*d)+")")
			}
			if f := p.op.Stream.RequestFlag; f != nil {
				parts = append(parts, "Flag: "+goString(*f))
			}
			w.comment(fmt.Sprintf("%s describes the event stream of %s.", p.streamVar, p.op.ID))
			w.line("var %s = &tungsten.StreamDescriptor{%s}", p.streamVar, strings.Join(parts, ", "))
			w.line("")
		}
	}
	w.line("// operations lists every callable operation, in IR order.")
	w.line("var operations = []*tungsten.OperationDescriptor{")
	for _, p := range g.ops {
		w.line("%s,", p.descVar)
	}
	w.line("}")
	return g.file(w, runtimeImport)
}

func (g *gen) schemasFile() *writer {
	w := &writer{}
	w.line("// The validators of every type: the runtime checks arguments, bodies, page")
	w.line("// items and events against them. They are filled in init, so recursive types")
	w.line("// refer to each other.")
	w.line("var (")
	for _, t := range g.types {
		w.line("%s = new(tungsten.Schema)", t.schema)
	}
	w.line(")")
	w.line("")
	w.line("func init() {")
	for i := 0; i < len(g.types); i++ {
		t := g.types[i]
		w.line("*%s = %s", t.schema, strings.TrimPrefix(g.shapeSchema(t.shape, splitWords(t.name)), "&"))
	}
	w.line("}")
	return g.file(w, runtimeImport)
}

func (g *gen) modelsFile() *writer {
	w := &writer{}
	for i := 0; i < len(g.types); i++ {
		g.writeType(w, g.types[i])
		w.line("")
	}
	body := w.b.String()
	imports := []string{}
	if strings.Contains(body, "json.") {
		imports = append(imports, "encoding/json")
	}
	if strings.Contains(body, "tungsten.") {
		imports = append(imports, runtimeImport)
	}
	return g.file(w, imports...)
}

// chain is the accessor expression of a resource from the client.
func (g *gen) chains(namespaces []*nsPlan) map[*resPlan]string {
	out := map[*resPlan]string{}
	var walk func(r *resPlan, prefix string)
	walk = func(r *resPlan, prefix string) {
		expr := prefix + "." + r.accessor + "()"
		out[r] = expr
		for _, c := range r.children {
			walk(c, expr)
		}
	}
	if g.multi {
		for _, ns := range namespaces {
			for _, r := range ns.roots {
				walk(r, "c."+ns.accessor+"()")
			}
		}
	} else {
		for _, r := range g.roots {
			walk(r, "c")
		}
	}
	return out
}

func hasPreview(op *Operation) bool {
	return op.Agent.Safety != "read_only" && op.Agent.Preview.Mode != "none"
}

func (g *gen) resourcesFile(namespaces []*nsPlan) *writer {
	w := &writer{}
	for _, ns := range namespaces {
		w.comment(fmt.Sprintf("%s holds the resources of the %s namespace (%s).", ns.goName, ns.ns.Name.Wire, orDefault(ns.ns.Title, ns.ns.Name.Wire)))
		w.line("type %s struct {", ns.goName)
		w.line("core *tungsten.ClientCore")
		w.line("}")
		w.line("")
		for _, r := range ns.roots {
			w.comment(fmt.Sprintf("%s returns the %s resource.", r.accessor, r.res.Name.Wire))
			w.line("func (n *%s) %s() *%s {", ns.goName, r.accessor, r.goName)
			w.line("return &%s{core: n.core}", r.goName)
			w.line("}")
			w.line("")
		}
	}
	var walk func(r *resPlan)
	walk = func(r *resPlan) {
		g.writeResource(w, r)
		for _, c := range r.children {
			walk(c)
		}
	}
	for _, r := range g.roots {
		walk(r)
	}
	body := w.b.String()
	var imports []string
	if strings.Contains(body, "bytes.") {
		imports = append(imports, "bytes")
	}
	imports = append(imports, "context")
	if strings.Contains(body, "json.") {
		imports = append(imports, "encoding/json")
	}
	imports = append(imports, runtimeImport)
	return g.file(w, imports...)
}

func (g *gen) writeResource(w *writer, r *resPlan) {
	doc := ""
	if r.res.Doc != nil {
		doc = docSummary(r.res.Doc)
	}
	w.comment(strings.TrimSpace(fmt.Sprintf("%s holds the operations of the %s resource (%s). %s", r.goName, r.res.Name.Wire, r.res.PathPrefix, doc)))
	w.line("type %s struct {", r.goName)
	w.line("core *tungsten.ClientCore")
	w.line("}")
	w.line("")
	for _, c := range r.children {
		w.comment(fmt.Sprintf("%s returns the %s resource.", c.accessor, c.res.Name.Wire))
		w.line("func (r *%s) %s() *%s {", r.goName, c.accessor, c.goName)
		w.line("return &%s{core: r.core}", c.goName)
		w.line("}")
		w.line("")
	}
	for _, p := range r.ops {
		g.writeRequest(w, p)
		g.writeMethods(w, r, p)
	}
}

func paramDoc(p *Param, key, location string) []string {
	var notes []string
	notes = append(notes, fmt.Sprintf("Sent as the %s %s parameter (argument %s).", p.WireName, location, key))
	if p.Deprecated {
		notes = append(notes, "Deprecated: the API marks this parameter deprecated.")
	}
	return notes
}

func (g *gen) writeRequest(w *writer, p *opPlan) {
	w.comment(fmt.Sprintf("%s is the arguments object of %s (%s %s).", p.request, p.op.ID, p.op.Method, p.op.Path.Raw))
	w.line("type %s struct {", p.request)
	for _, a := range p.params {
		docComment(w, a.goName, a.param.Doc, paramDoc(a.param, a.key, a.location)...)
		tag := a.key
		if !a.param.Required {
			tag += ",omitempty"
		}
		w.line("%s %s `json:%s`", a.goName, a.goType, goString(tag))
	}
	if b := p.body; b != nil {
		if b.merged != nil {
			for _, f := range b.fieldGo {
				var notes []string
				if f.field.Sensitive {
					notes = append(notes, "Sensitive: never log it.")
				}
				docComment(w, f.goName, f.field.Doc, notes...)
				w.line("%s %s `json:%s`", f.goName, f.goType, goString(f.tag))
			}
		} else {
			tag := b.arg
			if !b.required {
				tag += ",omitempty"
			}
			w.comment(fmt.Sprintf("%s is the request body, sent as %s.", b.goName, b.content.MediaType))
			w.line("%s %s `json:%s`", b.goName, b.goType, goString(tag))
		}
	}
	w.line("}")
	w.line("")
	var patches []fieldPlan
	if p.body != nil {
		for _, f := range p.body.fieldGo {
			if f.patch {
				patches = append(patches, f)
			}
		}
	}
	if len(patches) > 0 {
		w.comment("UnmarshalJSON tells an explicit null from an absent member.")
		w.line("func (m *%s) UnmarshalJSON(data []byte) error {", p.request)
		w.line("type plain %s", p.request)
		w.line("var v plain")
		w.line("dec := json.NewDecoder(bytes.NewReader(data))")
		w.line("dec.DisallowUnknownFields()")
		w.line("if err := dec.Decode(&v); err != nil {")
		w.line("return err")
		w.line("}")
		w.line("nulls := tungsten.NullMembers(data)")
		for _, f := range patches {
			inner := strings.TrimSuffix(strings.TrimPrefix(f.goType, "*tungsten.Patch["), "]")
			w.line("if nulls[%s] {", goString(f.field.WireName))
			w.line("v.%s = tungsten.Null[%s]()", f.goName, inner)
			w.line("}")
		}
		w.line("*m = %s(v)", p.request)
		w.line("return nil")
		w.line("}")
		w.line("")
	}
}

func (g *gen) methodDoc(p *opPlan) string {
	op := p.op
	parts := []string{fmt.Sprintf("%s calls %s (%s %s).", p.method, op.ID, op.Method, op.Path.Raw)}
	if s := opSummary(op); s != "" {
		parts = append(parts, s)
	}
	switch op.Agent.Safety {
	case "destructive":
		parts = append(parts, "Destructive: pass the confirmation token of Preview"+p.method+" (or tungsten.ConfirmYes) as opts.Confirm.")
	case "irreversible":
		parts = append(parts, "Irreversible: pass the confirmation token of Preview"+p.method+" as opts.Confirm.")
	}
	if op.Agent.Idempotency.Policy == "caller_owned" && op.Agent.Idempotency.PersistRequired {
		parts = append(parts, "Pass opts.IdempotencyKey and reuse it on every retry of the same intent.")
	}
	if op.Agent.ShownOnce {
		parts = append(parts, "The result holds values the API returns only once; store them before anything else.")
	}
	if op.Deprecated {
		parts = append(parts, "Deprecated: the API marks this operation deprecated.")
	}
	return strings.Join(parts, "\n\n")
}

func (g *gen) writeMethods(w *writer, r *resPlan, p *opPlan) {
	w.comment(g.methodDoc(p))
	w.line("func (r *%s) %s(ctx context.Context, request %s, opts tungsten.CallOptions) (*tungsten.Response[%s], error) {", r.goName, p.method, p.request, p.success)
	w.line("return tungsten.CallTyped[%s](ctx, r.core, %s, request, opts)", p.success, p.descVar)
	w.line("}")
	w.line("")
	if hasPreview(p.op) {
		w.comment(fmt.Sprintf("Preview%s renders the request of %s without sending it and issues a confirmation token bound to these exact arguments.", p.method, p.op.ID))
		w.line("func (r *%s) Preview%s(ctx context.Context, request %s, opts tungsten.CallOptions) (*tungsten.Response[*tungsten.PreviewResult], error) {", r.goName, p.method, p.request)
		w.line("return tungsten.PreviewTyped(ctx, r.core, %s, request, opts)", p.descVar)
		w.line("}")
		w.line("")
	}
	if p.op.Pagination != nil {
		w.comment(fmt.Sprintf("%sPages iterates the pages of %s.", p.method, p.op.ID))
		w.line("func (r *%s) %sPages(request %s, opts tungsten.CallOptions) *tungsten.TypedPages[%s] {", r.goName, p.method, p.request, p.itemType)
		w.line("return tungsten.PagesTyped[%s](r.core, %s, request, opts)", p.itemType, p.descVar)
		w.line("}")
		w.line("")
	}
	if p.streamVar != "" {
		w.comment(fmt.Sprintf("%sStream iterates the server-sent events of %s; Close the stream when leaving early.", p.method, p.op.ID))
		w.line("func (r *%s) %sStream(request %s, opts tungsten.CallOptions) *tungsten.TypedEvents[%s] {", r.goName, p.method, p.request, p.eventType)
		w.line("return tungsten.StreamTyped[%s](r.core, %s, %s, request, opts)", p.eventType, p.descVar, p.streamVar)
		w.line("}")
		w.line("")
	}
}

func (g *gen) hasAuthorizationCode() bool {
	for _, s := range g.ir.Auth {
		if s.Kind != "o_auth2" {
			continue
		}
		for _, f := range s.Flows {
			if f.Kind == "authorizationCode" && f.AuthorizationURL != "" && f.TokenURL != "" {
				return true
			}
		}
	}
	return false
}

func (g *gen) clientFile(namespaces []*nsPlan) *writer {
	w := &writer{}
	title := orDefault(g.ir.API.Title, g.ir.API.Name.Wire)
	w.comment(fmt.Sprintf("Client is the %s API client. It is safe for concurrent use; one client shares one connection pool, one confirmation key and one idempotency store.", title))
	w.line("type Client struct {")
	w.line("core *tungsten.ClientCore")
	w.line("}")
	w.line("")
	w.comment("New builds a client. Without options.BaseURL it calls the API's first server.")
	w.line("func New(options tungsten.ClientOptions) (*Client, error) {")
	w.line("options.Operations = append(append([]*tungsten.OperationDescriptor(nil), options.Operations...), operations...)")
	w.line("core, err := tungsten.NewClientCore(API, options)")
	w.line("if err != nil {")
	w.line("return nil, err")
	w.line("}")
	w.line("return &Client{core: core}, nil")
	w.line("}")
	w.line("")
	w.line("// Core returns the runtime client the SDK runs on.")
	w.line("func (c *Client) Core() *tungsten.ClientCore {")
	w.line("return c.core")
	w.line("}")
	w.line("")
	w.line("// Operations lists every callable operation, in IR order.")
	w.line("func (c *Client) Operations() []*tungsten.OperationDescriptor {")
	w.line("return append([]*tungsten.OperationDescriptor(nil), operations...)")
	w.line("}")
	w.line("")
	w.line("// Macros lists every macro, in IR order.")
	w.line("func (c *Client) Macros() []*tungsten.MacroDescriptor {")
	w.line("return append([]*tungsten.MacroDescriptor(nil), macros...)")
	w.line("}")
	w.line("")
	if g.hasAuthorizationCode() {
		w.comment("OAuth returns the OAuth2 authorization-code helpers of a scheme: PKCE, the authorization URL, the code exchange and refresh.")
		w.line("func (c *Client) OAuth(scheme string) *tungsten.OAuthFlow {")
		w.line("return c.core.OAuth(scheme)")
		w.line("}")
		w.line("")
	}
	if g.multi {
		for _, ns := range namespaces {
			w.comment(fmt.Sprintf("%s returns the resources of the %s namespace.", ns.accessor, ns.ns.Name.Wire))
			w.line("func (c *Client) %s() *%s {", ns.accessor, ns.goName)
			w.line("return &%s{core: c.core}", ns.goName)
			w.line("}")
			w.line("")
		}
	} else {
		for _, r := range g.roots {
			w.comment(fmt.Sprintf("%s returns the %s resource.", r.accessor, r.res.Name.Wire))
			w.line("func (c *Client) %s() *%s {", r.accessor, r.goName)
			w.line("return &%s{core: c.core}", r.goName)
			w.line("}")
			w.line("")
		}
	}
	if len(g.macros) == 0 {
		w.line("var macros []*tungsten.MacroDescriptor")
	}
	return g.file(w, runtimeImport)
}

func (g *gen) dispatchFile(namespaces []*nsPlan) *writer {
	chains := g.chains(namespaces)
	w := &writer{}
	w.line("var _ tungsten.Dispatch = (*Client)(nil)")
	w.line("")
	w.comment("Invoke runs an operation by id with an arguments object (keyed by argument name) through its typed method; arguments that do not decode go to the runtime as they are, so pre-flight validation reports them. The result's Value is the decoded wire body.")
	w.line("func (c *Client) Invoke(ctx context.Context, operation string, args any, opts tungsten.CallOptions) (*tungsten.Outcome, error) {")
	w.line("switch operation {")
	for _, p := range g.ops {
		chain := chains[p.res]
		w.line("case %s:", goString(p.op.ID))
		w.line("var request %s", p.request)
		w.line("if !tungsten.DecodeArgs(args, &request) {")
		w.line("return c.core.Call(ctx, %s, args, opts)", p.descVar)
		w.line("}")
		w.line("return tungsten.Untyped(%s.%s(ctx, request, opts))", chain, p.method)
	}
	w.line("}")
	w.line("return nil, tungsten.UnknownOperation(operation)")
	w.line("}")
	w.line("")
	w.comment("PreviewOperation previews an operation by id.")
	w.line("func (c *Client) PreviewOperation(ctx context.Context, operation string, args any, opts tungsten.CallOptions) (*tungsten.Response[*tungsten.PreviewResult], error) {")
	w.line("switch operation {")
	for _, p := range g.ops {
		if !hasPreview(p.op) {
			continue
		}
		w.line("case %s:", goString(p.op.ID))
		w.line("var request %s", p.request)
		w.line("if !tungsten.DecodeArgs(args, &request) {")
		w.line("return c.core.Preview(ctx, %s, args, opts)", p.descVar)
		w.line("}")
		w.line("return %s.Preview%s(ctx, request, opts)", chains[p.res], p.method)
	}
	w.line("}")
	w.line("if op := tungsten.Find(operations, operation); op != nil {")
	w.line("return c.core.Preview(ctx, op, args, opts)")
	w.line("}")
	w.line("return nil, tungsten.UnknownOperation(operation)")
	w.line("}")
	w.line("")
	w.comment("Paginate collects every page of a paginated operation by id; each page's items are the decoded JSON items. A failure ends the list with its error.")
	w.line("func (c *Client) Paginate(ctx context.Context, operation string, args any, opts tungsten.CallOptions) ([]*tungsten.Response[tungsten.Page[any]], error) {")
	w.line("switch operation {")
	for _, p := range g.ops {
		if p.op.Pagination == nil {
			continue
		}
		w.line("case %s:", goString(p.op.ID))
		w.line("var request %s", p.request)
		w.line("if !tungsten.DecodeArgs(args, &request) {")
		w.line("return c.core.Pages(%s, args, opts).All(ctx)", p.descVar)
		w.line("}")
		w.line("return %s.%sPages(request, opts).AllRaw(ctx)", chains[p.res], p.method)
	}
	w.line("}")
	w.line("return nil, tungsten.NotPaginated(operation)")
	w.line("}")
	w.line("")
	w.comment("StreamEvents collects the events of an operation's event stream by id, each as its decoded JSON value; a failure ends the list with its error.")
	w.line("func (c *Client) StreamEvents(ctx context.Context, operation string, args any, opts tungsten.CallOptions) ([]tungsten.StreamEvent, error) {")
	w.line("switch operation {")
	for _, p := range g.ops {
		if p.streamVar == "" {
			continue
		}
		w.line("case %s:", goString(p.op.ID))
		w.line("var request %s", p.request)
		w.line("if !tungsten.DecodeArgs(args, &request) {")
		w.line("return c.core.Stream(%s, %s, args, opts).CollectValues(ctx)", p.descVar, p.streamVar)
		w.line("}")
		w.line("return %s.%sStream(request, opts).CollectValues(ctx)", chains[p.res], p.method)
	}
	w.line("}")
	w.line("return nil, tungsten.NoStream(operation)")
	w.line("}")
	w.line("")
	w.comment("RunMacro runs a macro by name.")
	w.line("func (c *Client) RunMacro(ctx context.Context, name string, input any, opts tungsten.CallOptions) (*tungsten.Outcome, error) {")
	w.line("if m := tungsten.FindMacro(macros, name); m != nil {")
	w.line("return c.core.RunMacro(ctx, m, input, opts)")
	w.line("}")
	w.line("return nil, tungsten.UnknownMacro(name)")
	w.line("}")
	w.line("")
	w.comment("PreviewMacro previews a macro by name without sending anything.")
	w.line("func (c *Client) PreviewMacro(ctx context.Context, name string, input any, opts tungsten.CallOptions) (*tungsten.Response[*tungsten.PreviewResult], error) {")
	w.line("if m := tungsten.FindMacro(macros, name); m != nil {")
	w.line("return c.core.PreviewMacro(ctx, m, input, opts)")
	w.line("}")
	w.line("return nil, tungsten.UnknownMacro(name)")
	w.line("}")
	return g.file(w, "context", runtimeImport)
}

func (g *gen) macrosFile() *writer {
	w := &writer{}
	for _, p := range g.macros {
		w.comment(fmt.Sprintf("%s is the macro %s as data for the runtime: %s", p.varName, p.m.Name, p.m.Summary))
		w.line("var %s = %s", p.varName, macroDescriptorLit(p))
		w.line("")
	}
	w.line("// macros lists every macro, in IR order.")
	w.line("var macros = []*tungsten.MacroDescriptor{")
	for _, p := range g.macros {
		w.line("%s,", p.varName)
	}
	w.line("}")
	w.line("")
	for _, p := range g.macros {
		parts := []string{fmt.Sprintf("%s runs the macro %s: %s", p.method, p.m.Name, p.m.Summary)}
		if p.extends != "" {
			parts = append(parts, fmt.Sprintf("Its input is the arguments object of %s (plus the macro's own fields).", p.extends))
		}
		switch p.m.Safety {
		case "destructive", "irreversible":
			parts = append(parts, "It is "+p.m.Safety+": pass the confirmation token of Preview"+p.method+" as opts.Confirm.")
		}
		if p.m.ShownOnce {
			parts = append(parts, "The result holds values the API returns only once; store them before anything else.")
		}
		w.comment(strings.Join(parts, "\n\n"))
		w.line("func (c *Client) %s(ctx context.Context, input any, opts tungsten.CallOptions) (*tungsten.Outcome, error) {", p.method)
		w.line("return c.core.RunMacro(ctx, %s, input, opts)", p.varName)
		w.line("}")
		w.line("")
		if p.m.Safety != "read_only" {
			w.comment(fmt.Sprintf("Preview%s previews the macro %s without sending anything and issues its confirmation token.", p.method, p.m.Name))
			w.line("func (c *Client) Preview%s(ctx context.Context, input any, opts tungsten.CallOptions) (*tungsten.Response[*tungsten.PreviewResult], error) {", p.method)
			w.line("return c.core.PreviewMacro(ctx, %s, input, opts)", p.varName)
			w.line("}")
			w.line("")
		}
	}
	return g.file(w, "context", runtimeImport)
}

func (g *gen) docFile() *writer {
	out := &writer{}
	out.raw(g.header())
	title := orDefault(g.ir.API.Title, g.ir.API.Name.Wire)
	text := fmt.Sprintf("Package %s is the Go SDK of the %s API, generated by tungsten.", g.opts.pkg, title)
	if d := strings.TrimSpace(g.ir.API.Description); d != "" {
		text += "\n\n" + d
	}
	text += "\n\nEvery operation is a method of a resource reached from Client; it takes a context, a request struct (the operation's arguments) and tungsten.CallOptions, and returns a typed *tungsten.Response or a *tungsten.Error carrying the diagnostic envelope. The runtime (github.com/pboachie/tungsten/runtimes/go) validates arguments, applies auth, idempotency keys and confirmation rules, retries by safety tier and classifies every failure."
	out.comment(text)
	out.line("package %s", g.opts.pkg)
	return out
}

func (g *gen) goMod() string {
	var b strings.Builder
	fmt.Fprintf(&b, "module %s\n\ngo 1.22\n\nrequire %s %s\n", g.opts.module, runtimeImport, g.opts.runtimeVersion)
	if g.opts.runtimePath != "" {
		fmt.Fprintf(&b, "\nreplace %s => %s\n", runtimeImport, g.opts.runtimePath)
	}
	return b.String()
}
