// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"strings"
)

// readme is the generated package's README.md.
func (g *gen) readme(namespaces []*nsPlan) string {
	title := orDefault(g.ir.API.Title, g.ir.API.Name.Wire)
	var b strings.Builder
	line := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
		b.WriteByte('\n')
	}
	line("# %s Go SDK", title)
	line("")
	line("Generated by tungsten (tungsten-emit-go %s) from the API description. Do not edit", emitterVersion)
	line("the generated files; regenerate them with `tungsten generate`.")
	line("")
	if d := strings.TrimSpace(g.ir.API.Description); d != "" {
		line("%s", d)
		line("")
	}
	line("## Install")
	line("")
	line("```sh")
	line("go get %s", g.opts.module)
	line("```")
	line("")
	line("The SDK runs on `%s` %s (Go 1.22 or later, standard library only).", runtimeImport, g.opts.runtimeVersion)
	line("")
	line("## Use")
	line("")
	example := ""
	for _, p := range g.ops {
		if p.op.Agent.Safety == "read_only" {
			chain := g.chains(namespaces)[p.res]
			example = fmt.Sprintf("result, err := client%s.%s(ctx, %s.%s{}, tungsten.CallOptions{})", strings.TrimPrefix(chain, "c"), p.method, g.opts.pkg, p.request)
			break
		}
	}
	line("```go")
	line("client, err := %s.New(tungsten.ClientOptions{", g.opts.pkg)
	line("\tAuth: tungsten.AuthConfig{ /* credentials by scheme name */ },")
	line("})")
	line("if err != nil {")
	line("\treturn err")
	line("}")
	if example != "" {
		line("%s", example)
		line("var failure *tungsten.Error")
		line("if errors.As(err, &failure) {")
		line("\t// failure.Diagnostic is the error envelope: category, retryable,")
		line("\t// remediation, next_action. Partial keeps what a failed call produced.")
		line("}")
	}
	line("```")
	line("")
	line("Every method takes a `context.Context`, the operation's request struct and")
	line("`tungsten.CallOptions` (`IdempotencyKey`, `Confirm`, `Timeout`, `Verify`, `Headers`).")
	line("Failures are `*tungsten.Error` values carrying the diagnostic envelope, the same")
	line("in every tungsten runtime. Destructive and irreversible operations need")
	line("confirmation: call the `Preview...` method and pass its token as")
	line("`Confirm: tungsten.ConfirmToken(token)`. Paginated operations have a")
	line("`...Pages` iterator, event streams a `...Stream` iterator.")
	line("")
	line("## Operations")
	line("")
	line("| Operation | Method | Safety |")
	line("|---|---|---|")
	chains := g.chains(namespaces)
	for _, p := range g.ops {
		line("| `%s` | `client%s.%s` | %s |", p.op.ID, strings.TrimPrefix(chains[p.res], "c"), p.method, strings.ReplaceAll(p.op.Agent.Safety, "_", "-"))
	}
	if len(g.macros) > 0 {
		line("")
		line("## Macros")
		line("")
		line("| Macro | Method | Safety |")
		line("|---|---|---|")
		for _, m := range g.macros {
			line("| `%s` | `client.%s` | %s |", m.m.Name, m.method, strings.ReplaceAll(m.m.Safety, "_", "-"))
		}
	}
	return b.String()
}
