// SPDX-License-Identifier: Apache-2.0

// Package tungsten is the runtime of Go SDKs generated by tungsten.
//
// A generated SDK is mostly data (one OperationDescriptor per operation and
// an APIDescriptor) plus thin typed wrappers; everything with behaviour
// lives here, so every operation behaves the same way, and the same way as
// the TypeScript, Python and Rust runtimes.
//
// ClientCore runs each call through one pipeline: pre-flight validation of
// the arguments, auth (bearer with a required prefix, API keys, basic,
// composite profiles, OAuth2 client credentials and authorization code),
// idempotency keys, confirmation rules for destructive operations, sending
// with tier-aware retries, and classification of the answer (or of a lost
// request) into a result or the diagnostic error envelope (*Error carrying
// a *Diagnostic). On top of that it provides previews with confirmation
// tokens, verification hooks, pagination, polling, macros and server-sent
// event streams. Every call takes a context.Context; cancelling it ends the
// call (a mutation in flight is reported as OUTCOME_UNKNOWN).
//
// JSON values are plain Go values: nil, bool, string, int64, float64, []any
// and *Object (an object that keeps member order). ParseJSON and FromGo
// produce them.
//
// A destructive or irreversible operation fails with CONFIRMATION_REQUIRED
// unless the call is confirmed: Preview renders the request and its effects
// and issues a token bound to the exact arguments; the call then passes
// ConfirmToken(token) (or ConfirmYes, for destructive operations only).
package tungsten
