// SPDX-License-Identifier: Apache-2.0
//! `tungsten-cli-kit`: the engine of CLIs generated by tungsten. A generated CLI is a table of commands ([`CliSpec`]) and a
//! `main` that hands it to [`run`]; the kit builds the clap command tree,
//! turns flags into the arguments object, applies the output contract and
//! runs the SDK through [`tungsten_runtime::Dispatch`], so the CLI cannot
//! drift from the SDK: tiers, idempotency rules, previews, confirmation
//! tokens, pagination and macros all come from the SDK's descriptors.
//!
//! Stability: [`CliSpec`] and [`run`] are shared by the CLI emitter and this
//! crate. Changes are additive.
//!
//! # Commands
//!
//! - one command per table entry, at the entry's `path` (`webhooks create`),
//!   with the table's flags (kebab-case; strings, integers, numbers,
//!   booleans, enums, repeatable arrays, JSON text or `@file`, `@file`
//!   bytes) and `--body @file.json|-` when the operation takes its whole
//!   body as one argument;
//! - on operations that are not read-only: `--dry-run`, `--yes`,
//!   `--i-understand`, `--idempotency-key` and `--verify`; on paginated
//!   operations: `--all`;
//! - global flags: `--json`, `--base-url`, `--profile`, `--config`,
//!   `--timeout`, `--no-color`;
//! - `schema <command>` (the compact JSON Schema of the arguments),
//!   `operations` (every command with its tier), `auth status` (which
//!   credentials are present, never their values), `macros <name>` for the
//!   table's macros, and `explain-error <CODE|-|@file>` (an error category,
//!   an API error code from the manifest's remediation tables, or a whole
//!   envelope read from standard input or a file: its category,
//!   retryability, what `--idempotency-key`, `--yes` and `--dry-run` mean
//!   for it, the operation's remediation and the exit code).
//!
//! Secrets are never positional and never flag values. Credentials come
//! from environment variables (`<PREFIX>_<SCHEME>[_<PART>]`, derived from the
//! SDK's auth schemes: `ZROTEXT_BEARER_AUTH`; each part of a composite
//! profile has its own) and from the config file
//! `~/.config/<config_dir>/config.toml` (`XDG_CONFIG_HOME` is respected)
//! whose `[profile.<name>]` tables hold `base_url`, `timeout` and the same
//! credential names in lower case. Precedence: flag, then environment, then
//! profile, then the SDK's default. A flag marked `sensitive` takes `-` (a
//! line of standard input) or `env:NAME` instead of a value.
//!
//! # Output contract
//!
//! - Human output by default. Color only when the stream is a terminal,
//!   `NO_COLOR` is unset (or empty), `TERM` is not `dumb` and `--no-color`
//!   is not given.
//! - `--json` prints exactly one JSON document on standard output and
//!   nothing else: the success body (`null` when there is none), or, for a
//!   failure, the diagnostic envelope (a failure of the command line itself
//!   is an envelope too, category `VALIDATION_FAILED`, code `USAGE`, nothing
//!   sent). `--all` prints one array of every item. A preview (`--dry-run`,
//!   or a command that needs confirmation) is one document with the
//!   rendered request, the effects and the confirmation token; a command
//!   that needs confirmation adds `"confirmation_required": true` and
//!   `"rerun_with"`.
//! - Diagnostics and progress go to standard error: notes about values the
//!   API shows once, verification results, warnings, and the partial result
//!   of a failed call.
//! - The kit never prompts: it behaves the same with or without a terminal.
//!
//! # Safety
//!
//! A `destructive` operation needs `--yes`; an `irreversible` one needs
//! `--yes --i-understand`. Without them the command runs the SDK's preview,
//! prints it with its confirmation token and exits 6, so an agent can decide
//! and re-run. With them it previews first and calls with the token it got
//! (`Confirm::Token`); the token is bound to this process's client. An
//! operation that needs a caller-owned idempotency key fails without
//! `--idempotency-key` with the SDK's pre-flight envelope (exit 2).
//!
//! # Exit codes
//!
//! | Code | Meaning |
//! |---|---|
//! | 0 | success (also `--help`, `--version`, a preview from `--dry-run`) |
//! | 1 | internal error: the table and the SDK disagree, or output failed |
//! | 2 | usage or validation failure: a clap usage error, a flag or file that cannot be read, or a pre-flight `VALIDATION_FAILED` / `MALFORMED_REQUEST` (no HTTP status; nothing was sent) |
//! | 3 | API error that is not retryable (`retryable` is `never`) |
//! | 4 | API error that is retryable (`retryable` is anything but `never`) |
//! | 5 | `OUTCOME_UNKNOWN`: the request may have been applied; check before retrying |
//! | 6 | confirmation required: the preview was printed, nothing was sent |
//! | 7 | credentials missing or malformed: `AUTH_FAILED` before any request (no HTTP status) |

mod builtin;
mod check;
mod config;
mod ctx;
mod exec;
mod exit;
mod explain;
mod host;
mod render;
mod spec;
mod toml;
mod tree;
mod values;

pub use check::{RESERVED_COMMANDS, RESERVED_FLAGS};
pub use host::Host;
pub use spec::{CliFlag, CliMacro, CliOp, CliRemediation, CliSpec, FlagKind};

use std::process::ExitCode;

use tungsten_runtime::{ClientOptions, ConfigError, Dispatch};

/// Run the CLI: parse `argv` (including the program name), build the client
/// with `make_client` from the options the flags, environment and config
/// file give, run the command and print its output. Returns the exit code
/// of the output contract.
///
/// `make_client` is called once to learn which credentials the API takes
/// and once more with them, so it must be cheap and repeatable.
pub async fn run<D, F>(spec: &CliSpec, argv: Vec<String>, make_client: F) -> ExitCode
where
    D: Dispatch,
    F: Fn(ClientOptions) -> Result<D, ConfigError>,
{
    ExitCode::from(run_with(spec, argv, Host::process(), make_client).await)
}

/// [`run`] on another [`Host`]: the environment and streams are the host's.
/// Returns the exit code.
pub async fn run_with<D, F>(spec: &CliSpec, argv: Vec<String>, host: Host, make_client: F) -> u8
where
    D: Dispatch,
    F: Fn(ClientOptions) -> Result<D, ConfigError>,
{
    let json = argv.iter().any(|a| a == "--json");
    let no_color = argv.iter().any(|a| a == "--no-color");
    let mut ctx = ctx::Ctx::new(spec, host, json, no_color);
    let code = exec::drive(&mut ctx, argv, &make_client).await;
    ctx.finish();
    code
}
