// SPDX-License-Identifier: Apache-2.0
//! `tungsten-cli-kit`: the engine of CLIs generated by tungsten (PHASE-5
//! CONTRACT). A generated CLI is a table of commands ([`CliSpec`]) and a
//! `main` that hands it to [`run`]; the kit builds the clap command tree,
//! turns flags into the arguments object, applies the output contract
//! (planning/05 "CLI output contract") and runs the SDK through
//! [`tungsten_runtime::Dispatch`], so the CLI cannot drift from the SDK.

mod spec;

pub use spec::{CliFlag, CliMacro, CliOp, CliSpec, FlagKind};

use std::process::ExitCode;

use tungsten_runtime::{ClientOptions, ConfigError, Dispatch};

/// Run the CLI: parse `argv` (including the program name), build the client
/// with `make_client` from the options the flags, environment and config
/// file give, run the command and print its output. Returns the exit code
/// of the output contract.
pub async fn run<D, F>(spec: &CliSpec, argv: Vec<String>, make_client: F) -> ExitCode
where
    D: Dispatch,
    F: FnOnce(ClientOptions) -> Result<D, ConfigError>,
{
    let _ = (spec, argv, make_client);
    unimplemented!("PHASE-5 stub")
}
