// SPDX-License-Identifier: Apache-2.0
/**
 * `@tungsten/runtime`: the runtime for SDKs generated by tungsten
 * (planning/06). Zero dependencies; runs on Node >= 22, Bun, Deno, Workers
 * and browsers. Node-only adapters live in `@tungsten/runtime/node`.
 */

export * from "./types.js";
export { ClientCore } from "./client.js";
export { SseParser, type SseEvent } from "./sse.js";
export { MemoryIdempotencyStore } from "./idempotency.js";
export {
  generatePkce,
  MemoryTokenStore,
  OAuthFlow,
  pkceChallenge,
  type AuthorizationUrlParams,
  type ExchangeCodeParams,
  type OAuthResult,
  type Pkce,
  type StoredToken,
  type TokenInfo,
  type TokenStore,
} from "./oauth.js";
export { TungstenError, unwrap, throwing, type Throwing } from "./errors.js";
export { defineApi, defineMacro, defineOperation } from "./define.js";
export { evaluatePredicate } from "./expr.js";
export { DEFAULT_RETRYABLE } from "./envelope.js";
export { CONFIRMATION_TTL_MS } from "./confirm.js";
export { RUNTIME_VERSION } from "./version.js";
export { isBinaryInput, type BinaryInput, type NamedBinary } from "./util.js";
