// SPDX-License-Identifier: Apache-2.0
/**
 * `@tungsten/runtime`: the runtime for SDKs generated by tungsten.
 *
 * PHASE-2 STUB: exports the contract types and a `ClientCore` that refuses
 * every call. The runtime work package implements it in `client.ts` and
 * supporting modules.
 */

export * from "./types.js";
export { ClientCore } from "./client.js";
