// SPDX-License-Identifier: AGPL-3.0-only
//! The server package: `package.json`, `tsconfig.json`, `manifest.json`,
//! `src/server.ts`, the hand-editable `src/custom/index.ts`, `README.md`
//! and `.env.example`.
//!
//! `src/server.ts` reads `manifest.json`, builds one `ClientCore` per MCP
//! session from the generated SDK's descriptors with `ClientOptions` taken
//! from the environment (`crate::env`), and serves the manifest through
//! `createTungstenMcpServer(...).connectStdio()`.

use serde_json::{Map, Value, json};
use tungsten_emit::schema::collapse_whitespace;
use tungsten_emit::{CommentStyle, header};
use tungsten_ir::Ir;

use crate::budget::{Budget, INDEX_BUDGET};
use crate::env::{self, Credentials};
use crate::manifest::{COUNTER_NAME, McpManifest, Mode, ToolKind};
use crate::options::{DEFAULT_RANGE, NODE_TYPES_VERSION, Options, TYPESCRIPT_VERSION};

/// JSON with two-space indent and a final newline.
fn json_text(value: &Value) -> String {
    let mut text = serde_json::to_string_pretty(value).unwrap_or_default();
    text.push('\n');
    text
}

/// A TypeScript string literal.
fn ts_string(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_default()
}

pub(crate) fn package_json(ir: &Ir, opts: &Options) -> String {
    let mut deps = Map::new();
    let mut entries = vec![
        ("@tungsten/mcp".to_string(), opts.runtime.clone()),
        ("@tungsten/runtime".to_string(), DEFAULT_RANGE.to_string()),
        (opts.sdk_package.clone(), opts.sdk.clone()),
    ];
    entries.sort();
    entries.dedup_by(|a, b| a.0 == b.0);
    for (name, spec) in entries {
        deps.insert(name, json!(spec));
    }
    let mut bin = Map::new();
    bin.insert(opts.bin.clone(), json!("./dist/server.js"));
    json_text(&json!({
        "name": opts.package,
        "version": opts.version,
        "description": format!("MCP server for the {} API, generated by tungsten.", title(ir)),
        "type": "module",
        "bin": bin,
        "files": ["dist", "manifest.json"],
        "engines": { "node": ">=22" },
        "scripts": {
            "build": "tsc -p tsconfig.json",
            "typecheck": "tsc -p tsconfig.json --noEmit",
            "start": "node dist/server.js",
        },
        "dependencies": deps,
        "devDependencies": {
            "@types/node": NODE_TYPES_VERSION,
            "typescript": TYPESCRIPT_VERSION,
        },
    }))
}

pub(crate) fn tsconfig_json() -> String {
    json_text(&json!({
        "compilerOptions": {
            "target": "ES2022",
            "module": "NodeNext",
            "moduleResolution": "NodeNext",
            "lib": ["ES2022"],
            "types": ["node"],
            "strict": true,
            "exactOptionalPropertyTypes": true,
            "noUncheckedIndexedAccess": true,
            "noImplicitOverride": true,
            "outDir": "dist",
            "rootDir": "src",
            "skipLibCheck": true,
        },
        "include": ["src"],
    }))
}

pub(crate) fn custom_template() -> String {
    "// Hand-written extensions of this MCP server. tungsten creates this file once\n\
     // and never overwrites or deletes it; src/server.ts calls `customize` before\n\
     // the server starts.\n\
     \n\
     import type { ServerOptions } from \"@tungsten/mcp\";\n\
     \n\
     /** Adjust the server options: wrap `createCore` to add middleware, enable\n \
     * the sandbox, change the name. Return them unchanged to keep the defaults. */\n\
     export function customize(options: ServerOptions): ServerOptions {\n\
     \x20 return options;\n\
     }\n"
    .to_string()
}

/// The display title of the API.
fn title(ir: &Ir) -> String {
    let t = collapse_whitespace(&ir.api.title);
    if t.is_empty() {
        ir.api.name.wire.clone()
    } else {
        t
    }
}

pub(crate) fn server_ts(ir: &Ir, opts: &Options, manifest: &McpManifest) -> String {
    let has_macros = manifest.tools.iter().any(|t| t.kind == ToolKind::Macro);
    let mut out = String::new();
    out.push_str("#!/usr/bin/env node\n");
    out.push_str(&header(CommentStyle::DoubleSlash, ir));
    out.push_str("\n\n");
    out.push_str(&format!(
        "// MCP server for the {} API: serves manifest.json through @tungsten/mcp on\n\
         // top of the generated SDK. Configuration comes from the environment only\n\
         // (README.md, .env.example).\n\n",
        title(ir)
    ));
    out.push_str("import { readFileSync } from \"node:fs\";\n");
    out.push_str(
        "import { createTungstenMcpServer, type McpManifest, type ServerOptions } from \"@tungsten/mcp\";\n",
    );
    if has_macros {
        out.push_str(
            "import { ClientCore, type AuthConfig, type ClientOptions, type MacroDescriptor } from \"@tungsten/runtime\";\n",
        );
        out.push_str(&format!(
            "import {{ descriptors, macros }} from {};\n",
            ts_string(&opts.sdk_package)
        ));
    } else {
        out.push_str(
            "import { ClientCore, type AuthConfig, type ClientOptions } from \"@tungsten/runtime\";\n",
        );
        out.push_str(&format!(
            "import {{ descriptors }} from {};\n",
            ts_string(&opts.sdk_package)
        ));
    }
    out.push_str("import { customize } from \"./custom/index.js\";\n\n");

    out.push_str(
        "/** Environment variable of each credential, by auth scheme name; a composite\n \
         * profile maps each of its credential keys to a variable. */\n",
    );
    let schemes = env::schemes(ir);
    out.push_str("const AUTH_ENV: Record<string, string | Record<string, string>> = {");
    if !schemes.is_empty() {
        out.push('\n');
    }
    for s in schemes {
        match &s.credentials {
            Credentials::Secret { env, .. } => {
                out.push_str(&format!(
                    "  {}: {},\n",
                    ts_string(&s.scheme),
                    ts_string(env)
                ));
            }
            Credentials::Parts(parts) => {
                out.push_str(&format!("  {}: {{\n", ts_string(&s.scheme)));
                for (key, env, _) in parts {
                    out.push_str(&format!("    {}: {},\n", ts_string(key), ts_string(env)));
                }
                out.push_str("  },\n");
            }
        }
    }
    out.push_str("};\n");
    out.push_str(&format!(
        "const BASE_URL_ENV = {};\nconst MODE_ENV = {};\n\n",
        ts_string(&env::base_url(ir)),
        ts_string(&env::mode(ir))
    ));
    out.push_str(SERVER_HELPERS);
    out.push('\n');
    out.push_str("async function main(): Promise<void> {\n");
    out.push_str("  const options: ServerOptions = {\n");
    out.push_str("    manifest: loadManifest(),\n");
    out.push_str("    // One core per MCP session: confirmation tokens and shown-once state are per session.\n");
    out.push_str("    createCore: () => new ClientCore(descriptors.api, clientOptions()),\n");
    if has_macros {
        out.push_str("    macros: Object.fromEntries(macros.macroDescriptors.map((m): [string, MacroDescriptor] => [m.name, m])),\n");
    }
    out.push_str(&format!("    name: {},\n", ts_string(&opts.package)));
    out.push_str(&format!("    version: {},\n", ts_string(&opts.version)));
    if opts.sandbox {
        out.push_str("    sandbox: { enabled: true },\n");
    }
    out.push_str("  };\n");
    out.push_str("  const mode = modeOverride();\n");
    out.push_str("  if (mode !== undefined) options.mode = mode;\n");
    out.push_str("  await createTungstenMcpServer(customize(options)).connectStdio();\n");
    out.push_str("}\n\n");
    out.push_str("main().catch((error: unknown) => {\n");
    out.push_str(&format!(
        "  process.stderr.write(`{}: ${{error instanceof Error ? error.message : String(error)}}\\n`);\n",
        opts.bin
    ));
    out.push_str("  process.exitCode = 1;\n");
    out.push_str("});\n");
    out
}

/// The parts of `src/server.ts` that do not depend on the API.
const SERVER_HELPERS: &str = r#"/** A variable's value; unset and empty are the same. */
function env(name: string): string | undefined {
  const value = process.env[name];
  return value === undefined || value === "" ? undefined : value;
}

/** ClientOptions from the environment. Schemes without credentials are left
 * out; the runtime names what is missing when an operation needs them. */
function clientOptions(): ClientOptions {
  const auth: AuthConfig = {};
  for (const [scheme, source] of Object.entries(AUTH_ENV)) {
    if (typeof source === "string") {
      const secret = env(source);
      if (secret !== undefined) auth[scheme] = secret;
      continue;
    }
    const parts: Record<string, string> = {};
    for (const [key, name] of Object.entries(source)) {
      const value = env(name);
      if (value !== undefined) parts[key] = value;
    }
    if (Object.keys(parts).length > 0) auth[scheme] = parts;
  }
  const options: ClientOptions = { auth, operations: descriptors.operations };
  const baseUrl = env(BASE_URL_ENV);
  if (baseUrl !== undefined) options.baseUrl = baseUrl;
  return options;
}

/** The disclosure mode forced by the environment, if any. */
function modeOverride(): "discrete" | "progressive" | undefined {
  const mode = env(MODE_ENV);
  if (mode === undefined || mode === "discrete" || mode === "progressive") return mode;
  throw new Error(`${MODE_ENV} must be "discrete" or "progressive", not ${JSON.stringify(mode)}`);
}

/** manifest.json next to this package's dist/ directory. */
function loadManifest(): McpManifest {
  const url = new URL("../manifest.json", import.meta.url);
  let text: string;
  try {
    text = readFileSync(url, "utf8");
  } catch {
    throw new Error(`cannot read ${url.pathname}; reinstall the package`);
  }
  const manifest: unknown = JSON.parse(text);
  if (typeof manifest !== "object" || manifest === null || (manifest as { manifestVersion?: unknown }).manifestVersion !== 1) {
    throw new Error(`${url.pathname} is not a version 1 tungsten MCP manifest`);
  }
  return manifest as McpManifest;
}
"#;

/// Every variable of `.env.example` and the README: `(name, what)`.
fn variables(ir: &Ir) -> Vec<(String, String)> {
    let mut out = vec![(
        env::base_url(ir),
        match ir.api.servers.first() {
            Some(s) => format!("Base URL of the API (default `{}`).", s.url),
            None => "Base URL of the API (required: the API declares no server).".into(),
        },
    )];
    for s in env::schemes(ir) {
        match &s.credentials {
            Credentials::Secret { env, what } => {
                out.push((env.clone(), format!("`{}`: {what}.", s.scheme)));
            }
            Credentials::Parts(parts) => {
                for (_, env, what) in parts {
                    out.push((env.clone(), format!("`{}` profile: {what}.", s.scheme)));
                }
            }
        }
    }
    out.push((
        env::mode(ir),
        "`discrete` or `progressive`: overrides the generated disclosure mode.".into(),
    ));
    out
}

pub(crate) fn env_example(ir: &Ir) -> String {
    let mut out = header(CommentStyle::Hash, ir);
    out.push_str("\n#\n");
    out.push_str(&format!(
        "# Environment of the {} MCP server. Your MCP client passes these to the\n\
         # server process; set only what your operations need and never commit secrets.\n",
        title(ir)
    ));
    for (name, what) in variables(ir) {
        out.push('\n');
        out.push_str(&format!("# {}\n", what.replace('`', "")));
        out.push_str(&format!("{name}=\n"));
    }
    out
}

pub(crate) fn readme(ir: &Ir, opts: &Options, manifest: &McpManifest, budget: &Budget) -> String {
    let title = title(ir);
    let mut out = String::new();
    out.push_str("<!--\n");
    for l in header(CommentStyle::DoubleSlash, ir).lines() {
        out.push_str(l.trim_start_matches("//").trim_start());
        out.push('\n');
    }
    out.push_str("-->\n\n");
    out.push_str(&format!("# {}\n\n", opts.package));
    let macros = manifest
        .tools
        .iter()
        .filter(|t| t.kind == ToolKind::Macro)
        .count();
    out.push_str(&format!(
        "MCP server for the {title} API, generated by tungsten. It serves {} tools \
         ({} operations, {macros} macros) over stdio through `@tungsten/mcp`, calling \
         the API with the generated SDK `{}`.\n\n",
        manifest.tools.len(),
        manifest.tools.len() - macros,
        opts.sdk_package
    ));

    out.push_str("## Run\n\n");
    out.push_str(&format!(
        "```sh\nnpm install\nnpm run build\nnode dist/server.js    # or `{}` once installed\n```\n\n",
        opts.bin
    ));
    out.push_str("Client configuration (the `mcpServers` entry of Claude Desktop, Claude Code and other MCP clients):\n\n");
    let mut env_map = Map::new();
    for (name, _) in variables(ir) {
        if name != env::mode(ir) {
            env_map.insert(name, json!("..."));
        }
    }
    let mut servers = Map::new();
    servers.insert(
        ir.api.name.wire.clone(),
        json!({ "command": "npx", "args": ["-y", opts.package], "env": env_map }),
    );
    out.push_str("```json\n");
    out.push_str(&json_text(&json!({ "mcpServers": servers })));
    out.push_str("```\n\n");
    out.push_str("For a local build use `\"command\": \"node\"` with the absolute path of `dist/server.js` as the argument.\n\n");

    out.push_str("## Environment\n\n");
    out.push_str("Credentials are read from the environment only, never from arguments; `.env.example` lists every variable. Set only those of the schemes your operations need.\n\n");
    out.push_str("| Variable | Meaning |\n|---|---|\n");
    for (name, what) in variables(ir) {
        out.push_str(&format!("| `{name}` | {what} |\n"));
    }
    out.push('\n');

    out.push_str("## Modes\n\n");
    let selected = match manifest.mode {
        Mode::Discrete => "discrete",
        Mode::Progressive => "progressive",
    };
    out.push_str(&format!(
        "This server starts in **{selected}** mode ({} tools, threshold {}; agent.yml `defaults.disclosure`).\n\n",
        manifest.tools.len(),
        manifest.threshold
    ));
    out.push_str("- `discrete`: one MCP tool per operation and macro, with input and output schemas and annotations from the safety tier.\n");
    out.push_str("- `progressive`: a few tools instead of the whole list. `search_tools(query, cluster?, limit?)` searches a BM25 index built at generation time, `describe_tool(name)` returns one tool's schemas and rules, `invoke(name, args)` calls it, `preview(name, args)` shows a call without sending it, `list_clusters()` lists the groups of tools.\n\n");
    out.push_str(&format!(
        "Set `{}` to `discrete` or `progressive` to override the mode.\n\n",
        env::mode(ir)
    ));

    out.push_str("## Safety rules\n\n");
    out.push_str("- Read-only tools are annotated `readOnlyHint`; destructive and irreversible ones `destructiveHint`.\n");
    out.push_str("- Destructive and irreversible tools need `preview` first: pass its `confirmation_token` with exactly the same arguments. A token authorizes one intent and expires.\n");
    out.push_str("- Tools with an idempotency key take it as `idempotency_key`. Caller-owned keys are generated by the agent once per intent, persisted and reused on every retry; a new key can repeat a side effect.\n");
    out.push_str("- Failures are returned as the diagnostic envelope (`category`, `retryable`, `remediation`, `next_action`), never as protocol errors. After `OUTCOME_UNKNOWN`, check the outcome or retry with the same key only.\n");
    out.push_str("- One-time secrets are returned once and redacted on repeated identical calls within a session.\n");
    out.push_str("- Planned operations are not tools.\n\n");

    out.push_str("## Token budget\n\n");
    out.push_str(&format!(
        "Measured at generation time with the `{COUNTER_NAME}` counter of tungsten-tokens.\n\n"
    ));
    out.push_str("| Measure | Tokens | Budget |\n|---|---|---|\n");
    out.push_str(&format!(
        "| Progressive tool list and index summary | {} | {INDEX_BUDGET} |\n",
        budget.progressive
    ));
    out.push_str(&format!(
        "| Discrete tool list ({} tools) | {} | |\n",
        manifest.tools.len(),
        budget.discrete
    ));
    if let Some((name, n)) = &budget.largest {
        out.push_str(&format!(
            "| Largest tool schema (`{name}`) | {n} | {} |\n",
            budget.schema_budget
        ));
    }
    out.push_str(&format!(
        "| Median tool schema | {} | {} |\n",
        budget.median, budget.schema_budget
    ));
    out
}
