// SPDX-License-Identifier: AGPL-3.0-only
//! Generated-file headers, writing to disk and staleness checks.
//!
//! PHASE-2 STUB: `write_output` writes files only; the emit-core work package
//! adds `.tungsten/manifest.json`, stale-file removal and custom-file
//! protection, and `check_stale` (TG0901).

use std::path::Path;

use tungsten_core::{Diagnostic, Diagnostics};
use tungsten_ir::Ir;

use crate::{CommentStyle, FileSet};

/// The "do not edit" header for a generated file, as comment lines in
/// `style` (no trailing blank line). Contains the tungsten version and the
/// input digests from `ir.generator`, never timestamps or absolute paths.
pub fn header(style: CommentStyle, ir: &Ir) -> String {
    let mut text = format!(
        "Generated by tungsten {}. Do not edit.\nInputs:",
        ir.generator.tungsten_version
    );
    for (name, digest) in &ir.generator.inputs {
        text.push_str(&format!("\n  {name} {}", digest.short()));
    }
    let mut w = crate::Writer::new("  ");
    match style {
        CommentStyle::JsDoc | CommentStyle::DoubleSlash | CommentStyle::RustDoc => {
            w.doc(CommentStyle::DoubleSlash, &text)
        }
        CommentStyle::Hash | CommentStyle::PyDocstring => w.doc(CommentStyle::Hash, &text),
    };
    w.finish().trim_end().to_string()
}

#[derive(Debug, Clone, Default)]
pub struct WriteOptions {
    /// Report what would change without touching the disk.
    pub dry_run: bool,
}

/// What [`write_output`] did, paths relative to the output directory, sorted.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct WriteReport {
    pub written: Vec<String>,
    pub unchanged: Vec<String>,
    pub removed: Vec<String>,
}

/// Write a file set under `out_dir`.
pub fn write_output(
    files: &FileSet,
    out_dir: &Path,
    opts: &WriteOptions,
) -> Result<WriteReport, Diagnostics> {
    let mut report = WriteReport::default();
    for (rel, bytes) in files.iter() {
        let path = out_dir.join(rel);
        if std::fs::read(&path).is_ok_and(|old| old == bytes) {
            report.unchanged.push(rel.to_string());
            continue;
        }
        if !opts.dry_run {
            let res = path
                .parent()
                .map_or(Ok(()), std::fs::create_dir_all)
                .and_then(|_| std::fs::write(&path, bytes));
            if let Err(e) = res {
                let mut d = Diagnostics::new();
                d.push(Diagnostic::error(
                    "TG0701",
                    format!("cannot write {}: {e}", path.display()),
                ));
                return Err(d);
            }
        }
        report.written.push(rel.to_string());
    }
    Ok(report)
}

/// TG0901 for every file that differs from disk or is missing.
pub fn check_stale(files: &FileSet, out_dir: &Path) -> Diagnostics {
    let mut d = Diagnostics::new();
    for (rel, bytes) in files.iter() {
        if std::fs::read(out_dir.join(rel)).ok().as_deref() != Some(bytes) {
            d.push(Diagnostic::error(
                "TG0901",
                format!("generated file {rel} is stale"),
            ));
        }
    }
    d
}
