// SPDX-License-Identifier: AGPL-3.0-only
//! Generated-file headers, writing to disk and staleness checks.
//!
//! Every target directory written by [`write_output`] holds
//! `.tungsten/manifest.json` ([`OutputManifest`]): the tungsten version, the
//! input digests and every generated file with its BLAKE3 digest. The
//! manifest is how a later run knows which files it owns:
//!
//! - files listed in the previous manifest that are no longer generated are
//!   removed;
//! - files under a path segment named `custom` ([`is_custom_path`]) are
//!   hand-editable templates: created when missing, never overwritten,
//!   never removed;
//! - a non-empty directory without a manifest was not written by tungsten,
//!   so writing into it is refused (TG0703) unless
//!   [`WriteOptions::force`] is set;
//! - no path may leave the output directory, also not through a symlink
//!   (TG0704), and `.tungsten/` is reserved for the manifest.
//!
//! With [`WriteOptions::ir`], `.tungsten/surface.json` (the API surface
//! snapshot of [`crate::surface`]) is written next to the manifest, so a
//! later `tungsten diff --semver` can classify the changes since this
//! generation. The snapshot is bookkeeping, not output: it is not listed in
//! the manifest and not part of the staleness comparison.
//!
//! [`check_stale`] reports the same differences as TG0901 without writing.

use std::collections::{BTreeMap, BTreeSet};
use std::io::ErrorKind;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use tungsten_core::{Diagnostic, Diagnostics, Digest};
use tungsten_ir::{GeneratorStamp, Ir};

use crate::fileset::valid_path;
use crate::surface::{ApiSurface, SURFACE_PATH};
use crate::{CommentStyle, FileSet};

/// Where the output manifest lives, relative to the output directory.
pub const MANIFEST_PATH: &str = ".tungsten/manifest.json";

/// First path segment reserved for tungsten's own bookkeeping.
const RESERVED_DIR: &str = ".tungsten";

/// Version of the [`OutputManifest`] format.
pub const MANIFEST_FORMAT: u32 = 1;

/// The header text without comment markers: the tungsten version, the
/// "do not edit" notice and the short digest of every input, sorted by
/// input name. Never contains timestamps or absolute paths (input names are
/// the paths as written in the manifest).
pub fn header_text(ir: &Ir) -> String {
    let mut text = format!(
        "Generated by tungsten {}. Do not edit.",
        ir.generator.tungsten_version
    );
    if !ir.generator.inputs.is_empty() {
        let inputs: Vec<String> = ir
            .generator
            .inputs
            .iter()
            .map(|(name, digest)| format!("{name} {}", digest.short()))
            .collect();
        text.push_str("\nInputs: ");
        text.push_str(&inputs.join(", "));
    }
    text
}

/// The "do not edit" header for a generated file, as comment lines in
/// `style` (no trailing blank line). Contains the tungsten version and the
/// input digests from `ir.generator`, never timestamps or absolute paths.
/// Block styles (JSDoc, docstrings) are rendered as line comments so the
/// header never becomes the documentation of the first item.
pub fn header(style: CommentStyle, ir: &Ir) -> String {
    let text = header_text(ir);
    let mut w = crate::Writer::new("  ");
    match style {
        CommentStyle::JsDoc | CommentStyle::DoubleSlash | CommentStyle::RustDoc => {
            w.doc(CommentStyle::DoubleSlash, &text)
        }
        CommentStyle::Hash | CommentStyle::PyDocstring => w.doc(CommentStyle::Hash, &text),
    };
    w.finish().trim_end().to_string()
}

/// Whether `path` (relative, forward slashes) is a hand-editable file: one
/// of its directory segments is named `custom` (`src/custom/index.ts`).
/// Such files are created once and never overwritten or removed.
pub fn is_custom_path(path: &str) -> bool {
    let mut segments: Vec<&str> = path.split('/').collect();
    segments.pop();
    segments.contains(&"custom")
}

#[derive(Debug, Clone, Default)]
pub struct WriteOptions {
    /// Report what would change without touching the disk.
    pub dry_run: bool,
    /// Write into a non-empty directory that has no output manifest (or an
    /// unreadable one). Files tungsten did not list are left alone.
    pub force: bool,
    /// Version and input digests recorded in the output manifest, normally
    /// the IR's `generator`. `None` records this crate's version and no
    /// inputs.
    pub generator: Option<GeneratorStamp>,
    /// The IR the files were generated from. When set, its API surface
    /// snapshot is written to `.tungsten/surface.json`.
    pub ir: Option<Arc<Ir>>,
    /// The agent tool names the target serves (tool name → operation id or
    /// macro name), recorded in the snapshot ([`ApiSurface::with_tools`]).
    pub tools: BTreeMap<String, String>,
}

/// What [`write_output`] did, paths relative to the output directory, sorted.
/// The output manifest itself is not listed.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct WriteReport {
    /// Files created or replaced (with `dry_run`: that would be).
    pub written: Vec<String>,
    /// Generated files whose bytes were already on disk.
    pub unchanged: Vec<String>,
    /// Files of the previous generation that are no longer generated.
    pub removed: Vec<String>,
    /// Custom files that already existed and were left as they are.
    pub preserved: Vec<String>,
}

/// One generated file in the output manifest.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManifestFile {
    pub path: String,
    pub digest: Digest,
}

/// `.tungsten/manifest.json`: what one generation wrote.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutputManifest {
    /// [`MANIFEST_FORMAT`].
    pub format: u32,
    pub tungsten_version: String,
    /// Input name → digest, sorted.
    pub inputs: BTreeMap<String, Digest>,
    /// Generated files tungsten owns, sorted by path, with the digest of
    /// their bytes.
    pub files: Vec<ManifestFile>,
    /// Custom files (created once, then owned by the user), sorted.
    #[serde(default)]
    pub custom: Vec<String>,
}

impl OutputManifest {
    /// The manifest describing `files`.
    pub fn new(files: &FileSet, generator: Option<&GeneratorStamp>) -> Self {
        let (custom, generated): (Vec<_>, Vec<_>) =
            files.iter().partition(|(path, _)| is_custom_path(path));
        OutputManifest {
            format: MANIFEST_FORMAT,
            tungsten_version: generator.map_or_else(
                || env!("CARGO_PKG_VERSION").to_string(),
                |g| g.tungsten_version.clone(),
            ),
            inputs: generator.map(|g| g.inputs.clone()).unwrap_or_default(),
            files: generated
                .into_iter()
                .map(|(path, bytes)| ManifestFile {
                    path: path.to_string(),
                    digest: Digest::of(bytes),
                })
                .collect(),
            custom: custom.into_iter().map(|(p, _)| p.to_string()).collect(),
        }
    }

    /// Indented JSON with a trailing newline.
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut text = serde_json::to_string_pretty(self).unwrap_or_default();
        text.push('\n');
        text.into_bytes()
    }

    /// Parse a manifest. Fails on malformed JSON, an unknown format version
    /// or a path that is not a plain relative path inside the directory.
    pub fn parse(bytes: &[u8]) -> Result<Self, String> {
        let manifest: OutputManifest =
            serde_json::from_slice(bytes).map_err(|e| format!("not a tungsten manifest: {e}"))?;
        if manifest.format != MANIFEST_FORMAT {
            return Err(format!(
                "manifest format {} is not supported (expected {MANIFEST_FORMAT})",
                manifest.format
            ));
        }
        let paths = manifest
            .files
            .iter()
            .map(|f| f.path.as_str())
            .chain(manifest.custom.iter().map(String::as_str));
        for path in paths {
            if !valid_path(path) || is_reserved(path) {
                return Err(format!("manifest lists the invalid path {path:?}"));
            }
        }
        Ok(manifest)
    }
}

fn is_reserved(path: &str) -> bool {
    path.split('/').next() == Some(RESERVED_DIR)
}

/// `out_dir/rel` for diagnostics.
fn shown(out_dir: &Path, rel: &str) -> String {
    out_dir.join(rel).display().to_string()
}

fn io_error(path: String, action: &str, e: &std::io::Error) -> Diagnostic {
    Diagnostic::error("TG0701", format!("cannot {action} {path}: {e}")).at(path, "", None)
}

/// The previous generation's manifest.
enum Previous {
    /// The directory does not exist or is empty.
    Fresh,
    Manifest(OutputManifest),
    /// The directory has content but no manifest (or an invalid one).
    Foreign(String),
}

fn read_previous(out_dir: &Path) -> Result<Previous, Diagnostic> {
    match std::fs::symlink_metadata(out_dir) {
        Err(e) if e.kind() == ErrorKind::NotFound => return Ok(Previous::Fresh),
        Err(e) => return Err(io_error(out_dir.display().to_string(), "read", &e)),
        Ok(_) if !out_dir.is_dir() => {
            let path = out_dir.display().to_string();
            return Err(Diagnostic::error(
                "TG0701",
                format!("output directory {path} is not a directory"),
            )
            .at(path, "", None));
        }
        Ok(_) => {}
    }
    let manifest_path = out_dir.join(MANIFEST_PATH);
    match std::fs::read(&manifest_path) {
        Ok(bytes) => Ok(match OutputManifest::parse(&bytes) {
            Ok(m) => Previous::Manifest(m),
            Err(e) => Previous::Foreign(format!("{}: {e}", manifest_path.display())),
        }),
        Err(e) if e.kind() == ErrorKind::NotFound => {
            let mut entries = std::fs::read_dir(out_dir)
                .map_err(|e| io_error(out_dir.display().to_string(), "read", &e))?;
            Ok(if entries.next().is_none() {
                Previous::Fresh
            } else {
                Previous::Foreign(format!("{} does not exist", manifest_path.display()))
            })
        }
        Err(e) => Err(io_error(manifest_path.display().to_string(), "read", &e)),
    }
}

/// TG0704 when `rel` would leave `out_dir`: an existing component that is a
/// symlink resolving outside the directory, or a final component that is a
/// symlink at all (writing would follow it).
fn check_inside(out_dir: &Path, canonical: &Path, rel: &str) -> Option<Diagnostic> {
    let segments: Vec<&str> = rel.split('/').collect();
    let mut cur = out_dir.to_path_buf();
    for (i, segment) in segments.iter().enumerate() {
        cur.push(segment);
        let Ok(meta) = std::fs::symlink_metadata(&cur) else {
            return None;
        };
        if !meta.file_type().is_symlink() {
            continue;
        }
        let last = i + 1 == segments.len();
        let inside =
            !last && std::fs::canonicalize(&cur).is_ok_and(|target| target.starts_with(canonical));
        if !inside {
            let path = shown(out_dir, rel);
            return Some(
                Diagnostic::error(
                    "TG0704",
                    format!("output path {path} goes through a symlink that leaves the output directory or replaces a generated file"),
                )
                .at(path, "", None)
                .with_help("remove the symlink; generated files are always written inside the target's `out` directory"),
            );
        }
    }
    None
}

/// Paths of `files` that are reserved for tungsten (`.tungsten/...`).
fn reserved_paths(files: &FileSet, out_dir: &Path) -> Diagnostics {
    let mut d = Diagnostics::new();
    for (rel, _) in files.iter().filter(|(rel, _)| is_reserved(rel)) {
        let path = shown(out_dir, rel);
        d.push(
            Diagnostic::error(
                "TG0704",
                format!("generated path {path} is inside the reserved .tungsten directory"),
            )
            .at(path, "", None),
        );
    }
    d
}

/// Write a file set under `out_dir`, maintaining `.tungsten/manifest.json`.
///
/// Nothing is written when any check fails: TG0703 (a non-empty directory
/// that tungsten did not generate, without `force`), TG0704 (a path leaving
/// the directory or inside `.tungsten/`). A failed write or removal is
/// TG0701; files written before it stay written.
pub fn write_output(
    files: &FileSet,
    out_dir: &Path,
    opts: &WriteOptions,
) -> Result<WriteReport, Diagnostics> {
    let mut errors = reserved_paths(files, out_dir);
    let previous = match read_previous(out_dir) {
        Ok(p) => p,
        Err(d) => {
            errors.push(d);
            return Err(errors);
        }
    };
    let previous = match previous {
        Previous::Foreign(reason) if !opts.force => {
            let path = out_dir.display().to_string();
            errors.push(
                Diagnostic::error(
                    "TG0703",
                    format!("refusing to write into {path}: it is not empty and was not generated by tungsten ({reason})"),
                )
                .at(path, "", None)
                .with_help("choose an empty or new `out` directory, or pass --force to write into it anyway"),
            );
            return Err(errors);
        }
        Previous::Manifest(m) => Some(m),
        Previous::Fresh | Previous::Foreign(_) => None,
    };

    let stale: Vec<String> = previous
        .iter()
        .flat_map(|m| m.files.iter().map(|f| f.path.clone()))
        .filter(|p| files.get(p).is_none() && !is_custom_path(p))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect();
    if let Ok(canonical) = std::fs::canonicalize(out_dir) {
        let paths = files
            .iter()
            .map(|(rel, _)| rel)
            .chain(stale.iter().map(String::as_str))
            .chain([MANIFEST_PATH])
            .chain(opts.ir.as_ref().map(|_| SURFACE_PATH));
        for rel in paths {
            errors.extend(Diagnostics(
                check_inside(out_dir, &canonical, rel).into_iter().collect(),
            ));
        }
    }
    if errors.has_errors() {
        return Err(errors);
    }

    let mut report = WriteReport::default();
    for (rel, bytes) in files.iter() {
        let path = out_dir.join(rel);
        let exists = std::fs::symlink_metadata(&path).is_ok();
        if exists && is_custom_path(rel) {
            report.preserved.push(rel.to_string());
        } else if exists && std::fs::read(&path).is_ok_and(|old| old == bytes) {
            report.unchanged.push(rel.to_string());
        } else {
            report.written.push(rel.to_string());
        }
    }
    report.removed = stale
        .into_iter()
        .filter(|rel| std::fs::symlink_metadata(out_dir.join(rel)).is_ok())
        .collect();
    if opts.dry_run {
        return Ok(report);
    }

    let fail = |d: Diagnostic| {
        let mut all = Diagnostics::new();
        all.push(d);
        all
    };
    for rel in &report.removed {
        let path = out_dir.join(rel);
        std::fs::remove_file(&path)
            .map_err(|e| fail(io_error(shown(out_dir, rel), "remove", &e)))?;
        prune_empty_dirs(out_dir, &path);
    }
    for rel in &report.written {
        let bytes = files.get(rel).unwrap_or_default();
        write_file(&out_dir.join(rel), bytes)
            .map_err(|e| fail(io_error(shown(out_dir, rel), "write", &e)))?;
    }
    let manifest = OutputManifest::new(files, opts.generator.as_ref()).to_bytes();
    let surface = opts
        .ir
        .as_ref()
        .map(|ir| ApiSurface::of(ir).with_tools(opts.tools.clone()).to_bytes());
    let bookkeeping = [(MANIFEST_PATH, Some(manifest)), (SURFACE_PATH, surface)];
    for (rel, bytes) in bookkeeping {
        let Some(bytes) = bytes else { continue };
        let path = out_dir.join(rel);
        if std::fs::read(&path).ok().as_deref() != Some(bytes.as_slice()) {
            write_file(&path, &bytes)
                .map_err(|e| fail(io_error(shown(out_dir, rel), "write", &e)))?;
        }
    }
    Ok(report)
}

fn write_file(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, bytes)
}

/// Remove the directories between `removed` and `out_dir` that became
/// empty, deepest first. `out_dir` itself is kept.
fn prune_empty_dirs(out_dir: &Path, removed: &Path) {
    let mut dir: Option<PathBuf> = removed.parent().map(Path::to_path_buf);
    while let Some(d) = dir {
        if d == out_dir || !d.starts_with(out_dir) || std::fs::remove_dir(&d).is_err() {
            break;
        }
        dir = d.parent().map(Path::to_path_buf);
    }
}

/// Why a generated file is stale.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum StaleReason {
    /// The file (generated or custom) does not exist.
    Missing,
    /// A generated file's bytes differ from what would be written.
    Changed,
    /// Listed by the previous generation, no longer generated: it would be
    /// removed.
    Removed,
    /// `.tungsten/manifest.json` is missing or unreadable.
    ManifestMissing,
}

impl StaleReason {
    fn describe(self) -> &'static str {
        match self {
            StaleReason::Missing => "missing",
            StaleReason::Changed => "content differs",
            StaleReason::Removed => "no longer generated and would be removed",
            StaleReason::ManifestMissing => "missing or unreadable",
        }
    }
}

/// One difference between a file set and an output directory.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct StaleFile {
    /// Relative to the output directory.
    pub path: String,
    pub reason: StaleReason,
}

impl StaleFile {
    /// The TG0901 error for this file under `out_dir`.
    pub fn diagnostic(&self, out_dir: &Path) -> Diagnostic {
        let path = shown(out_dir, &self.path);
        Diagnostic::error(
            "TG0901",
            format!("generated file {path} is stale: {}", self.reason.describe()),
        )
        .at(path, "", None)
        .with_help("run `tungsten generate` and commit the result")
    }
}

/// Every difference [`write_output`] would make, sorted by path: a
/// generated file that is missing or differs, a custom file that is missing,
/// a file of the previous generation that would be removed, and a missing or
/// unreadable output manifest. Reads only.
pub fn stale_files(files: &FileSet, out_dir: &Path) -> Vec<StaleFile> {
    let mut out = vec![];
    let mut push = |path: &str, reason| {
        out.push(StaleFile {
            path: path.to_string(),
            reason,
        })
    };
    for (rel, bytes) in files.iter() {
        match std::fs::read(out_dir.join(rel)) {
            Err(_) => push(rel, StaleReason::Missing),
            Ok(_) if is_custom_path(rel) => {}
            Ok(old) if old != bytes => push(rel, StaleReason::Changed),
            Ok(_) => {}
        }
    }
    let manifest = std::fs::read(out_dir.join(MANIFEST_PATH))
        .ok()
        .and_then(|bytes| OutputManifest::parse(&bytes).ok());
    match manifest {
        None => push(MANIFEST_PATH, StaleReason::ManifestMissing),
        Some(m) => {
            for f in m.files.iter().filter(|f| files.get(&f.path).is_none()) {
                if !is_custom_path(&f.path) && out_dir.join(&f.path).exists() {
                    push(&f.path, StaleReason::Removed);
                }
            }
        }
    }
    out.sort();
    out
}

/// TG0901 for every file of [`stale_files`]. Reads only.
pub fn check_stale(files: &FileSet, out_dir: &Path) -> Diagnostics {
    Diagnostics(
        stale_files(files, out_dir)
            .iter()
            .map(|f| f.diagnostic(out_dir))
            .collect(),
    )
}
