# SPDX-License-Identifier: Apache-2.0
"""The contract between Python SDKs generated by tungsten and this runtime.

It mirrors ``runtimes/ts/src/types.ts`` (planning/05 "Python SDK",
planning/06 "Runtime and safety") with Python conventions: descriptor keys
are snake_case, generated methods take keyword arguments, and a merged body
field carries both its Python argument name and its wire name because a wire
name is not always a valid keyword argument.

Generated code is mostly data: one ``OperationDescriptor`` per operation, one
``ApiDescriptor`` per client, ``MacroDescriptor``s, and thin typed wrappers
that call ``ClientCore`` (sync) or ``AsyncClientCore`` (async). Everything with
behaviour lives in the runtime.

The diagnostic envelope (``Diagnostic``) is byte-for-byte the same shape as in
the TypeScript runtime (``specs/envelope.schema.json``): agents see identical
errors whatever the SDK language.

PHASE-4 CONTRACT: shared by the runtime and the Python emitter. Additive
changes only (new optional keys, new literal members), with both sides
updated.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any, Literal, NotRequired, Protocol, TypedDict

# ------------------------------------------------------------------ errors

Safety = Literal["read_only", "mutating", "destructive", "irreversible"]
Retryable = Literal["never", "after_delay", "same_key_only", "after_remediation"]
Category = Literal[
    "VALIDATION_FAILED",
    "MALFORMED_REQUEST",
    "REQUEST_TOO_LARGE",
    "AUTH_FAILED",
    "NOT_FOUND",
    "CONFLICT",
    "PRECONDITION_FAILED",
    "RATE_LIMITED",
    "UPSTREAM_UNAVAILABLE",
    "OUTCOME_UNKNOWN",
    "TRANSPORT_FAILED",
    "CONFIRMATION_REQUIRED",
    "GATE_DISABLED",
    "UNEXPECTED_RESPONSE",
]


class Trace(TypedDict):
    attempts: int


class Diagnostic(TypedDict):
    """The diagnostic error envelope (planning/06), identical across runtimes."""

    status: Literal["error"]
    category: Category
    operation: str
    http_status: int | None
    code: str | None
    failed_parameter: str | None
    received_value: Any
    expected: str | None
    remediation: str
    retryable: Retryable
    retry_after_ms: int | None
    next_action: str | None
    request_id: str | None
    trace: Trace


@dataclass(frozen=True, slots=True)
class ResponseMeta:
    status: int
    headers: Mapping[str, str]
    request_id: str | None
    attempts: int


@dataclass(frozen=True, slots=True)
class Verification:
    checked: bool
    passed: bool
    observed: Any
    timed_out: bool = False
    error: Diagnostic | None = None


@dataclass(frozen=True, slots=True)
class Ok[T]:
    """A successful call. ``value`` is ``None`` for a bodiless success.

    ``value`` is the response validator's ``Valid.data`` when the operation
    has a response validator and ``ClientOptions.validate_responses`` is
    ``warn`` or ``strict`` and the body conforms; otherwise the decoded body
    (parsed JSON, text, or bytes)."""

    value: T
    meta: ResponseMeta
    verification: Verification | None = None
    ok: Literal[True] = True
    #: ``poll()`` only: True when the budget ran out before ``until`` held
    #: (the value is the last answer), False when it held; None elsewhere.
    timed_out: bool | None = None
    #: The operation's sensitive response field paths (wire names): redacted
    #: in ``repr()``, so logging a result never prints a one-time secret.
    sensitive_fields: tuple[str, ...] = field(default=(), repr=False, compare=False, kw_only=True)

    def __repr__(self) -> str:
        return (
            f"Ok(value={_shown(self.value, self.sensitive_fields)}, meta={self.meta!r}, "
            f"verification={self.verification!r}, ok=True, timed_out={self.timed_out!r})"
        )


@dataclass(frozen=True, slots=True)
class Err:
    """A failed call; ``error`` is the envelope."""

    error: Diagnostic
    ok: Literal[False] = False
    #: What the failed call or macro already produced, when its effect
    #: happened: the decoded success body of a mutation whose response failed
    #: strict validation, or a macro's completed step results by their ``as``
    #: names. It can hold values the API shows only once (a signing secret),
    #: so store them before acting on the error; they are never repeated in
    #: the envelope. None otherwise. Never shown by ``repr()``.
    partial: Any = None

    def __repr__(self) -> str:
        partial = "None" if self.partial is None else "<not shown: store it, never log it>"
        return f"Err(error={self.error!r}, ok=False, partial={partial})"


def _shown(value: object, sensitive: Sequence[str]) -> str:
    """``repr(value)`` with sensitive fields redacted: the listed paths and
    members whose names look secret, also inside a model's JSON form."""
    from ._util import redact_paths, redact_sensitive_keys

    dump = getattr(value, "model_dump", None)
    try:
        plain: object = dump(mode="json", by_alias=True) if callable(dump) else value
    except Exception:
        return f"<{type(value).__name__}: not shown>"
    redacted = redact_sensitive_keys(redact_paths(plain, sensitive))
    if redacted == plain:
        return repr(value)
    return f"{type(value).__name__}({redacted!r})" if plain is not value else repr(redacted)


type Result[T] = Ok[T] | Err
"""Generated methods return ``Result[T]`` and never raise for API or
transport errors. ``TungstenError`` and ``unwrap`` (runtime) give raising
ergonomics. Branch with ``isinstance(result, Ok)`` or ``result.ok is True``
(type checkers narrow both; a bare ``if result.ok:`` does not narrow)."""

# ------------------------------------------------------------- descriptors

HttpMethod = Literal["GET", "PUT", "POST", "DELETE", "OPTIONS", "HEAD", "PATCH", "TRACE"]
ParamLocation = Literal["path", "query", "header", "cookie"]
ParamStyle = Literal["simple", "form", "label", "matrix", "space_delimited", "pipe_delimited", "deep_object"]
ParamRole = Literal["plain", "idempotency_key", "dry_run", "origin", "auth"]


class ParamDescriptor(TypedDict):
    """``name`` is the Python keyword argument. Params with the roles
    ``idempotency_key``, ``origin`` and ``auth`` are not arguments: they come
    from ``CallOptions.idempotency_key`` and the auth profile."""

    name: str
    wire: str
    location: ParamLocation
    required: bool
    style: ParamStyle
    explode: bool
    role: ParamRole
    sensitive: NotRequired[bool]


BodyEncoding = Literal["json", "form", "multipart", "bytes", "text"]


class MergedBodyField(TypedDict):
    arg: str
    wire: str


class MergedBodyShape(TypedDict):
    kind: Literal["merged"]
    fields: list[MergedBodyField]


class ArgBodyShape(TypedDict):
    kind: Literal["arg"]
    arg: str


class BodyDescriptor(TypedDict):
    media_type: str
    encoding: BodyEncoding
    required: bool
    shape: MergedBodyShape | ArgBodyShape


StatusMatch = int | Literal["1XX", "2XX", "3XX", "4XX", "5XX", "default"]


class ResponseDescriptor(TypedDict):
    status: StatusMatch
    kind: Literal["success", "error", "ambiguous"]
    media_type: str | None


class CursorPagination(TypedDict):
    style: Literal["cursor"]
    request_param: str
    response_field: str
    items_field: str
    page_size_param: str | None


class OffsetPagination(TypedDict):
    style: Literal["offset"]
    offset_param: str
    limit_param: str
    items_field: str


class PagePagination(TypedDict):
    style: Literal["page"]
    page_param: str
    size_param: str
    items_field: str


class LinkHeaderPagination(TypedDict):
    style: Literal["link_header"]
    items_field: str


PaginationDescriptor = CursorPagination | OffsetPagination | PagePagination | LinkHeaderPagination

IdempotencyKind = Literal["none", "auto", "caller_owned", "content_hash", "content_identity"]


class RemediationEntry(TypedDict, total=False):
    category: Category
    text: str
    retryable: Retryable
    next_action: str


class VerifyDescriptor(TypedDict):
    operation: str
    args: dict[str, Any]
    expect: dict[str, Any]
    terminal: dict[str, Any]
    poll_interval_ms: int | None
    poll_budget_ms: int | None


class IdempotencyMeta(TypedDict):
    policy: IdempotencyKind
    header: str | None
    format: str | None
    persist_required: bool
    note: str | None


class PreviewLocal(TypedDict):
    mode: Literal["local"]


class PreviewHeader(TypedDict):
    mode: Literal["header"]
    header: str
    value: str


class PreviewEndpoint(TypedDict):
    mode: Literal["endpoint"]
    operation: str


class PreviewNone(TypedDict):
    mode: Literal["none"]


class ConfirmationMeta(TypedDict):
    summary_fields: list[str]
    message: str | None


class AgentMeta(TypedDict):
    safety: Safety
    idempotency: IdempotencyMeta
    preview: PreviewLocal | PreviewHeader | PreviewEndpoint | PreviewNone
    confirmation: ConfirmationMeta | None
    verify: VerifyDescriptor | None
    remediation: dict[str, RemediationEntry]
    remediation_note: str | None
    sensitive_response_fields: list[str]
    sensitive_request_fields: NotRequired[list[str]]
    shown_once: bool


class Issue(TypedDict):
    path: list[str | int]
    message: str
    code: NotRequired[str]


@dataclass(frozen=True, slots=True)
class Valid[T]:
    data: T
    ok: Literal[True] = True


@dataclass(frozen=True, slots=True)
class Invalid:
    issues: list[Issue]
    ok: Literal[False] = False


class Validator[T](Protocol):
    """What the runtime needs from a schema; the emitter implements it with
    Pydantic v2 ``TypeAdapter``s. For requests, ``Valid.data`` is the
    normalized args mapping keyed by argument name, with every value already
    JSON-ready (models dumped by alias, ``UNSET`` removed); binary values
    (bytes, file objects, ``(filename, content[, content_type])`` tuples)
    pass through untouched. The runtime removes ``UNSET`` mapping members
    (at any depth through mappings and lists) before validating, sends
    ``Valid.data``, and reports
    an ``Invalid`` issue's path (argument names) as ``args.<path>`` or
    ``body.<path>``. For responses, ``Valid.data`` is the typed value (a
    model instance) the caller receives."""

    def validate(self, value: object) -> Valid[T] | Invalid: ...


class RpcBinding(TypedDict):
    field: str
    value: str
    params_field: str
    constants: NotRequired[dict[str, Any]]


class ImplementedStatus(TypedDict):
    kind: Literal["implemented"]


class GatedStatus(TypedDict):
    kind: Literal["gated"]
    env_var: str
    disabled_status: int


class OperationDescriptor(TypedDict):
    id: str
    method: HttpMethod
    path: str
    params: list[ParamDescriptor]
    body: BodyDescriptor | None
    responses: list[ResponseDescriptor]
    security: list[list[str]]
    pagination: PaginationDescriptor | None
    rpc: RpcBinding | None
    error_code_field: str | None
    status: ImplementedStatus | GatedStatus
    agent: AgentMeta
    request: NotRequired[Validator[dict[str, Any]]]
    response: NotRequired[Validator[Any]]
    #: Paginated operations: the validator of one page item. ``pages()``
    #: yields each item as its ``Valid.data`` (with response validation on;
    #: an item that does not match stays as decoded), so ``Page[T].items``
    #: holds ``T`` without help from generated code.
    page_item: NotRequired[Validator[Any]]
    summary: NotRequired[str | None]


class ApiKeyScheme(TypedDict):
    kind: Literal["api_key"]
    name: str
    location: Literal["header", "query", "cookie"]
    wire: str


class BearerScheme(TypedDict):
    kind: Literal["http_bearer"]
    name: str
    prefix: str | None


class BasicScheme(TypedDict):
    kind: Literal["http_basic"]
    name: str


class OAuth2Scheme(TypedDict):
    kind: Literal["oauth2"]
    name: str
    token_url: str | None
    scopes: list[str]


class CookiePart(TypedDict):
    kind: Literal["cookie"]
    name: str


class HeaderPart(TypedDict):
    kind: Literal["header"]
    name: str
    equals_cookie: str | None
    from_config: str | None
    mutation_only: bool


class BearerPart(TypedDict):
    kind: Literal["bearer"]
    prefix: str | None


class CompositeScheme(TypedDict):
    kind: Literal["composite"]
    name: str
    satisfies: list[str]
    parts: list[CookiePart | HeaderPart | BearerPart]


AuthSchemeDescriptor = ApiKeyScheme | BearerScheme | BasicScheme | OAuth2Scheme | CompositeScheme


class NonJsonError(TypedDict):
    status: int
    media: str
    category: Category
    retryable: Retryable
    text: str | None


class RetryPolicy(TypedDict, total=False):
    max: int
    base_ms: int
    max_ms: int
    jitter: Literal["none", "full", "equal"]
    honor_retry_after: bool


class ApiRetries(TypedDict):
    read_only: RetryPolicy
    mutating: RetryPolicy


class ApiDescriptor(TypedDict):
    name: str
    version: str
    tungsten_version: str
    servers: list[str]
    auth: list[AuthSchemeDescriptor]
    error_codes: dict[str, RemediationEntry]
    ambiguous_statuses: list[int]
    non_json: list[NonJsonError]
    gates: dict[str, str]
    retries: NotRequired[ApiRetries]


# ----------------------------------------------------------------- macros


class MacroStep(TypedDict):
    kind: Literal["call", "poll", "paginate"]
    operation: str
    args: Any
    as_: str | None
    until: dict[str, Any] | None
    interval_ms: int | None
    budget_ms: Any
    max_pages: int | None


class MacroInput(TypedDict):
    extends: str | None
    add: dict[str, Any]


class MacroDescriptor(TypedDict):
    """Canonical macro form (planning/04); ``as_`` is the step's ``as`` name
    (``as`` is a Python keyword)."""

    name: str
    summary: str
    safety: Safety
    steps: list[MacroStep]
    output: Any
    input: MacroInput
    sensitive_response_fields: NotRequired[list[str]]
    shown_once: NotRequired[bool]
    cluster: NotRequired[str | None]


# ---------------------------------------------------------------- options

AuthConfig = Mapping[str, str | Mapping[str, str]]
"""Credentials per auth scheme name: a string secret for api_key / bearer /
basic (``user:password``), or a mapping keyed by cookie name or config key
for composite profiles (``bearer`` for a composite bearer part). An oauth2
scheme takes an access token, or ``{"client_id": ..., "client_secret": ...}``
to fetch client-credentials tokens from its token URL."""


class IdempotencyStore(Protocol):
    def get(self, scope: str, logical_id: str) -> str | None: ...
    def put(self, scope: str, logical_id: str, key: str) -> None: ...


class AsyncIdempotencyStore(Protocol):
    async def get(self, scope: str, logical_id: str) -> str | None: ...
    async def put(self, scope: str, logical_id: str, key: str) -> None: ...


@dataclass(slots=True)
class RequestContext:
    operation: OperationDescriptor
    attempt: int
    method: HttpMethod
    url: str
    headers: dict[str, str]
    body: bytes | None


class Middleware(Protocol):
    """All hooks optional; implement the ones you need. Hooks observe: their
    exceptions are ignored, and secrets are redacted in what they see
    (``RequestContext.headers`` and ``body``). Headers ``on_request`` adds or
    changes in ``ctx.headers`` (other than redacted ones) are sent.
    ``AsyncClientCore`` awaits a hook that returns an awaitable."""

    def on_request(self, ctx: RequestContext) -> None: ...
    def on_response(self, ctx: RequestContext, status: int, headers: Mapping[str, str]) -> None: ...
    def on_retry(self, ctx: RequestContext, reason: Diagnostic) -> None: ...


@dataclass(slots=True)
class RetryOptions:
    max: int = 2
    base_ms: int = 500
    max_ms: int = 8000
    jitter: Literal["none", "full", "equal"] = "full"
    honor_retry_after: bool = True


@dataclass(slots=True)
class ClientOptions:
    base_url: str | None = None
    auth: AuthConfig | None = None
    timeout_ms: int = 30_000
    #: Overrides the API's per-tier retry defaults (``ApiDescriptor.retries``)
    #: for every tier: a ``RetryPolicy`` mapping field by field, a
    #: ``RetryOptions`` instance as a whole.
    retries: RetryOptions | RetryPolicy | None = None
    idempotency_store: IdempotencyStore | AsyncIdempotencyStore | None = None
    middleware: Sequence[Middleware] = ()
    validate_responses: Literal["off", "warn", "strict"] = "warn"
    on_diagnostic: Callable[[Diagnostic], None] | None = None
    headers: Mapping[str, str] = field(default_factory=dict[str, str])
    confirmation_key: bytes | None = None
    operations: Sequence[OperationDescriptor] = ()
    macros: Sequence[MacroDescriptor] = ()
    #: Injected transport (``httpx.BaseTransport`` / ``httpx.AsyncBaseTransport``) for tests.
    transport: Any = None
    #: Clock in epoch milliseconds (token expiry, Retry-After dates).
    now: Callable[[], float] | None = None
    #: Random number in [0, 1) for retry jitter.
    random: Callable[[], float] | None = None


class CallOptions(TypedDict, total=False):
    idempotency_key: str
    #: Token from ``preview()``; required for irreversible, and for destructive unless ``True``.
    confirm: str | Literal[True]
    allow_confirm_true: bool
    timeout_ms: int
    verify: bool
    headers: Mapping[str, str]


# ---------------------------------------------------------------- results


class RenderedRequest(TypedDict):
    method: HttpMethod
    url: str
    headers: dict[str, str]
    body: Any


class MacroStepPreview(TypedDict):
    step: int
    kind: Literal["call", "poll", "paginate"]
    operation: str
    as_: str | None
    safety: Safety
    request: RenderedRequest | None
    effects: list[str]


class PreviewResult(TypedDict):
    operation: str
    safety: Safety
    request: RenderedRequest
    effects: list[str]
    confirmation_token: str | None
    expires_in_ms: int | None
    server_preview: NotRequired[Any]
    steps: NotRequired[list[MacroStepPreview]]


@dataclass(frozen=True, slots=True)
class Page[T]:
    """One page of a paginated operation. ``items`` are read from the page
    body at the pagination's ``items_field`` and validated with the
    operation's ``page_item`` validator (``OperationDescriptor``); ``body`` is
    the page's value as a call returns it; ``next`` is the next cursor, offset,
    page number or URL, None after the last page."""

    items: list[T]
    body: Any
    next: Any


Predicate = dict[str, Any]


__all__ = [
    "AgentMeta",
    "ApiDescriptor",
    "ApiKeyScheme",
    "ApiRetries",
    "ArgBodyShape",
    "AsyncIdempotencyStore",
    "AuthConfig",
    "AuthSchemeDescriptor",
    "BasicScheme",
    "BearerPart",
    "BearerScheme",
    "BodyDescriptor",
    "BodyEncoding",
    "CallOptions",
    "Category",
    "ClientOptions",
    "CompositeScheme",
    "ConfirmationMeta",
    "CookiePart",
    "CursorPagination",
    "Diagnostic",
    "Err",
    "GatedStatus",
    "HeaderPart",
    "HttpMethod",
    "IdempotencyKind",
    "IdempotencyMeta",
    "IdempotencyStore",
    "ImplementedStatus",
    "Invalid",
    "Issue",
    "LinkHeaderPagination",
    "MacroDescriptor",
    "MacroInput",
    "MacroStep",
    "MacroStepPreview",
    "MergedBodyField",
    "MergedBodyShape",
    "Middleware",
    "NonJsonError",
    "OAuth2Scheme",
    "OffsetPagination",
    "Ok",
    "OperationDescriptor",
    "Page",
    "PagePagination",
    "PaginationDescriptor",
    "ParamDescriptor",
    "ParamLocation",
    "ParamRole",
    "ParamStyle",
    "Predicate",
    "PreviewEndpoint",
    "PreviewHeader",
    "PreviewLocal",
    "PreviewNone",
    "PreviewResult",
    "RemediationEntry",
    "RenderedRequest",
    "RequestContext",
    "ResponseDescriptor",
    "ResponseMeta",
    "Result",
    "RetryOptions",
    "RetryPolicy",
    "Retryable",
    "RpcBinding",
    "Safety",
    "StatusMatch",
    "Trace",
    "Valid",
    "Validator",
    "Verification",
    "VerifyDescriptor",
]
