// SPDX-License-Identifier: Apache-2.0
//! `tungsten-runtime`: the runtime of Rust SDKs generated by tungsten.
//!
//! A generated SDK is mostly data plus thin typed wrappers; everything with
//! behaviour lives here, so every operation of every generated client
//! behaves the same way and the same way as `@tungsten/runtime` (TypeScript)
//! and the Python `tungsten-runtime`.
//!
//! # What the runtime does
//!
//! [`ClientCore`] runs each call through one pipeline: pre-flight validation
//! of the arguments, auth resolution, idempotency keys, confirmation rules
//! for destructive operations, sending with tier-aware retries, and
//! classification of the response (or of a lost request) into a result or
//! the diagnostic error envelope. On top of that it provides previews with
//! confirmation tokens, verification hooks, pagination and macros
//! (multi-step workflows).
//!
//! # Main types
//!
//! - [`types`] is the contract with generated code: an [`ApiDescriptor`]
//!   (servers, auth schemes, error policy) and one [`OperationDescriptor`]
//!   per operation (parameters, body, responses, pagination and the agent
//!   metadata: safety tier, idempotency, preview, verification).
//! - [`ClientOptions`] configures a client (base URL, credentials, retries,
//!   middleware, idempotency store) and [`CallOptions`] one call (timeout,
//!   idempotency key, [`Confirm`], verification).
//! - [`Dispatch`] is implemented by generated clients so that the CLI kit
//!   and tool servers can invoke any operation by id with a JSON arguments
//!   object; [`decode`] and [`decode_page`] turn an outcome into typed
//!   results.
//! - Failures are [`Error`] values that carry the [`Diagnostic`] envelope: a
//!   stable category, a retryable flag, remediation text and a trace.
//!   [`Patch`] and [`Binary`] represent fields that can be absent, `null` or
//!   a value, and binary payloads.
//! - [`MemoryIdempotencyStore`] and [`FileIdempotencyStore`] keep
//!   idempotency keys across retries (and, for the file store, across
//!   processes).
//!
//! # Usage
//!
//! Application code normally uses the generated crate, not this one:
//!
//! ```text
//! let client = AcmeClient::new(ClientOptions { auth, ..Default::default() })?;
//! let widget = client.widgets().create(request, &CallOptions::default()).await?;
//! ```
//!
//! A `destructive` or `irreversible` operation fails with a
//! `CONFIRMATION_REQUIRED` envelope unless the call is confirmed: `preview()`
//! renders the request and its effects and issues a confirmation token bound
//! to the exact arguments, and the call then passes `Confirm::Token` (or
//! `Confirm::Yes`, for `destructive` operations only).
//!
//! Stability: [`types`] is shared by the runtime, the Rust SDK emitter and
//! the CLI kit. Changes are additive.

mod auth;
pub mod b64;
pub mod blocking;
mod classify;
mod client;
mod confirm;
mod dispatch;
mod envelope;
mod expr;
mod helpers;
mod idempotency;
mod macros;
mod pages;
mod prepare;
mod preview;
mod send;
mod serialize;
mod sse;
mod stream;
mod transport;
mod util;
mod validate;
mod value;
mod verify;

pub mod types;

pub use client::{ClientCore, ConfigError, Pages, Polled, TypedPages};
pub use dispatch::{
    ByStatus, Dispatch, Mismatch, StatusDecode, decode, decode_by_status, decode_event,
    decode_page, decode_variant, no_stream,
};
pub use idempotency::{FileIdempotencyStore, MemoryIdempotencyStore};
pub use stream::{
    DEFAULT_MAX_COLLECT_BYTES, DEFAULT_MAX_COLLECT_TIME, EventStream, StreamEvent, StreamResult,
    TypedEvents,
};
pub use types::*;
pub use value::{BINARY_KEY, Binary, Patch};

/// Version of this runtime, sent as `X-Tungsten-Runtime: tungsten-rs/<version>`.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Pure building blocks of the runtime (canonical JSON, digests, tokens,
/// parameter and body encoding, predicates, response decoding), exposed for
/// cross-runtime parity checks. Not part of the stable API.
#[doc(hidden)]
pub mod internals {
    pub use crate::classify::{DecodedBody, decode_body};
    pub use crate::confirm::{
        CONFIRMATION_TTL_MS, TokenCheck, args_digest, check_token, issue_token, token_payload,
    };
    pub use crate::envelope::{default_retryable, generic_remediation};
    pub use crate::expr::{
        describe_predicate, evaluate_dry, evaluate_expr, evaluate_predicate, resolve_ref,
    };
    pub use crate::idempotency::{check_key_format, key_format_description};
    pub use crate::serialize::{
        EncodedBody, Payload, encode_body, serialize_cookie_param, serialize_header_param,
        serialize_path_param, serialize_query_param,
    };
    pub use crate::sse::{DEFAULT_MAX_EVENT_BYTES, SseEvent, SseParser, Utf8Decoder};
    pub use crate::transport::{next_link, parse_http_date, parse_retry_after};
    pub use crate::util::{canonical_json, envelope_value, js_number, json_text, sha256_hex};
}
