// SPDX-License-Identifier: Apache-2.0
//! `tungsten-runtime`: the runtime of Rust SDKs generated by tungsten.
//!
//! [`types`] is the contract with generated code (PHASE-5 CONTRACT);
//! [`ClientCore`] implements the behaviour: pre-flight validation, auth,
//! idempotency, tier-aware retries, classification into the diagnostic
//! envelope, previews and confirmation tokens, verification, pagination and
//! macros, with the same semantics as `@tungsten/runtime` and the Python
//! `tungsten-runtime`.

pub mod b64;
mod client;
mod dispatch;
mod idempotency;
mod value;

pub mod types;

pub use client::{ClientCore, ConfigError, Pages, Polled, TypedPages};
pub use dispatch::{Dispatch, decode, decode_page};
pub use idempotency::{FileIdempotencyStore, MemoryIdempotencyStore};
pub use types::*;
pub use value::{Binary, Patch};

/// Version of this runtime, sent as `X-Tungsten-Runtime: tungsten-rs/<version>`.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
