// SPDX-License-Identifier: Apache-2.0
//! The contract between Rust SDKs generated by tungsten and this runtime
//! (planning/05 "Rust SDK and CLI", planning/06 "Runtime and safety").
//!
//! It mirrors `runtimes/ts/src/types.ts` and `runtimes/python/.../types.py`
//! with Rust conventions: descriptor fields are snake_case, closed sets are
//! enums, JSON that the runtime does not interpret is `serde_json::Value`
//! (with `preserve_order`, so object members keep their insertion order),
//! and durations are `std::time::Duration`. The diagnostic envelope
//! serializes to exactly the fourteen fields of `specs/envelope.schema.json`,
//! in order, so it is identical across the TypeScript, Python and Rust
//! runtimes.
//!
//! Generated code is mostly data: one [`OperationDescriptor`] per operation,
//! one [`ApiDescriptor`] per client, and typed wrappers that serialize a
//! request struct to the *arguments object* (a JSON object keyed by argument
//! name), call [`crate::ClientCore`] and decode the body into the response
//! type. Everything with behaviour lives in the runtime.
//!
//! PHASE-5 CONTRACT: these types are shared by the runtime, the Rust SDK
//! emitter and the CLI kit. Additive changes only (new optional fields, new
//! enum variants where the enum is `#[non_exhaustive]`), and only with every
//! side updated.

use std::collections::BTreeMap;
use std::fmt;
use std::sync::Arc;
use std::time::Duration;

use serde::{Deserialize, Serialize};
use serde_json::Value;

// ---------------------------------------------------------------- errors

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Safety {
    ReadOnly,
    Mutating,
    Destructive,
    Irreversible,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Retryable {
    Never,
    AfterDelay,
    SameKeyOnly,
    AfterRemediation,
}

/// Closed set of error categories shared by every tungsten runtime.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Category {
    ValidationFailed,
    MalformedRequest,
    RequestTooLarge,
    AuthFailed,
    NotFound,
    Conflict,
    PreconditionFailed,
    RateLimited,
    UpstreamUnavailable,
    OutcomeUnknown,
    TransportFailed,
    ConfirmationRequired,
    GateDisabled,
    UnexpectedResponse,
}

/// The `status` member of the envelope: always `"error"`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum Status {
    #[default]
    #[serde(rename = "error")]
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct Trace {
    pub attempts: u32,
}

/// The diagnostic error envelope (planning/06). Field order is the wire
/// order of `specs/envelope.schema.json`; every field is always present
/// (`null` when it has no value).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Diagnostic {
    pub status: Status,
    pub category: Category,
    /// Operation id, e.g. `public.replayWebhookDelivery`.
    pub operation: String,
    pub http_status: Option<u16>,
    /// The API's error code from the response body, when present.
    pub code: Option<String>,
    /// JSON path of the offending argument (`body.recipient_e164`), in the
    /// Rust spelling of argument names (`args.endpoint_id`).
    pub failed_parameter: Option<String>,
    /// Redacted when the parameter is sensitive; strings cut to 200 chars.
    pub received_value: Value,
    pub expected: Option<String>,
    pub remediation: String,
    pub retryable: Retryable,
    pub retry_after_ms: Option<u64>,
    /// What to do next, e.g. the verification operation to call.
    pub next_action: Option<String>,
    pub request_id: Option<String>,
    pub trace: Trace,
}

impl fmt::Display for Diagnostic {
    /// `<category> in <operation>: <remediation>`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let category = serde_json::to_value(self.category).ok();
        let category = category.as_ref().and_then(Value::as_str).unwrap_or("ERROR");
        write!(f, "{category} in {}: {}", self.operation, self.remediation)
    }
}

impl std::error::Error for Diagnostic {}

/// A failed call: the envelope, plus what the failed call or macro already
/// produced when its effect happened (the success body of a mutation whose
/// response failed strict validation, or a macro's completed step results by
/// their `as` names). `partial` can hold values the API shows only once (a
/// signing secret), so store them before acting on the error; they are never
/// repeated in the envelope. Boxed members keep `Result<_, Error>` small.
#[derive(Clone, PartialEq)]
pub struct Error {
    pub diagnostic: Box<Diagnostic>,
    pub partial: Option<Box<Value>>,
}

impl fmt::Debug for Error {
    /// The envelope; `partial` is never printed (it can hold a secret).
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Error")
            .field("diagnostic", &self.diagnostic)
            .field(
                "partial",
                &self.partial.as_ref().map(|_| "<kept, not shown>"),
            )
            .finish()
    }
}

impl Error {
    pub fn new(diagnostic: Diagnostic) -> Self {
        Error {
            diagnostic: Box::new(diagnostic),
            partial: None,
        }
    }

    pub fn with_partial(diagnostic: Diagnostic, partial: Value) -> Self {
        Error {
            diagnostic: Box::new(diagnostic),
            partial: Some(Box::new(partial)),
        }
    }
}

impl std::ops::Deref for Error {
    type Target = Diagnostic;
    fn deref(&self) -> &Diagnostic {
        &self.diagnostic
    }
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.diagnostic.fmt(f)
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        Some(&*self.diagnostic)
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ResponseMeta {
    pub status: u16,
    /// Response headers with lower-cased names (last value wins).
    pub headers: BTreeMap<String, String>,
    pub request_id: Option<String>,
    pub attempts: u32,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Verification {
    pub checked: bool,
    /// True when `expect` held; false when it did not within the budget.
    pub passed: bool,
    /// The verification operation's last result body.
    pub observed: Option<Value>,
    /// True when polling for `terminal` ran out of budget.
    pub timed_out: bool,
    /// Why the check could not run (the verification call failed);
    /// `checked` is false.
    pub error: Option<Box<Diagnostic>>,
}

/// A successful call. A success without a body (204, or any success status
/// the spec declares without content) has `value: None` at the dynamic
/// level ([`Outcome`]); typed wrappers decode it into `()`.
#[derive(Debug, Clone, PartialEq)]
pub struct Response<T> {
    pub value: T,
    pub meta: ResponseMeta,
    pub verification: Option<Verification>,
}

/// The outcome of a typed call.
pub type Result<T> = std::result::Result<Response<T>, Error>;

/// The outcome of a dynamic call: the decoded JSON body, `None` when the
/// response had none.
pub type Outcome = Result<Option<Value>>;

// ----------------------------------------------------------- descriptors

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum HttpMethod {
    Get,
    Put,
    Post,
    Delete,
    Options,
    Head,
    Patch,
    Trace,
}

impl HttpMethod {
    pub fn as_str(self) -> &'static str {
        match self {
            HttpMethod::Get => "GET",
            HttpMethod::Put => "PUT",
            HttpMethod::Post => "POST",
            HttpMethod::Delete => "DELETE",
            HttpMethod::Options => "OPTIONS",
            HttpMethod::Head => "HEAD",
            HttpMethod::Patch => "PATCH",
            HttpMethod::Trace => "TRACE",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamLocation {
    Path,
    Query,
    Header,
    Cookie,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamStyle {
    Simple,
    Form,
    Label,
    Matrix,
    SpaceDelimited,
    PipeDelimited,
    DeepObject,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamRole {
    Plain,
    IdempotencyKey,
    DryRun,
    Origin,
    Auth,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ParamDescriptor {
    /// Key in the arguments object (the Rust field name of the request
    /// struct). Roles `IdempotencyKey`, `Origin` and `Auth` are not
    /// arguments: they come from [`CallOptions::idempotency_key`] and the
    /// auth profile ([`ClientOptions::auth`]); their `name` is informational.
    pub name: String,
    /// Name on the wire.
    pub wire: String,
    pub location: ParamLocation,
    pub required: bool,
    pub style: ParamStyle,
    pub explode: bool,
    pub role: ParamRole,
    pub sensitive: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BodyEncoding {
    Json,
    Form,
    Multipart,
    Bytes,
    Text,
}

/// One field of a merged body: the key in the arguments object and the
/// name on the wire.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MergedBodyField {
    pub arg: String,
    pub wire: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum BodyShape {
    /// The body is a JSON object whose fields are keys of the arguments
    /// object (listed in `fields`, in wire order).
    Merged { fields: Vec<MergedBodyField> },
    /// The whole body is `args[arg]` (bytes, text, unions, arrays, or field
    /// names that collide with a parameter).
    Arg { arg: String },
}

#[derive(Debug, Clone, PartialEq)]
pub struct BodyDescriptor {
    pub media_type: String,
    pub encoding: BodyEncoding,
    pub required: bool,
    pub shape: BodyShape,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StatusMatch {
    Exact(u16),
    /// `1XX` to `5XX`: the hundreds digit.
    Class(u8),
    Default,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ResponseKind {
    Success,
    Error,
    Ambiguous,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ResponseDescriptor {
    pub status: StatusMatch,
    pub kind: ResponseKind,
    /// First media type, or `None` for a bare status.
    pub media_type: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum PaginationDescriptor {
    Cursor {
        request_param: String,
        response_field: String,
        items_field: String,
        page_size_param: Option<String>,
    },
    Offset {
        offset_param: String,
        limit_param: String,
        items_field: String,
    },
    Page {
        page_param: String,
        size_param: String,
        items_field: String,
    },
    LinkHeader {
        items_field: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IdempotencyKind {
    None,
    Auto,
    CallerOwned,
    ContentHash,
    ContentIdentity,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RemediationEntry {
    pub category: Option<Category>,
    pub text: Option<String>,
    pub retryable: Option<Retryable>,
    pub next_action: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct VerifyDescriptor {
    /// Operation id of the read operation to call.
    pub operation: String,
    /// Argument mapping, keyed by the read operation's parameter wire names
    /// (or argument names); string values starting with `$response.` or
    /// `$args.` are resolved against the call, `$args` by argument or wire
    /// name.
    pub args: Value,
    /// Field path → predicate (`{"in": [...]}`, `{"equals": x}`,
    /// `{"contains": {...}}`); `$response.` and `$args.` references are
    /// resolved against the call; an unresolved one never matches.
    pub expect: Value,
    pub terminal: Value,
    pub poll_interval: Option<Duration>,
    pub poll_budget: Option<Duration>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct IdempotencyMeta {
    pub policy: IdempotencyKind,
    pub header: Option<String>,
    pub format: Option<String>,
    pub persist_required: bool,
    pub note: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum PreviewMode {
    Local,
    Header { header: String, value: String },
    Endpoint { operation: String },
    None,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ConfirmationMeta {
    pub summary_fields: Vec<String>,
    pub message: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct AgentMeta {
    pub safety: Safety,
    pub idempotency: IdempotencyMeta,
    pub preview: PreviewMode,
    pub confirmation: Option<ConfirmationMeta>,
    pub verify: Option<VerifyDescriptor>,
    /// Operation-specific remediation by API error code.
    pub remediation: BTreeMap<String, RemediationEntry>,
    pub remediation_note: Option<String>,
    pub sensitive_response_fields: Vec<String>,
    /// Arguments marked sensitive, as dotted paths into the arguments
    /// object (`pin`, `body.pin`); array items are not indexed. Redacted in
    /// `received_value`, previews, middleware and diagnostics.
    pub sensitive_request_fields: Vec<String>,
    pub shown_once: bool,
}

/// One validation problem: the path of the offending value and a message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Issue {
    pub path: Vec<PathSegment>,
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PathSegment {
    Key(String),
    Index(usize),
}

#[derive(Debug, Clone, PartialEq)]
pub enum Validation {
    /// Request validators: the normalized, JSON-ready arguments object (keys
    /// are argument names; absent optionals are not keys; binary values are
    /// the [`crate::Binary`] form). Response and page-item validators: the
    /// value that was checked (the runtime keeps the decoded wire body, not
    /// this value).
    Valid(Value),
    Invalid(Vec<Issue>),
}

/// Validates a value before any network call (requests) or after the
/// response (bodies, page items). Generated code implements it by
/// deserializing into the generated type with `serde_path_to_error` and
/// running the type's constraint checks, so issue paths are exact.
pub trait Validator: Send + Sync + fmt::Debug {
    fn validate(&self, value: &Value) -> Validation;
}

#[derive(Debug, Clone, PartialEq)]
pub enum OperationStatus {
    Implemented,
    Gated {
        env_var: String,
        disabled_status: u16,
    },
}

/// For rpc-unflattened operations: the envelope field and value to send and
/// the field the arguments go under; `constants` are further envelope
/// members sent verbatim (JSON-RPC `jsonrpc: "2.0"`).
#[derive(Debug, Clone, PartialEq)]
pub struct RpcDescriptor {
    pub field: String,
    pub value: String,
    pub params_field: String,
    pub constants: BTreeMap<String, Value>,
}

#[derive(Debug, Clone)]
pub struct OperationDescriptor {
    /// IR operation id (`public.replayWebhookDelivery`).
    pub id: String,
    pub method: HttpMethod,
    /// Path template as in the spec (`/v1/webhooks/{endpoint_id}/rotate`);
    /// placeholders use wire names.
    pub path: String,
    pub params: Vec<ParamDescriptor>,
    pub body: Option<BodyDescriptor>,
    pub responses: Vec<ResponseDescriptor>,
    /// OR of AND-sets of auth scheme names. Empty: no auth.
    pub security: Vec<Vec<String>>,
    pub pagination: Option<PaginationDescriptor>,
    pub rpc: Option<RpcDescriptor>,
    /// Field path of the API error code in error bodies (`code`, `error.code`).
    pub error_code_field: Option<String>,
    pub status: OperationStatus,
    pub agent: AgentMeta,
    /// Validates the arguments object before any network call.
    pub request: Option<Arc<dyn Validator>>,
    /// Validates the success body (per [`ClientOptions::validate_responses`]).
    /// The result's value is always the decoded wire body itself, never a
    /// re-serialization, so an untagged-union variant that strips unknown
    /// members cannot drop or rewrite members of the body.
    pub response: Option<Arc<dyn Validator>>,
    /// Types each item of a page (`pages`) when response validation is on.
    pub page_item: Option<Arc<dyn Validator>>,
    /// One-line summary (compacted description); the last line of preview effects.
    pub summary: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApiKeyLocation {
    Header,
    Query,
    Cookie,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CompositePart {
    Cookie {
        name: String,
    },
    Header {
        name: String,
        equals_cookie: Option<String>,
        from_config: Option<String>,
        mutation_only: bool,
    },
    Bearer {
        prefix: Option<String>,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum AuthSchemeDescriptor {
    ApiKey {
        name: String,
        location: ApiKeyLocation,
        wire: String,
    },
    /// `prefix`: the token must start with it (tungsten.yml
    /// `auth_profiles.<name>.bearer.prefix`, e.g. `ztw_`); checked before
    /// any request is sent, and a mismatch is `AuthFailed` with zero network
    /// calls.
    HttpBearer {
        name: String,
        prefix: Option<String>,
    },
    HttpBasic {
        name: String,
    },
    Oauth2 {
        name: String,
        token_url: Option<String>,
        scopes: Vec<String>,
    },
    Composite {
        name: String,
        satisfies: Vec<String>,
        parts: Vec<CompositePart>,
    },
}

impl AuthSchemeDescriptor {
    pub fn name(&self) -> &str {
        match self {
            AuthSchemeDescriptor::ApiKey { name, .. }
            | AuthSchemeDescriptor::HttpBearer { name, .. }
            | AuthSchemeDescriptor::HttpBasic { name }
            | AuthSchemeDescriptor::Oauth2 { name, .. }
            | AuthSchemeDescriptor::Composite { name, .. } => name,
        }
    }
}

/// Non-JSON error mapping (agent.yml `errors.non_json`).
#[derive(Debug, Clone, PartialEq)]
pub struct NonJsonError {
    pub status: u16,
    /// A media type, or `"none"` for a bare status.
    pub media: String,
    pub category: Category,
    pub retryable: Retryable,
    pub text: Option<String>,
}

/// Retry defaults by safety tier (agent.yml `defaults.retries`):
/// `read_only` for read-only operations, `mutating` for every other tier (a
/// mutation is still retried only with an idempotency key or an identity
/// body).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct TierRetries {
    pub read_only: PartialRetryOptions,
    pub mutating: PartialRetryOptions,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ApiDescriptor {
    /// Machine name (`zrotext`).
    pub name: String,
    /// SDK package version.
    pub version: String,
    pub tungsten_version: String,
    pub servers: Vec<String>,
    pub auth: Vec<AuthSchemeDescriptor>,
    /// Global remediation by API error code (agent.yml `errors.codes`).
    pub error_codes: BTreeMap<String, RemediationEntry>,
    /// Statuses that make a mutation's outcome unknown.
    pub ambiguous_statuses: Vec<u16>,
    pub non_json: Vec<NonJsonError>,
    /// Runtime gate env var → explanation.
    pub gates: BTreeMap<String, String>,
    /// Absent: the runtime defaults apply to every tier.
    pub retries: Option<TierRetries>,
}

// --------------------------------------------------------------- options

/// Credentials of one auth scheme: a secret string for `api_key`,
/// `http_bearer` and `http_basic` (`user:password`) schemes, a map keyed by
/// cookie name or config key for a composite profile.
#[derive(Clone, PartialEq)]
pub enum Credential {
    Secret(String),
    Parts(BTreeMap<String, String>),
}

impl fmt::Debug for Credential {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Credential::Secret(_) => f.write_str("Credential::Secret(<redacted>)"),
            Credential::Parts(parts) => {
                write!(f, "Credential::Parts({} parts, <redacted>)", parts.len())
            }
        }
    }
}

/// Credentials per auth scheme name.
pub type AuthConfig = BTreeMap<String, Credential>;

/// Remembers the key used for one logical intent so a retry reuses it.
/// Methods are synchronous: the shipped stores are in memory and on disk.
pub trait IdempotencyStore: Send + Sync + fmt::Debug {
    fn get(&self, scope: &str, logical_id: &str) -> Option<String>;
    fn put(&self, scope: &str, logical_id: &str, key: &str);
}

/// What middleware sees of one attempt. Secrets are redacted: secret
/// headers, auth query values, and in a JSON or form body the arguments
/// marked sensitive (or named like credentials) as `<redacted>`.
#[derive(Debug, Clone)]
pub struct RequestContext {
    pub operation: String,
    pub attempt: u32,
    pub method: HttpMethod,
    pub url: String,
    pub headers: BTreeMap<String, String>,
    /// The body as JSON when it is JSON, a text rendering otherwise.
    pub body: Option<Value>,
}

#[derive(Debug, Clone)]
pub struct ResponseContext {
    pub status: u16,
    pub headers: BTreeMap<String, String>,
}

/// Observers of the request lifecycle. Hooks are synchronous and must not
/// block; a panicking hook is not caught.
pub trait Middleware: Send + Sync + fmt::Debug {
    fn on_request(&self, _ctx: &RequestContext) {}
    fn on_response(&self, _ctx: &RequestContext, _response: &ResponseContext) {}
    fn on_retry(&self, _ctx: &RequestContext, _reason: &Diagnostic) {}
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Jitter {
    None,
    Full,
    Equal,
}

#[derive(Debug, Clone, PartialEq)]
pub struct RetryOptions {
    /// Attempts after the first, for retryable outcomes.
    pub max: u32,
    pub base: Duration,
    pub max_delay: Duration,
    pub jitter: Jitter,
    pub honor_retry_after: bool,
}

/// An override of [`RetryOptions`], field by field.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PartialRetryOptions {
    pub max: Option<u32>,
    pub base: Option<Duration>,
    pub max_delay: Option<Duration>,
    pub jitter: Option<Jitter>,
    pub honor_retry_after: Option<bool>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ValidateResponses {
    Off,
    /// Report through `on_diagnostic`, never fail the call.
    #[default]
    Warn,
    Strict,
}

/// Receives warnings (response validation, deprecations).
pub type DiagnosticSink = Arc<dyn Fn(&Diagnostic) + Send + Sync>;

#[derive(Clone)]
pub struct ClientOptions {
    /// Defaults to the first server.
    pub base_url: Option<String>,
    pub auth: AuthConfig,
    /// Per-attempt timeout. Default 30 s.
    pub timeout: Duration,
    /// Overrides the API's per-tier retry defaults field by field, for every tier.
    pub retries: PartialRetryOptions,
    pub idempotency_store: Option<Arc<dyn IdempotencyStore>>,
    pub middleware: Vec<Arc<dyn Middleware>>,
    pub validate_responses: ValidateResponses,
    pub on_diagnostic: Option<DiagnosticSink>,
    /// Extra headers on every request.
    pub headers: BTreeMap<String, String>,
    /// Overrides the key used to sign confirmation tokens. Default: random
    /// per client instance.
    pub confirmation_key: Option<Vec<u8>>,
    /// Operations the core can resolve by id: verification hooks, endpoint
    /// previews and macro steps.
    pub operations: Vec<Arc<OperationDescriptor>>,
    /// Use this HTTP client (proxies, TLS roots); default: a new one. It must
    /// not follow redirects (`reqwest::redirect::Policy::none()`): the runtime
    /// follows same-origin redirects of reads itself and never on mutations,
    /// and a client that follows them would forward credentials.
    pub http_client: Option<reqwest::Client>,
    /// Clock in epoch milliseconds (token expiry, Retry-After dates).
    pub now: Option<Arc<dyn Fn() -> u64 + Send + Sync>>,
    /// Random number in [0, 1) for retry jitter.
    pub random: Option<Arc<dyn Fn() -> f64 + Send + Sync>>,
}

impl Default for ClientOptions {
    fn default() -> Self {
        ClientOptions {
            base_url: None,
            auth: AuthConfig::new(),
            timeout: Duration::from_secs(30),
            retries: PartialRetryOptions::default(),
            idempotency_store: None,
            middleware: Vec::new(),
            validate_responses: ValidateResponses::default(),
            on_diagnostic: None,
            headers: BTreeMap::new(),
            confirmation_key: None,
            operations: Vec::new(),
            http_client: None,
            now: None,
            random: None,
        }
    }
}

impl fmt::Debug for ClientOptions {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ClientOptions")
            .field("base_url", &self.base_url)
            .field("auth", &self.auth)
            .field("timeout", &self.timeout)
            .field("validate_responses", &self.validate_responses)
            .finish_non_exhaustive()
    }
}

/// How a destructive or irreversible operation is confirmed.
#[derive(Clone, PartialEq, Eq)]
pub enum Confirm {
    /// A token from `preview()`, bound to the operation and the exact arguments.
    Token(String),
    /// Accepts a destructive (never an irreversible) operation without a token.
    Yes,
}

impl fmt::Debug for Confirm {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Confirm::Token(_) => f.write_str("Confirm::Token(<redacted>)"),
            Confirm::Yes => f.write_str("Confirm::Yes"),
        }
    }
}

#[derive(Clone)]
pub struct CallOptions {
    /// Required for `caller_owned` operations with `persist_required`.
    pub idempotency_key: Option<String>,
    /// A token authorizes one intent: the first call that sends spends it,
    /// and it is accepted again only for a retry with the same idempotency
    /// key (or the identical body of a `content_identity` operation).
    pub confirm: Option<Confirm>,
    /// `false`: `Confirm::Yes` does not confirm a destructive operation
    /// either, and remediation never offers it (callers that only forward
    /// preview tokens, such as an MCP server). Default `true`.
    pub allow_confirm_true: bool,
    /// Per-attempt timeout; default: the client's.
    pub timeout: Option<Duration>,
    /// Run the operation's verification hook after success.
    pub verify: bool,
    pub headers: BTreeMap<String, String>,
}

impl fmt::Debug for CallOptions {
    /// Keys and tokens are never printed; headers show their names only.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CallOptions")
            .field(
                "idempotency_key",
                &self.idempotency_key.as_ref().map(|_| "<redacted>"),
            )
            .field("confirm", &self.confirm)
            .field("allow_confirm_true", &self.allow_confirm_true)
            .field("timeout", &self.timeout)
            .field("verify", &self.verify)
            .field("headers", &self.headers.keys().collect::<Vec<_>>())
            .finish()
    }
}

impl Default for CallOptions {
    fn default() -> Self {
        CallOptions {
            idempotency_key: None,
            confirm: None,
            allow_confirm_true: true,
            timeout: None,
            verify: false,
            headers: BTreeMap::new(),
        }
    }
}

// --------------------------------------------------------------- results

#[derive(Debug, Clone, PartialEq)]
pub struct RenderedRequest {
    pub method: HttpMethod,
    pub url: String,
    /// Secrets redacted as `<redacted>`.
    pub headers: BTreeMap<String, String>,
    pub body: Value,
}

/// One step of a macro preview (`ClientCore::preview_macro`).
#[derive(Debug, Clone, PartialEq)]
pub struct MacroStepPreview {
    /// 1-based position in the macro.
    pub step: u32,
    pub kind: MacroStepKind,
    pub operation: String,
    pub r#as: Option<String>,
    pub safety: Safety,
    /// The request the step sends, rendered without sending anything;
    /// arguments from an earlier result show as `<from step NAME: path>`.
    /// `None` when the step's whole argument object (or a bytes or
    /// multipart body) comes from an earlier result.
    pub request: Option<RenderedRequest>,
    pub effects: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct PreviewResult {
    pub operation: String,
    pub safety: Safety,
    /// For a macro: the first step's request (also `steps[0].request`).
    pub request: RenderedRequest,
    /// Side-effect summary from the manifest's confirmation message, the
    /// remediation note and the operation's summary.
    pub effects: Vec<String>,
    /// Present for mutating operations; bound to the exact arguments.
    pub confirmation_token: Option<String>,
    pub expires_in_ms: Option<u64>,
    /// For `header`/`endpoint` previews: the server's answer.
    pub server_preview: Option<Value>,
    /// Macro previews only, in order.
    pub steps: Option<Vec<MacroStepPreview>>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Page<T> {
    pub items: Vec<T>,
    /// The full page body.
    pub body: Value,
    /// Cursor, offset, page number or URL for the next page; `None` at the end.
    pub next: Option<Value>,
}

/// Until-predicate for `ClientCore::poll`, same shape as
/// [`VerifyDescriptor::expect`].
pub type Predicate = Value;

// ---------------------------------------------------------------- macros

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MacroStepKind {
    Call,
    Poll,
    Paginate,
}

/// One macro step in the canonical form (`tungsten_ir::Macro.steps`).
/// `args`, `budget_ms` and the macro output are expressions: strings
/// starting with `$` reference `$input` or an earlier step's `as` name,
/// `{"expr": "<ref> in [..]" | "<ref> == x" | "<ref> != x"}` is a boolean,
/// anything else a literal.
#[derive(Debug, Clone, PartialEq)]
pub struct MacroStep {
    pub kind: MacroStepKind,
    /// Operation id, resolved among the operations registered with the core.
    pub operation: String,
    pub args: Value,
    pub r#as: Option<String>,
    /// `poll` only: predicate on the step's success body. When the budget
    /// runs out before it holds, the step's `as` name is bound to `null`.
    pub until: Option<Predicate>,
    pub interval_ms: Option<u64>,
    pub budget_ms: Value,
    /// `paginate` only: page limit.
    pub max_pages: Option<u32>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MacroInput {
    pub extends: Option<String>,
    /// Added fields by name (JSON Schema fragments; a `default` applies when
    /// the input omits the field).
    pub add: BTreeMap<String, Value>,
}

/// A compiled macro (`tungsten_ir::Macro`). Confirmation is macro-level
/// exactly as in the TypeScript runtime (`MacroDescriptor`).
#[derive(Debug, Clone, PartialEq)]
pub struct MacroDescriptor {
    pub name: String,
    pub summary: String,
    pub safety: Safety,
    pub steps: Vec<MacroStep>,
    pub output: Value,
    pub input: MacroInput,
    /// Output fields carrying secrets (dotted paths); redacted in traces.
    pub sensitive_response_fields: Vec<String>,
    /// The output holds values the API returns only once.
    pub shown_once: bool,
    /// Disclosure cluster (agent.yml `disclosure.clusters`).
    pub cluster: Option<String>,
}
