// SPDX-License-Identifier: AGPL-3.0-only
//! Package files: the workspace `Cargo.toml` and `README.md`, the SDK
//! crate's `Cargo.toml`, `lib.rs`, the shared helpers module and the
//! hand-editable `custom/mod.rs`.

use std::collections::BTreeSet;

use tungsten_emit::Writer;
use tungsten_ir::{AuthScheme, CompositePart, IdempotencyKind, Safety};

use super::ops::{OpShape, has_preview, safety_str};
use super::plan::{MemberKind, Plan};
use super::rs::string_lit;
use crate::options::{Dep, Options};

/// The oldest compiler the generated code builds with (let chains).
const RUST_VERSION: &str = "1.88";

/// A TOML basic string (JSON string escapes are valid TOML escapes).
fn toml_str(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".to_string())
}

fn dep(dep: &Dep) -> String {
    match dep {
        Dep::Version(v) => toml_str(v),
        Dep::Path(p) => format!("{{ path = {} }}", toml_str(p)),
    }
}

/// The workspace manifest: the SDK crate, and the CLI crate when enabled.
pub(crate) fn workspace_toml(opts: &Options, header: &str) -> String {
    let mut members = vec![toml_str(&opts.package)];
    if let Some(cli) = &opts.cli {
        members.push(toml_str(&cli.package));
    }
    format!(
        "{header}\n\n[workspace]\nresolver = \"3\"\nmembers = [{}]\n\n[workspace.package]\nversion = {}\nedition = \"2024\"\nrust-version = \"{RUST_VERSION}\"\n",
        members.join(", "),
        toml_str(&opts.version),
    )
}

/// The SDK crate's manifest.
pub(crate) fn sdk_toml(plan: &Plan<'_>, opts: &Options, header: &str) -> String {
    let mut out = String::new();
    out.push_str(header);
    out.push_str("\n\n[package]\n");
    out.push_str(&format!("name = {}\n", toml_str(&opts.package)));
    out.push_str(
        "version.workspace = true\nedition.workspace = true\nrust-version.workspace = true\n",
    );
    out.push_str(&format!(
        "description = {}\n",
        toml_str(&format!(
            "Rust SDK for the {} API, generated by tungsten.",
            tungsten_ir::title_stem(&plan.ir.api.title).replace('\n', " ")
        ))
    ));
    out.push_str("\n[lib]\ndoctest = false\n\n[dependencies]\n");
    out.push_str("regex = \"1\"\n");
    out.push_str("serde = { version = \"1\", features = [\"derive\"] }\n");
    out.push_str("serde_json = { version = \"1\", features = [\"preserve_order\"] }\n");
    out.push_str("serde_path_to_error = \"0.1\"\n");
    out.push_str(&format!("tungsten-runtime = {}\n", dep(&opts.runtime)));
    out.push_str("\n[lints.rust]\nunsafe_code = \"forbid\"\n\n");
    out.push_str("[lints.clippy]\n# Generated code mirrors the API description: wide constructors, long\n# unions and prose in doc comments are not defects.\n");
    for lint in CLIPPY_ALLOWED {
        out.push_str(&format!("{lint} = \"allow\"\n"));
    }
    out
}

/// Clippy lints the generated code does not follow on purpose.
const CLIPPY_ALLOWED: &[&str] = &[
    "doc_lazy_continuation",
    "enum_variant_names",
    "large_enum_variant",
    "module_inception",
    "ptr_arg",
    "too_many_arguments",
    "type_complexity",
];

/// The hand-editable template. Never overwritten once it exists.
pub(crate) fn custom_template() -> String {
    "//! Hand-written extensions of this SDK.\n//!\n//! tungsten creates this module once and never overwrites or deletes it (every\n//! path under a `custom/` directory is yours). It is exported as `custom`.\n"
        .to_string()
}

/// The source of `lib.rs`.
pub(crate) fn lib_file(plan: &Plan<'_>, has_macros: bool, header: &str) -> String {
    let ir = plan.ir;
    let mut w = Writer::new("    ");
    w.line(header);
    w.blank();
    w.line(format!(
        "//! Rust SDK for the {} API ({}), generated by tungsten.",
        tungsten_ir::title_stem(&ir.api.title).replace('\n', " "),
        ir.api.version
    ));
    w.line("//!");
    w.line(format!(
        "//! Create a [`{0}`] from [`ClientOptions`] and call its resources:",
        plan.client_class
    ));
    w.line("//! every call returns `tungsten_runtime::Result<T>` (the value with its response");
    w.line("//! metadata, or the diagnostic envelope) and never panics for API or transport");
    w.line("//! errors. See the README for authentication, idempotency, previews, pagination");
    w.line("//! and macros.");
    w.blank();
    let mut mods = vec![
        "client",
        "custom",
        "descriptors",
        "dispatch",
        "models",
        "resources",
        "support",
    ];
    if has_macros {
        mods.push("macros");
    }
    mods.sort_unstable();
    for m in mods {
        match m {
            "dispatch" => w.line("mod dispatch;"),
            "support" => {
                w.line("#[doc(hidden)]");
                w.line("pub mod support;")
            }
            other => w.line(format!("pub mod {other};")),
        };
    }
    w.blank();
    w.line(format!("pub use client::{};", plan.client_class));
    w.line("pub use tungsten_runtime::{");
    w.indent();
    w.line(
        "Binary, CallOptions, ClientOptions, ConfigError, Confirm, Diagnostic, Dispatch, Patch,",
    );
    w.line("PreviewResult, Response,");
    w.dedent();
    w.line("};");
    w.finish()
}

/// `(path to the operation, preview or pages method path)` of an operation
/// on the client, for the README's examples.
fn client_paths(plan: &Plan<'_>) -> Vec<(usize, String)> {
    fn walk(plan: &Plan<'_>, idx: usize, prefix: &str, out: &mut Vec<(usize, String)>) {
        for m in &plan.resources[idx].members {
            match m.kind {
                MemberKind::Op(o) => out.push((o, format!("{prefix}.{}", m.name))),
                MemberKind::Child(c) => walk(plan, c, &format!("{prefix}.{}()", m.name), out),
                MemberKind::Preview(_) | MemberKind::Pages(_) => {}
            }
        }
    }
    let mut out = vec![];
    if plan.multi() {
        for n in &plan.client_namespaces {
            for (name, i) in &n.members {
                walk(
                    plan,
                    *i,
                    &format!("client.{}().{name}()", n.member),
                    &mut out,
                );
            }
        }
    } else {
        for (name, i) in &plan.client_resources {
            walk(plan, *i, &format!("client.{name}()"), &mut out);
        }
    }
    out
}

/// The method name of `kind` for operation `o`.
fn derived(plan: &Plan<'_>, o: usize, path: &str, preview: bool) -> String {
    let (prefix, _) = path.rsplit_once('.').unwrap_or(("client", path));
    for r in &plan.resources {
        for m in &r.members {
            match m.kind {
                MemberKind::Preview(i) if preview && i == o => {
                    return format!("{prefix}.{}", m.name);
                }
                MemberKind::Pages(i) if !preview && i == o => {
                    return format!("{prefix}.{}", m.name);
                }
                _ => {}
            }
        }
    }
    path.to_string()
}

/// The `auth` entries of the README's client example: one per scheme a
/// caller configures. A composite profile replaces the schemes it
/// satisfies and takes its cookies and configuration keys.
fn auth_example(ir: &tungsten_ir::Ir) -> Vec<String> {
    let mut covered: BTreeSet<&str> = BTreeSet::new();
    let mut composites: Vec<(&str, Vec<&str>)> = vec![];
    for s in &ir.auth {
        if let AuthScheme::Composite {
            name,
            satisfies,
            parts,
        } = s
        {
            covered.extend(satisfies.iter().map(String::as_str));
            let keys = parts
                .iter()
                .filter_map(|p| match p {
                    CompositePart::Cookie { name } => Some(name.as_str()),
                    CompositePart::Header { from_config, .. } => from_config.as_deref(),
                    CompositePart::Bearer { .. } => None,
                })
                .collect();
            composites.push((name, keys));
        }
    }
    let mut entries: BTreeSet<String> = BTreeSet::new();
    for (name, keys) in &composites {
        let fields: Vec<String> = keys
            .iter()
            .map(|k| format!("({}.to_string(), \"<{k}>\".to_string())", string_lit(k)))
            .collect();
        entries.insert(format!(
            "({}.to_string(), Credential::Parts(BTreeMap::from([{}])))",
            string_lit(name),
            fields.join(", ")
        ));
    }
    for s in &ir.auth {
        let name = s.name();
        if !covered.contains(name) && !composites.iter().any(|(c, _)| *c == name) {
            entries.insert(format!(
                "({}.to_string(), Credential::Secret(\"<credential>\".to_string()))",
                string_lit(name)
            ));
        }
    }
    entries.into_iter().collect()
}

/// An example value for a required argument.
fn example_value(ty: &str, key: &str) -> String {
    match ty {
        "String" => format!("\"<{key}>\".to_string()"),
        "i64" | "i32" | "u64" => "1".into(),
        "f64" => "1.0".into(),
        "bool" => "true".into(),
        _ => "Default::default()".into(),
    }
}

/// Example request: required arguments with placeholders.
fn example_request(plan: &Plan<'_>, shape: &OpShape<'_>, o: usize) -> String {
    let info = &plan.ops[o];
    let name = &info.request;
    let fields: Vec<String> = shape
        .fields
        .iter()
        .filter(|f| !f.optional)
        .map(|f| format!("{}: {}", f.key, example_value(&f.slot.ty, &f.key)))
        .collect();
    if fields.is_empty() {
        format!("{name}::default()")
    } else {
        format!("{name} {{ {}, ..Default::default() }}", fields.join(", "))
    }
}

fn request_import(plan: &Plan<'_>, o: usize, lib: &str) -> String {
    let info = &plan.ops[o];
    format!(
        "use {lib}::resources::{}::{};",
        plan.resources[info.res].module, info.request
    )
}

/// The workspace README: install, auth, async calls, idempotency, preview
/// then confirm, pagination, macros and the error envelope.
pub(crate) fn readme(
    plan: &Plan<'_>,
    shapes: &[OpShape<'_>],
    opts: &Options,
    header: &str,
    has_macros: bool,
) -> String {
    let ir = plan.ir;
    let client = &plan.client_class;
    let lib = opts.lib_name();
    let paths = client_paths(plan);
    let mut out = String::new();
    out.push_str("<!--\n");
    for l in header.lines() {
        out.push_str(l.trim_start_matches('/').trim_start());
        out.push('\n');
    }
    out.push_str("-->\n\n");
    out.push_str(&format!("# {}\n\n", opts.package));
    out.push_str(&format!(
        "Rust SDK for the {} API ({}), generated by tungsten.\n\n",
        tungsten_ir::title_stem(&ir.api.title),
        ir.api.version
    ));
    out.push_str(
        "Every call returns `tungsten_runtime::Result<T>`: the value with its response \
         metadata, or the diagnostic envelope. API and transport errors are values, never \
         panics, and arguments are validated before any request is sent. The SDK is async \
         (tokio) and builds with Rust 1.88 or newer; models are `serde` types.\n\n",
    );
    out.push_str("## Install\n\n```sh\n");
    out.push_str(&format!(
        "cargo add {}\ncargo add tokio --features rt-multi-thread,macros\n```\n\n",
        opts.package
    ));
    out.push_str("## Create a client\n\n```rust\n");
    out.push_str(&format!(
        "use std::collections::BTreeMap;\n\nuse tungsten_runtime::Credential;\nuse {lib}::{{CallOptions, ClientOptions, {client}}};\n\n"
    ));
    let server = ir
        .api
        .servers
        .first()
        .map_or("https://api.example.test", |s| s.url.as_str());
    let auth = auth_example(ir);
    out.push_str(&format!(
        "let client = {client}::new(ClientOptions {{\n    base_url: Some({}.to_string()),\n",
        string_lit(server)
    ));
    if !auth.is_empty() {
        out.push_str(&format!(
            "    auth: BTreeMap::from([{}]),\n",
            auth.join(", ")
        ));
    }
    out.push_str("    ..Default::default()\n})?;\n```\n\n");
    if !ir.auth.is_empty() {
        out.push_str(
            "`auth` takes one credential per scheme name. A composite profile takes a map \
             keyed by cookie name or configuration key (`Credential::Parts`).\n\n",
        );
    }

    let find = |pred: &dyn Fn(usize) -> bool| paths.iter().find(|(o, _)| pred(*o));
    if let Some((o, path)) = find(&|o| plan.ops[o].op.agent.safety == Safety::ReadOnly) {
        let request = example_request(plan, &shapes[*o], *o);
        out.push_str("## Read\n\n```rust\n");
        out.push_str(&format!("{}\n\n", request_import(plan, *o, &lib)));
        out.push_str(
            "#[tokio::main]\nasync fn main() -> Result<(), Box<dyn std::error::Error>> {\n",
        );
        out.push_str("    // let client = ...;\n");
        out.push_str(&format!(
            "    match {path}({request}, &CallOptions::default()).await {{\n"
        ));
        out.push_str("        Ok(response) => println!(\"{:?}\", response.value),\n");
        out.push_str(
            "        Err(error) => println!(\"{:?} {}\", error.category, error.remediation),\n",
        );
        out.push_str("    }\n    Ok(())\n}\n```\n\n");
        out.push_str(
            "`response.meta` has the status, headers, request id and the number of attempts. \
             A success without a body is `()` (or `None` when only some success statuses have \
             one).\n\n",
        );
    }
    let mutating =
        find(&|o| plan.ops[o].op.agent.idempotency.policy == IdempotencyKind::CallerOwned)
            .or_else(|| find(&|o| plan.ops[o].op.agent.safety == Safety::Mutating));
    if let Some((o, path)) = mutating {
        let request = example_request(plan, &shapes[*o], *o);
        out.push_str("## Change something, safely\n\n");
        out.push_str(
            "Mutations are never retried blindly. When the operation takes an idempotency key, \
             generate it once, persist it with your intent, and reuse it on every retry.\n\n```rust\n",
        );
        out.push_str(&format!("{}\n\n", request_import(plan, *o, &lib)));
        out.push_str("let opts = CallOptions {\n    idempotency_key: Some(key), // a UUIDv4 you persisted\n    ..Default::default()\n};\n");
        out.push_str(&format!(
            "let result = {path}({request}, &opts).await;\n```\n\n"
        ));
    }
    if let Some((o, path)) = find(&|o| {
        let op = plan.ops[o].op;
        has_preview(op) && matches!(op.agent.safety, Safety::Destructive | Safety::Irreversible)
    }) {
        let op = plan.ops[*o].op;
        let preview = derived(plan, *o, path, true);
        let request = example_request(plan, &shapes[*o], *o);
        out.push_str("## Preview, then confirm\n\n");
        out.push_str(&format!(
            "`{}` is `{}`: it needs a confirmation. Preview it (no request is sent), show the effects, then pass the token.\n\n```rust\n",
            op.id.0,
            safety_str(op.agent.safety)
        ));
        out.push_str(&format!(
            "{}\nuse {lib}::Confirm;\n\n",
            request_import(plan, *o, &lib)
        ));
        out.push_str(&format!(
            "let preview = {preview}({request}.clone(), &CallOptions::default()).await?;\n"
        ));
        out.push_str("println!(\"{:?}\", preview.value.effects);\n");
        out.push_str("let opts = CallOptions {\n    confirm: preview.value.confirmation_token.map(Confirm::Token),\n    ..Default::default()\n};\n");
        out.push_str(&format!("{path}({request}, &opts).await?;\n```\n\n"));
    }
    if let Some((o, path)) = find(&|o| shapes[o].page_item.is_some()) {
        let pages = derived(plan, *o, path, false);
        let request = example_request(plan, &shapes[*o], *o);
        out.push_str("## Pagination\n\n```rust\n");
        out.push_str(&format!("{}\n\n", request_import(plan, *o, &lib)));
        out.push_str(&format!(
            "let mut pages = {pages}({request}, &CallOptions::default());\nwhile let Some(page) = pages.next().await {{\n    match page {{\n        Ok(page) => {{\n            for item in page.value.items {{\n                println!(\"{{item:?}}\");\n            }}\n        }}\n        Err(error) => {{\n            eprintln!(\"{{error}}\");\n            break;\n        }}\n    }}\n}}\n```\n\n"
        ));
    }
    if has_macros {
        out.push_str(
            "## Macros\n\nMulti-step workflows from the agent manifest are methods of `client.macros()`, \
             run by the runtime from the descriptors in `macros.rs`. Each takes an input struct and \
             returns the macro's output as `serde_json::Value`. A macro that is `destructive` or \
             `irreversible`, or has such a step, is confirmed once for the whole run: call its \
             `preview_<macro>(...)` (nothing is sent) and pass the `confirmation_token` as \
             `Confirm::Token`. The first failing step's envelope is returned and names the steps \
             already completed.\n\n",
        );
    }
    out.push_str(
        "## Models and optional fields\n\nRequest and response bodies are `serde` structs under \
         `models`. A field that may be left out is `Option<T>` and is not sent when `None`; a \
         required field that may be `null` is `Option<T>` and is sent as `null`; a field that may \
         be left out or `null` is `Patch<T>` (`Patch::Undefined`, `Patch::Null`, `Patch::Value`). \
         Closed records reject unknown members; open records keep them in `extra`. String and \
         integer enums are closed: an unknown value does not decode. Integer fields are `i64` \
         (`i32` for `int32`, `u64` for non-negative ones above `i64::MAX`) and do not accept \
         `1.0`. Constraints (bounds, lengths, patterns, formats, unique items) are checked by \
         the validators the SDK registers with the runtime, before a request is sent and, per \
         `ClientOptions::validate_responses`, on responses.\n\n",
    );
    out.push_str("## Errors\n\nA failed call is `Err(error)`; `error.diagnostic` is the envelope:\n\n```json\n");
    out.push_str(
        "{\n  \"status\": \"error\",\n  \"category\": \"VALIDATION_FAILED\",\n  \"operation\": \"<operation id>\",\n  \"http_status\": null,\n  \"code\": null,\n  \"failed_parameter\": \"<args path>\",\n  \"received_value\": null,\n  \"expected\": \"<what was expected>\",\n  \"remediation\": \"<what to do next>\",\n  \"retryable\": \"never\",\n  \"retry_after_ms\": null,\n  \"next_action\": null,\n  \"request_id\": null,\n  \"trace\": { \"attempts\": 0 }\n}\n```\n\n",
    );
    out.push_str(
        "Branch on `category` and `retryable`: `same_key_only` means retry only with the same \
         idempotency key, `after_remediation` means act first (fix the input, or check \
         whether an unknown outcome took effect: without a key a repeat can apply it \
         twice), and `OUTCOME_UNKNOWN` means the request may have been applied. \
         `error.partial` holds what a failed call or macro already produced (a one-time \
         secret, completed step results): store it before acting on the error.\n\n",
    );
    out.push_str(
        "## Dynamic calls\n\nThe client implements `tungsten_runtime::Dispatch`: `invoke`, `preview`, `pages`, \
         `run_macro` and `preview_macro` take an operation id (or macro name) and a JSON arguments \
         object keyed by argument name, run the same typed methods and return JSON. Arguments \
         that do not decode go to the runtime as given, which answers with the pre-flight envelope.\n\n",
    );
    if let Some(cli) = &opts.cli {
        out.push_str(&format!(
            "## Command line\n\nThe `{}` binary (crate `{}`) is built on this SDK: one command per operation, `--json` output, \
             `--dry-run` previews and the same safety rules. Build it with `cargo build -p {} --release`.\n\n",
            cli.bin, cli.package, cli.package
        ));
    }
    out.push_str(
        "## Extending\n\n`src/custom/mod.rs` is yours: it is created once, never overwritten, and exported as `custom`.\n",
    );
    out
}

/// The shared helpers module.
pub(crate) fn support_file(header: &str) -> String {
    // The template starts with the licence line of this repository, which
    // generated files do not carry.
    let template = include_str!("support_template.rs");
    let body = template.split_once('\n').map_or(template, |(_, rest)| rest);
    format!("{header}\n\n{body}")
}
