// SPDX-License-Identifier: AGPL-3.0-only
//! Package files: `package.json`, `tsconfig.json`, `README.md`, the
//! internal helpers module and the hand-editable `src/custom/index.ts`.

use std::collections::BTreeSet;

use serde_json::json;
use tungsten_emit::Writer;
use tungsten_ir::{AuthScheme, CompositePart, IdempotencyKind, Safety};

use crate::ops::{OpShape, safety_str};
use crate::options::{Options, TYPESCRIPT_VERSION, ZOD_RANGE};
use crate::plan::{MemberKind, Plan};
use crate::resources::has_preview;
use crate::ts::string_lit;

pub(crate) fn package_json(plan: &Plan<'_>, opts: &Options) -> String {
    let doc = json!({
        "name": opts.package,
        "version": opts.version,
        "description": format!("TypeScript SDK for the {} API, generated by tungsten.", plan.ir.api.title),
        "type": "module",
        "sideEffects": false,
        "main": "./dist/index.js",
        "types": "./dist/index.d.ts",
        "exports": {
            ".": { "types": "./dist/index.d.ts", "import": "./dist/index.js" }
        },
        "files": ["dist"],
        "engines": { "node": ">=22" },
        "scripts": {
            "build": "tsc -p tsconfig.json",
            "typecheck": "tsc -p tsconfig.json --noEmit"
        },
        "dependencies": {
            "@tungsten/runtime": opts.runtime,
            "zod": ZOD_RANGE
        },
        "devDependencies": {
            "typescript": TYPESCRIPT_VERSION
        }
    });
    let mut text = serde_json::to_string_pretty(&doc).unwrap_or_default();
    text.push('\n');
    text
}

pub(crate) fn tsconfig_json() -> String {
    let doc = json!({
        "compilerOptions": {
            "target": "ES2022",
            "module": "NodeNext",
            "moduleResolution": "NodeNext",
            "lib": ["ES2022", "DOM"],
            "strict": true,
            "exactOptionalPropertyTypes": true,
            "noUncheckedIndexedAccess": true,
            "noImplicitOverride": true,
            "declaration": true,
            "outDir": "dist",
            "rootDir": "src",
            "skipLibCheck": true
        },
        "include": ["src"]
    });
    let mut text = serde_json::to_string_pretty(&doc).unwrap_or_default();
    text.push('\n');
    text
}

/// The hand-editable template. Never overwritten once it exists.
pub(crate) fn custom_template() -> String {
    "// Hand-written extensions of this SDK. tungsten creates this file once and\n\
     // never overwrites or deletes it; it is exported from the package as `custom`.\n\
     \n\
     export {};\n"
        .to_string()
}

/// Helpers the generated modules share.
pub(crate) fn internal_file(header: &str) -> String {
    let mut w = Writer::new("  ");
    w.line(header);
    w.blank();
    w.line("// Helpers shared by the generated modules; not part of the package's API.");
    w.blank();
    w.line("import type { SchemaLike } from \"@tungsten/runtime\";");
    w.line("import { z } from \"zod\";");
    w.blank();
    w.line(TO_SCHEMA_LIKE);
    w.blank();
    w.line(INTEGER);
    w.blank();
    w.line(WITH_PATTERN);
    w.finish()
}

const TO_SCHEMA_LIKE: &str = r#"/** A Zod schema as the runtime's `SchemaLike` (issue paths as strings and numbers). */
export function toSchemaLike<T>(schema: z.ZodType<T>): SchemaLike<T> {
  return {
    safeParse(value: unknown) {
      const result = schema.safeParse(value);
      if (result.success) return { success: true, data: result.data };
      const issues = result.error.issues.map((issue) => ({
        path: issue.path.map((p) => (typeof p === "symbol" ? String(p) : p)),
        message: issue.message,
        code: issue.code,
      }));
      return { success: false, error: { issues } };
    },
  };
}"#;

const INTEGER: &str = r#"/** An integer. Unlike `z.int()` it accepts 64-bit values beyond 2^53, which
 * JSON decoding has already rounded to the nearest JavaScript number. */
export function integer(): z.ZodNumber {
  return z.number().refine(Number.isInteger, { message: "expected an integer" });
}"#;

const WITH_PATTERN: &str = r#"/** Adds a JSON Schema `pattern` (ECMA-262, Unicode mode when it compiles).
 * A pattern this engine cannot compile is not enforced, so loading the SDK
 * never fails; the server still validates it. */
export function withPattern<S extends { regex(pattern: RegExp): S }>(schema: S, source: string): S {
  for (const flags of ["u", ""]) {
    try {
      return schema.regex(new RegExp(source, flags));
    } catch {
      // Not valid with these flags; try the next.
    }
  }
  return schema;
}"#;

/// Where an operation lives on the client (`client.public.webhooks.list`).
fn client_paths(plan: &Plan<'_>) -> Vec<(usize, String)> {
    fn walk(plan: &Plan<'_>, idx: usize, prefix: &str, out: &mut Vec<(usize, String)>) {
        for m in &plan.resources[idx].members {
            match m.kind {
                MemberKind::Op(o) => out.push((o, format!("{prefix}.{}", m.name))),
                MemberKind::Child(c) => walk(plan, c, &format!("{prefix}.{}", m.name), out),
            }
        }
    }
    let mut out = vec![];
    if plan.multi() {
        for n in &plan.client_namespaces {
            for (name, i) in &n.members {
                walk(plan, *i, &format!("client.{}.{name}", n.member), &mut out);
            }
        }
    } else {
        for (name, i) in &plan.client_resources {
            walk(plan, *i, &format!("client.{name}"), &mut out);
        }
    }
    out
}

/// The `auth` entries of the README's client example: one per scheme a
/// caller configures. A composite profile replaces the schemes it
/// satisfies and takes an object of its cookies and configuration keys.
fn auth_example(ir: &tungsten_ir::Ir) -> Vec<String> {
    let mut covered: BTreeSet<&str> = BTreeSet::new();
    let mut composites: Vec<(&str, Vec<&str>)> = vec![];
    for s in &ir.auth {
        if let AuthScheme::Composite {
            name,
            satisfies,
            parts,
        } = s
        {
            covered.extend(satisfies.iter().map(String::as_str));
            let keys = parts
                .iter()
                .filter_map(|p| match p {
                    CompositePart::Cookie { name } => Some(name.as_str()),
                    CompositePart::Header { from_config, .. } => from_config.as_deref(),
                    CompositePart::Bearer { .. } => None,
                })
                .collect();
            composites.push((name, keys));
        }
    }
    let mut entries: BTreeSet<String> = BTreeSet::new();
    for (name, keys) in &composites {
        let fields: Vec<String> = keys
            .iter()
            .map(|k| format!("{}: \"<{k}>\"", crate::ts::prop_key(k)))
            .collect();
        entries.insert(format!(
            "{}: {{ {} }}",
            crate::ts::prop_key(name),
            fields.join(", ")
        ));
    }
    for s in &ir.auth {
        let name = s.name();
        if !covered.contains(name) && !composites.iter().any(|(c, _)| *c == name) {
            entries.insert(format!("{}: \"<credential>\"", crate::ts::prop_key(name)));
        }
    }
    entries.into_iter().collect()
}

/// Example args for a call: required keys with placeholder values.
fn example_args(shape: &OpShape<'_>) -> String {
    let parts: Vec<String> = shape
        .fields
        .iter()
        .filter(|f| !f.optional)
        .map(|f| {
            let value = match f.ts.as_str() {
                "number" => "1".to_string(),
                "boolean" => "true".to_string(),
                "Uint8Array" => "new Uint8Array()".to_string(),
                t if t.starts_with('"') => t.split(" | ").next().unwrap_or(t).to_string(),
                "string" => string_lit(&format!("<{}>", f.key)),
                _ => "/* ... */".to_string(),
            };
            format!("{}: {value}", crate::ts::prop_key(&f.key))
        })
        .collect();
    if parts.is_empty() {
        String::new()
    } else {
        format!("{{ {} }}", parts.join(", "))
    }
}

/// The package README: install, auth, a read, a mutation with
/// idempotency, preview then confirm, pagination and the error envelope.
pub(crate) fn readme(
    plan: &Plan<'_>,
    shapes: &[OpShape<'_>],
    opts: &Options,
    header: &str,
    has_macros: bool,
) -> String {
    let ir = plan.ir;
    let client = &plan.client_class;
    let paths = client_paths(plan);
    let mut out = String::new();
    out.push_str("<!--\n");
    for l in header.lines() {
        out.push_str(l.trim_start_matches("//").trim_start());
        out.push('\n');
    }
    out.push_str("-->\n\n");
    out.push_str(&format!("# {}\n\n", opts.package));
    out.push_str(&format!(
        "TypeScript SDK for the {} API ({}), generated by tungsten.\n\n",
        ir.api.title, ir.api.version
    ));
    out.push_str(
        "Every call returns a `Result` and never throws for API or transport errors. \
                  Arguments are validated before any request is sent.\n\n",
    );
    out.push_str("## Install\n\n```sh\n");
    out.push_str(&format!("npm install {}\n```\n\n", opts.package));
    out.push_str("## Create a client\n\n```ts\n");
    out.push_str(&format!(
        "import {{ {client} }} from {};\n\n",
        string_lit(&opts.package)
    ));
    let auth = auth_example(ir);
    let server = ir
        .api
        .servers
        .first()
        .map_or("https://api.example.test", |s| s.url.as_str());
    out.push_str(&format!(
        "const client = new {client}({{\n  baseUrl: {},\n",
        string_lit(server)
    ));
    if !auth.is_empty() {
        out.push_str(&format!("  auth: {{ {} }},\n", auth.join(", ")));
    }
    out.push_str("});\n```\n\n");
    if !ir.auth.is_empty() {
        out.push_str(
            "`auth` takes one entry per scheme name. A composite profile takes an object \
                      keyed by cookie name or configuration key.\n\n",
        );
    }

    let find = |pred: &dyn Fn(usize) -> bool| paths.iter().find(|(o, _)| pred(*o));
    let call = |o: usize, path: &str, extra: &str| {
        let args = example_args(&shapes[o]);
        match (args.is_empty(), extra.is_empty()) {
            (true, true) => format!("{path}()"),
            (true, false) => format!("{path}({{}}, {extra})"),
            (false, true) => format!("{path}({args})"),
            (false, false) => format!("{path}({args}, {extra})"),
        }
    };
    if let Some((o, path)) = find(&|o| plan.ops[o].op.agent.safety == Safety::ReadOnly) {
        out.push_str("## Read\n\n```ts\n");
        out.push_str(&format!("const res = await {};\n", call(*o, path, "")));
        out.push_str("if (res.ok) console.log(res.value);\nelse console.error(res.error.category, res.error.remediation);\n```\n\n");
    }
    let mutating =
        find(&|o| plan.ops[o].op.agent.idempotency.policy == IdempotencyKind::CallerOwned)
            .or_else(|| find(&|o| plan.ops[o].op.agent.safety == Safety::Mutating));
    if let Some((o, path)) = mutating {
        out.push_str("## Change something, safely\n\n");
        out.push_str("Mutations are never retried blindly. When the operation takes an idempotency key, \
                      generate it once, persist it with your intent, and reuse it on every retry.\n\n```ts\n");
        out.push_str("const idempotencyKey = crypto.randomUUID();\n");
        out.push_str(&format!(
            "const res = await {};\n```\n\n",
            call(*o, path, "{ idempotencyKey }")
        ));
    }
    if let Some((o, path)) = find(&|o| {
        let info = &plan.ops[o];
        has_preview(info)
            && matches!(
                info.op.agent.safety,
                Safety::Destructive | Safety::Irreversible
            )
    }) {
        let info = &plan.ops[*o];
        out.push_str("## Preview, then confirm\n\n");
        out.push_str(&format!(
            "`{}` is `{}`: it needs a confirmation. Preview it (no request is sent), show the effects, then pass the token.\n\n```ts\n",
            info.op.id.0,
            safety_str(info.op.agent.safety)
        ));
        let args = example_args(&shapes[*o]);
        let args = if args.is_empty() {
            "{}".to_string()
        } else {
            args
        };
        out.push_str(&format!("const preview = await {path}.preview({args});\n"));
        out.push_str("if (preview.ok && preview.value.confirmation_token) {\n");
        out.push_str("  console.log(preview.value.effects);\n");
        out.push_str(&format!(
            "  await {path}({args}, {{ confirm: preview.value.confirmation_token }});\n}}\n```\n\n"
        ));
    }
    if let Some((o, path)) = find(&|o| shapes[o].page_item.is_some()) {
        out.push_str("## Pagination\n\n```ts\n");
        let args = example_args(&shapes[*o]);
        out.push_str(&format!(
            "for await (const page of {path}.pages({args})) {{\n"
        ));
        out.push_str("  if (!page.ok) break;\n  for (const item of page.value.items) console.log(item);\n}\n```\n\n");
    }
    if has_macros {
        out.push_str("## Macros\n\nMulti-step workflows from the agent manifest are methods of `client.macros`, \
                      run by the runtime from the descriptors in `src/macros.ts`. A macro that is `destructive` or \
                      `irreversible`, or has such a step, is confirmed once for the whole run: call \
                      `.preview(input)` on it (nothing is sent) and pass its `confirmation_token` as `confirm`. \
                      The first failing step's envelope is returned and names the steps already completed.\n\n");
    }
    out.push_str("## Errors\n\nA failed call returns `{ ok: false, error }`, where `error` is the diagnostic envelope:\n\n```json\n");
    out.push_str(
        "{\n  \"status\": \"error\",\n  \"category\": \"VALIDATION_FAILED\",\n  \"operation\": \"<operation id>\",\n  \"http_status\": null,\n  \"code\": null,\n  \"failed_parameter\": \"<args path>\",\n  \"received_value\": null,\n  \"expected\": \"<what was expected>\",\n  \"remediation\": \"<what to do next>\",\n  \"retryable\": \"never\",\n  \"retry_after_ms\": null,\n  \"next_action\": null,\n  \"request_id\": null,\n  \"trace\": { \"attempts\": 0 }\n}\n```\n\n",
    );
    out.push_str(
        "Branch on `category` and `retryable`: `same_key_only` means retry only with the same \
                  idempotency key, and `OUTCOME_UNKNOWN` means the request may have been applied. \
                  A success response without a body has `value: undefined`.\n\n",
    );
    out.push_str("## Extending\n\n`src/custom/index.ts` is yours: it is created once, never overwritten, and exported as `custom`.\n");
    out
}
