// SPDX-License-Identifier: AGPL-3.0-only
//! Package files: `package.json`, `tsconfig.json`, `README.md`, the
//! internal helpers module and the hand-editable `src/custom/index.ts`.

use std::collections::BTreeSet;

use serde_json::json;
use tungsten_emit::Writer;
use tungsten_ir::{AuthScheme, CompositePart, IdempotencyKind, Safety};

use crate::ops::{OpShape, safety_str};
use crate::options::{Options, TYPESCRIPT_VERSION, ZOD_RANGE};
use crate::plan::{MemberKind, Plan};
use crate::resources::has_preview;
use crate::ts::string_lit;

pub(crate) fn package_json(plan: &Plan<'_>, opts: &Options) -> String {
    let doc = json!({
        "name": opts.package,
        "version": opts.version,
        "description": format!("TypeScript SDK for the {} API, generated by tungsten.", plan.ir.api.title),
        "type": "module",
        "sideEffects": false,
        "main": "./dist/index.js",
        "types": "./dist/index.d.ts",
        "exports": {
            ".": { "types": "./dist/index.d.ts", "import": "./dist/index.js" }
        },
        "files": ["dist"],
        "engines": { "node": ">=22" },
        "scripts": {
            "build": "tsc -p tsconfig.json",
            "typecheck": "tsc -p tsconfig.json --noEmit"
        },
        "dependencies": {
            "@tungsten/runtime": opts.runtime,
            "zod": ZOD_RANGE
        },
        "devDependencies": {
            "typescript": TYPESCRIPT_VERSION
        }
    });
    let mut text = serde_json::to_string_pretty(&doc).unwrap_or_default();
    text.push('\n');
    text
}

pub(crate) fn tsconfig_json() -> String {
    let doc = json!({
        "compilerOptions": {
            "target": "ES2022",
            "module": "NodeNext",
            "moduleResolution": "NodeNext",
            "lib": ["ES2022", "DOM"],
            "strict": true,
            "exactOptionalPropertyTypes": true,
            "noUncheckedIndexedAccess": true,
            "noImplicitOverride": true,
            "declaration": true,
            "outDir": "dist",
            "rootDir": "src",
            "skipLibCheck": true
        },
        "include": ["src"]
    });
    let mut text = serde_json::to_string_pretty(&doc).unwrap_or_default();
    text.push('\n');
    text
}

/// The hand-editable template. Never overwritten once it exists.
pub(crate) fn custom_template() -> String {
    "// Hand-written extensions of this SDK. tungsten creates this file once and\n\
     // never overwrites or deletes it; it is exported from the package as `custom`.\n\
     \n\
     export {};\n"
        .to_string()
}

/// Helpers the generated modules share. Macro helpers are included only
/// when macros use them.
pub(crate) fn internal_file(header: &str, macro_helpers: &BTreeSet<&str>) -> String {
    let mut macro_helpers = macro_helpers.clone();
    if macro_helpers.contains("isIn") {
        macro_helpers.insert("jsonEqual");
    }
    let mut w = Writer::new("  ");
    w.line(header);
    w.blank();
    w.line("// Helpers shared by the generated modules; not part of the package's API.");
    w.blank();
    let mut runtime_types = vec!["OperationDescriptor", "SchemaLike"];
    if macro_helpers.contains("laterOptions") {
        runtime_types.push("CallOptions");
    }
    if macro_helpers.contains("invalidInput") {
        runtime_types.push("Diagnostic");
    }
    if macro_helpers.contains("noMeta") {
        runtime_types.push("ResponseMeta");
    }
    runtime_types.sort_unstable();
    w.line(format!(
        "import type {{ {} }} from \"@tungsten/runtime\";",
        runtime_types.join(", ")
    ));
    w.line("import { z } from \"zod\";");
    w.blank();
    w.line(TO_SCHEMA_LIKE);
    w.blank();
    w.line(INTEGER);
    w.blank();
    w.line(WITH_PATTERN);
    w.blank();
    w.line(RPC);
    for (name, code) in MACRO_HELPERS {
        if macro_helpers.contains(name) {
            w.blank();
            w.line(*code);
        }
    }
    w.finish()
}

const TO_SCHEMA_LIKE: &str = r#"/** A Zod schema as the runtime's `SchemaLike` (issue paths as strings and numbers). */
export function toSchemaLike<T>(schema: z.ZodType<T>): SchemaLike<T> {
  return {
    safeParse(value: unknown) {
      const result = schema.safeParse(value);
      if (result.success) return { success: true, data: result.data };
      const issues = result.error.issues.map((issue) => ({
        path: issue.path.map((p) => (typeof p === "symbol" ? String(p) : p)),
        message: issue.message,
        code: issue.code,
      }));
      return { success: false, error: { issues } };
    },
  };
}"#;

const INTEGER: &str = r#"/** An integer. Unlike `z.int()` it accepts 64-bit values beyond 2^53, which
 * JSON decoding has already rounded to the nearest JavaScript number. */
export function integer(): z.ZodNumber {
  return z.number().refine(Number.isInteger, { message: "expected an integer" });
}"#;

const WITH_PATTERN: &str = r#"/** Adds a JSON Schema `pattern` (ECMA-262, Unicode mode when it compiles).
 * A pattern this engine cannot compile is not enforced, so loading the SDK
 * never fails; the server still validates it. */
export function withPattern<S extends { regex(pattern: RegExp): S }>(schema: S, source: string): S {
  for (const flags of ["u", ""]) {
    try {
      return schema.regex(new RegExp(source, flags));
    } catch {
      // Not valid with these flags; try the next.
    }
  }
  return schema;
}"#;

const RPC: &str = r#"/** The rpc binding of an operation: the envelope field and value to send, the
 * field holding the args, and envelope members sent verbatim. */
export function rpc(
  field: string,
  value: string,
  paramsField: string,
  constants?: Record<string, unknown>,
): OperationDescriptor["rpc"] {
  const binding = { field, value, paramsField };
  return constants === undefined ? binding : Object.assign(binding, { constants });
}"#;

const MACRO_HELPERS: &[(&str, &str)] = &[
    (
        "asArgs",
        r#"/** A value as an args object (`{}` when it is not an object). */
export function asArgs(value: unknown): Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}"#,
    ),
    (
        "get",
        r#"/** The value at `path` (own properties only), or undefined. */
export function get(value: unknown, path: readonly string[]): unknown {
  let current: unknown = value;
  for (const key of path) {
    if (typeof current !== "object" || current === null || !Object.prototype.hasOwnProperty.call(current, key)) {
      return undefined;
    }
    current = (current as Record<string, unknown>)[key];
  }
  return current;
}"#,
    ),
    (
        "invalidInput",
        r#"/** The envelope for a macro input that cannot be used. */
export function invalidInput(operation: string, parameter: string, value: unknown, expected: string): { ok: false; error: Diagnostic } {
  return {
    ok: false,
    error: {
      status: "error",
      category: "VALIDATION_FAILED",
      operation,
      http_status: null,
      code: null,
      failed_parameter: parameter,
      received_value: typeof value === "string" ? value.slice(0, 200) : value,
      expected,
      remediation: `Pass ${parameter} as ${expected} and call ${operation} again.`,
      retryable: "never",
      retry_after_ms: null,
      next_action: null,
      request_id: null,
      trace: { attempts: 0 },
    },
  };
}"#,
    ),
    (
        "isIn",
        r#"/** Whether `value` equals one of `options` (JSON equality). */
export function isIn(value: unknown, options: readonly unknown[]): boolean {
  return options.some((option) => jsonEqual(value, option));
}"#,
    ),
    (
        "jsonEqual",
        r#"/** JSON equality: same primitives, arrays item by item, objects key by key. */
export function jsonEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) return false;
  if (Array.isArray(a) || Array.isArray(b)) {
    return Array.isArray(a) && Array.isArray(b) && a.length === b.length && a.every((x, i) => jsonEqual(x, b[i]));
  }
  const ka = Object.keys(a);
  const kb = Object.keys(b);
  return (
    ka.length === kb.length &&
    ka.every((k) => Object.prototype.hasOwnProperty.call(b, k) && jsonEqual((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]))
  );
}"#,
    ),
    (
        "laterOptions",
        r#"/** The options of a macro's later steps: cancellation, timeout and headers,
 * never the first step's idempotency key or confirmation. */
export function laterOptions(opts: CallOptions | undefined): CallOptions {
  const later: CallOptions = {};
  if (opts?.signal !== undefined) later.signal = opts.signal;
  if (opts?.timeoutMs !== undefined) later.timeoutMs = opts.timeoutMs;
  if (opts?.headers !== undefined) later.headers = opts.headers;
  return later;
}"#,
    ),
    (
        "noMeta",
        r#"/** Response metadata before any response arrived. */
export function noMeta(): ResponseMeta {
  return { status: 0, headers: {}, requestId: null, attempts: 0 };
}"#,
    ),
    (
        "omit",
        r#"/** `value` without `keys`, as an args object. */
export function omit(value: object, keys: readonly string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(value)) {
    if (!keys.includes(k)) out[k] = v;
  }
  return out;
}"#,
    ),
];

/// Where an operation lives on the client (`client.public.webhooks.list`).
fn client_paths(plan: &Plan<'_>) -> Vec<(usize, String)> {
    fn walk(plan: &Plan<'_>, idx: usize, prefix: &str, out: &mut Vec<(usize, String)>) {
        for m in &plan.resources[idx].members {
            match m.kind {
                MemberKind::Op(o) => out.push((o, format!("{prefix}.{}", m.name))),
                MemberKind::Child(c) => walk(plan, c, &format!("{prefix}.{}", m.name), out),
            }
        }
    }
    let mut out = vec![];
    if plan.multi() {
        for n in &plan.client_namespaces {
            for (name, i) in &n.members {
                walk(plan, *i, &format!("client.{}.{name}", n.member), &mut out);
            }
        }
    } else {
        for (name, i) in &plan.client_resources {
            walk(plan, *i, &format!("client.{name}"), &mut out);
        }
    }
    out
}

/// The `auth` entries of the README's client example: one per scheme a
/// caller configures. A composite profile replaces the schemes it
/// satisfies and takes an object of its cookies and configuration keys.
fn auth_example(ir: &tungsten_ir::Ir) -> Vec<String> {
    let mut covered: BTreeSet<&str> = BTreeSet::new();
    let mut composites: Vec<(&str, Vec<&str>)> = vec![];
    for s in &ir.auth {
        if let AuthScheme::Composite {
            name,
            satisfies,
            parts,
        } = s
        {
            covered.extend(satisfies.iter().map(String::as_str));
            let keys = parts
                .iter()
                .filter_map(|p| match p {
                    CompositePart::Cookie { name } => Some(name.as_str()),
                    CompositePart::Header { from_config, .. } => from_config.as_deref(),
                    CompositePart::Bearer { .. } => None,
                })
                .collect();
            composites.push((name, keys));
        }
    }
    let mut entries: BTreeSet<String> = BTreeSet::new();
    for (name, keys) in &composites {
        let fields: Vec<String> = keys
            .iter()
            .map(|k| format!("{}: \"<{k}>\"", crate::ts::prop_key(k)))
            .collect();
        entries.insert(format!(
            "{}: {{ {} }}",
            crate::ts::prop_key(name),
            fields.join(", ")
        ));
    }
    for s in &ir.auth {
        let name = s.name();
        if !covered.contains(name) && !composites.iter().any(|(c, _)| *c == name) {
            entries.insert(format!("{}: \"<credential>\"", crate::ts::prop_key(name)));
        }
    }
    entries.into_iter().collect()
}

/// Example args for a call: required keys with placeholder values.
fn example_args(shape: &OpShape<'_>) -> String {
    let parts: Vec<String> = shape
        .fields
        .iter()
        .filter(|f| !f.optional)
        .map(|f| {
            let value = match f.ts.as_str() {
                "number" => "1".to_string(),
                "boolean" => "true".to_string(),
                "Uint8Array" => "new Uint8Array()".to_string(),
                t if t.starts_with('"') => t.split(" | ").next().unwrap_or(t).to_string(),
                "string" => string_lit(&format!("<{}>", f.key)),
                _ => "/* ... */".to_string(),
            };
            format!("{}: {value}", crate::ts::prop_key(&f.key))
        })
        .collect();
    if parts.is_empty() {
        String::new()
    } else {
        format!("{{ {} }}", parts.join(", "))
    }
}

/// The package README: install, auth, a read, a mutation with
/// idempotency, preview then confirm, pagination and the error envelope.
pub(crate) fn readme(
    plan: &Plan<'_>,
    shapes: &[OpShape<'_>],
    opts: &Options,
    header: &str,
    has_macros: bool,
) -> String {
    let ir = plan.ir;
    let client = &plan.client_class;
    let paths = client_paths(plan);
    let mut out = String::new();
    out.push_str("<!--\n");
    for l in header.lines() {
        out.push_str(l.trim_start_matches("//").trim_start());
        out.push('\n');
    }
    out.push_str("-->\n\n");
    out.push_str(&format!("# {}\n\n", opts.package));
    out.push_str(&format!(
        "TypeScript SDK for the {} API ({}), generated by tungsten.\n\n",
        ir.api.title, ir.api.version
    ));
    out.push_str(
        "Every call returns a `Result` and never throws for API or transport errors. \
                  Arguments are validated before any request is sent.\n\n",
    );
    out.push_str("## Install\n\n```sh\n");
    out.push_str(&format!("npm install {}\n```\n\n", opts.package));
    out.push_str("## Create a client\n\n```ts\n");
    out.push_str(&format!(
        "import {{ {client} }} from {};\n\n",
        string_lit(&opts.package)
    ));
    let auth = auth_example(ir);
    let server = ir
        .api
        .servers
        .first()
        .map_or("https://api.example.test", |s| s.url.as_str());
    out.push_str(&format!(
        "const client = new {client}({{\n  baseUrl: {},\n",
        string_lit(server)
    ));
    if !auth.is_empty() {
        out.push_str(&format!("  auth: {{ {} }},\n", auth.join(", ")));
    }
    out.push_str("});\n```\n\n");
    if !ir.auth.is_empty() {
        out.push_str(
            "`auth` takes one entry per scheme name. A composite profile takes an object \
                      keyed by cookie name or configuration key.\n\n",
        );
    }

    let find = |pred: &dyn Fn(usize) -> bool| paths.iter().find(|(o, _)| pred(*o));
    let call = |o: usize, path: &str, extra: &str| {
        let args = example_args(&shapes[o]);
        match (args.is_empty(), extra.is_empty()) {
            (true, true) => format!("{path}()"),
            (true, false) => format!("{path}({{}}, {extra})"),
            (false, true) => format!("{path}({args})"),
            (false, false) => format!("{path}({args}, {extra})"),
        }
    };
    if let Some((o, path)) = find(&|o| plan.ops[o].op.agent.safety == Safety::ReadOnly) {
        out.push_str("## Read\n\n```ts\n");
        out.push_str(&format!("const res = await {};\n", call(*o, path, "")));
        out.push_str("if (res.ok) console.log(res.value);\nelse console.error(res.error.category, res.error.remediation);\n```\n\n");
    }
    let mutating =
        find(&|o| plan.ops[o].op.agent.idempotency.policy == IdempotencyKind::CallerOwned)
            .or_else(|| find(&|o| plan.ops[o].op.agent.safety == Safety::Mutating));
    if let Some((o, path)) = mutating {
        out.push_str("## Change something, safely\n\n");
        out.push_str("Mutations are never retried blindly. When the operation takes an idempotency key, \
                      generate it once, persist it with your intent, and reuse it on every retry.\n\n```ts\n");
        out.push_str("const idempotencyKey = crypto.randomUUID();\n");
        out.push_str(&format!(
            "const res = await {};\n```\n\n",
            call(*o, path, "{ idempotencyKey }")
        ));
    }
    if let Some((o, path)) = find(&|o| {
        let info = &plan.ops[o];
        has_preview(info)
            && matches!(
                info.op.agent.safety,
                Safety::Destructive | Safety::Irreversible
            )
    }) {
        let info = &plan.ops[*o];
        out.push_str("## Preview, then confirm\n\n");
        out.push_str(&format!(
            "`{}` is `{}`: it needs a confirmation. Preview it (no request is sent), show the effects, then pass the token.\n\n```ts\n",
            info.op.id.0,
            safety_str(info.op.agent.safety)
        ));
        let args = example_args(&shapes[*o]);
        let args = if args.is_empty() {
            "{}".to_string()
        } else {
            args
        };
        out.push_str(&format!("const preview = await {path}.preview({args});\n"));
        out.push_str("if (preview.ok && preview.value.confirmation_token) {\n");
        out.push_str("  console.log(preview.value.effects);\n");
        out.push_str(&format!(
            "  await {path}({args}, {{ confirm: preview.value.confirmation_token }});\n}}\n```\n\n"
        ));
    }
    if let Some((o, path)) = find(&|o| shapes[o].page_item.is_some()) {
        out.push_str("## Pagination\n\n```ts\n");
        let args = example_args(&shapes[*o]);
        out.push_str(&format!(
            "for await (const page of {path}.pages({args})) {{\n"
        ));
        out.push_str("  if (!page.ok) break;\n  for (const item of page.value.items) console.log(item);\n}\n```\n\n");
    }
    if has_macros {
        out.push_str("## Macros\n\nMulti-step workflows from the agent manifest are methods of `client.macros`.\n\n");
    }
    out.push_str("## Errors\n\nA failed call returns `{ ok: false, error }`, where `error` is the diagnostic envelope:\n\n```json\n");
    out.push_str(
        "{\n  \"status\": \"error\",\n  \"category\": \"VALIDATION_FAILED\",\n  \"operation\": \"<operation id>\",\n  \"http_status\": null,\n  \"code\": null,\n  \"failed_parameter\": \"<args path>\",\n  \"received_value\": null,\n  \"expected\": \"<what was expected>\",\n  \"remediation\": \"<what to do next>\",\n  \"retryable\": \"never\",\n  \"retry_after_ms\": null,\n  \"next_action\": null,\n  \"request_id\": null,\n  \"trace\": { \"attempts\": 0 }\n}\n```\n\n",
    );
    out.push_str("Branch on `category` and `retryable`: `same_key_only` means retry only with the same \
                  idempotency key, and `OUTCOME_UNKNOWN` means the request may have been applied.\n\n");
    out.push_str("## Extending\n\n`src/custom/index.ts` is yours: it is created once, never overwritten, and exported as `custom`.\n");
    out
}
